/**
 * Data Connect integration layer for plan builder operations.
 * Provides typed Data Connect queries and mutations for starter templates, plans, and related entities.
 * Refs: D-114, BL-006, FR-212, FR-247, AC-256, BR-270
 * 
 * NOTE: This file demonstrates the integration pattern for Data Connect.
 * The actual generated SDK will be created by `firebase dataconnect:sdk:generate`
 * once the Firebase Data Connect schema migration is completed.
 */

import type { PlanType } from './plan-change-request.logic';
import type { StarterTemplate, TemplateUsageStats } from './starter-template.logic';

// ─── Data Connect Service Client ─────────────────────────────────────────────

/**
 * Initialize Data Connect client with Firebase configuration.
 * This will be auto-generated by Firebase Data Connect SDK.
 */
export interface DataConnectClient {
  query: (query: string, variables?: Record<string, unknown>) => Promise<unknown>;
  mutation: (mutation: string, variables?: Record<string, unknown>) => Promise<unknown>;
}

// ─── Query Operations ────────────────────────────────────────────────────────

/**
 * Query: Get all starter templates, optionally filtered by plan type.
 * Implements: filterStarterTemplates() from logic layer
 * @param planType Optional filter by 'nutrition' or 'training'
 * @returns Array of StarterTemplate objects
 */
export async function getStarterTemplates(
  client: DataConnectClient,
  planType?: PlanType
): Promise<StarterTemplate[]> {
  // This query is defined in dataconnect/connector/starter_templates.gql
  const response = await client.query(
    `
    query GetStarterTemplates($planType: String) {
      starter_templates(
        where: { plan_type: { eq: $planType } }
        orderBy: [{ name: ASC }]
      ) {
        edges {
          node {
            id
            plan_type
            name
            description
            created_at
            updated_at
          }
        }
      }
    }
    `,
    { planType }
  );

  // Parse and transform response
  const templates = ((response as any)?.starter_templates?.edges || []).map(
    (edge: any) => ({
      id: edge.node.id,
      planType: edge.node.plan_type as PlanType,
      name: edge.node.name,
      description: edge.node.description,
      createdAt: edge.node.created_at,
    })
  );

  return templates;
}

/**
 * Query: Get a single starter template by ID.
 * Implements: Template lookup for cloning operations
 * @param templateId The starter template ID to retrieve
 * @returns StarterTemplate object or null if not found
 */
export async function getStarterTemplate(
  client: DataConnectClient,
  templateId: string
): Promise<StarterTemplate | null> {
  const response = await client.query(
    `
    query GetStarterTemplate($id: String!) {
      starter_templates(where: { id: { eq: $id } }) {
        edges {
          node {
            id
            plan_type
            name
            description
            created_at
            updated_at
          }
        }
      }
    }
    `,
    { id: templateId }
  );

  const template = (response as any)?.starter_templates?.edges?.[0]?.node;
  if (!template) return null;

  return {
    id: template.id,
    planType: template.plan_type as PlanType,
    name: template.name,
    description: template.description,
    createdAt: template.created_at,
  };
}

/**
 * Query: Get nutrition templates.
 * Convenience method for nutrition plan builder.
 * @returns Array of nutrition StarterTemplate objects
 */
export async function getNutritionTemplates(
  client: DataConnectClient
): Promise<StarterTemplate[]> {
  return getStarterTemplates(client, 'nutrition');
}

/**
 * Query: Get training templates.
 * Convenience method for training plan builder.
 * @returns Array of training StarterTemplate objects
 */
export async function getTrainingTemplates(
  client: DataConnectClient
): Promise<StarterTemplate[]> {
  return getStarterTemplates(client, 'training');
}

/**
 * Query: Get template usage statistics.
 * Used to track popular templates and usage trends.
 * @param templateId The template ID to get stats for
 * @returns TemplateUsageStats object or null if not found
 */
export async function getTemplateStats(
  client: DataConnectClient,
  templateId: string
): Promise<TemplateUsageStats | null> {
  const response = await client.query(
    `
    query GetTemplateStats($templateId: String!) {
      template_usage_stats(where: { template_id: { eq: $templateId } }) {
        edges {
          node {
            template_id
            clone_count
            assignment_count
            updated_at
          }
        }
      }
    }
    `,
    { templateId }
  );

  const stats = (response as any)?.template_usage_stats?.edges?.[0]?.node;
  if (!stats) return null;

  return {
    templateId: stats.template_id,
    cloneCount: stats.clone_count,
    assignmentCount: stats.assignment_count,
  };
}

// ─── Mutation Operations ─────────────────────────────────────────────────────

/**
 * Mutation: Clone a starter template into a nutrition or training plan.
 * Implements: cloneStarterTemplate() stub
 * Links cloned plan to original template via source_template_id foreign key
 * @param professionalId The professional who owns the cloned plan
 * @param planName The name for the cloned plan
 * @param templateId The starter template ID to clone from
 * @param planType Whether to create 'nutrition' or 'training' plan
 * @returns The newly created plan ID
 */
export async function cloneStarterTemplate(
  client: DataConnectClient,
  professionalId: string,
  planName: string,
  templateId: string,
  planType: PlanType
): Promise<string> {
  const newPlanId = `plan_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

  const mutation =
    planType === 'nutrition'
      ? `
    mutation CloneNutritionTemplate(
      $id: String!
      $professionalId: String!
      $sourceTemplateId: String!
      $name: String!
    ) {
      insert_nutrition_plans(
        data: {
          id: $id
          professional_id: $professionalId
          source_template_id: $sourceTemplateId
          name: $name
          is_draft: true
        }
      ) {
        id
        professional_id
        source_template_id
        name
        is_draft
        created_at
      }
    }
    `
      : `
    mutation CloneTrainingTemplate(
      $id: String!
      $professionalId: String!
      $sourceTemplateId: String!
      $name: String!
    ) {
      insert_training_plans(
        data: {
          id: $id
          professional_id: $professionalId
          source_template_id: $sourceTemplateId
          name: $name
          is_draft: true
        }
      ) {
        id
        professional_id
        source_template_id
        name
        is_draft
        created_at
      }
    }
    `;

  await client.mutation(mutation, {
    id: newPlanId,
    professionalId,
    sourceTemplateId: templateId,
    name: planName,
  });

  // Increment clone count
  await incrementTemplateCloneCount(client, templateId);

  return newPlanId;
}

/**
 * Mutation: Increment template clone count when a template is cloned.
 * Called automatically by cloneStarterTemplate()
 * @param templateId The template ID to increment
 */
export async function incrementTemplateCloneCount(
  client: DataConnectClient,
  templateId: string
): Promise<void> {
  await client.mutation(
    `
    mutation IncrementTemplateCloneCount($templateId: String!) {
      update_template_usage_stats(
        where: { template_id: { eq: $templateId } }
        data: { clone_count: { increment: 1 } }
      ) {
        template_id
        clone_count
        updated_at
      }
    }
    `,
    { templateId }
  );
}

/**
 * Mutation: Increment template assignment count when a cloned plan is assigned to a student.
 * Should be called after student assignment through plan-change-request workflow
 * @param templateId The original template ID
 */
export async function incrementTemplateAssignmentCount(
  client: DataConnectClient,
  templateId: string
): Promise<void> {
  await client.mutation(
    `
    mutation IncrementTemplateAssignmentCount($templateId: String!) {
      update_template_usage_stats(
        where: { template_id: { eq: $templateId } }
        data: { assignment_count: { increment: 1 } }
      ) {
        template_id
        assignment_count
        updated_at
      }
    }
    `,
    { templateId }
  );
}

/**
 * Mutation: Initialize usage statistics for a newly created template (admin only).
 * @param templateId The template ID to initialize stats for
 */
export async function initializeTemplateStats(
  client: DataConnectClient,
  templateId: string
): Promise<TemplateUsageStats> {
  const response = await client.mutation(
    `
    mutation InitializeTemplateStats($templateId: String!) {
      insert_template_usage_stats(
        data: {
          template_id: $templateId
          clone_count: 0
          assignment_count: 0
        }
      ) {
        template_id
        clone_count
        assignment_count
      }
    }
    `,
    { templateId }
  );

  const stats = (response as any)?.insert_template_usage_stats;
  return {
    templateId: stats.template_id,
    cloneCount: stats.clone_count,
    assignmentCount: stats.assignment_count,
  };
}
