export const enUS = {
  'common.error.generic': 'Something went wrong. Try again.',
  'auth.field.email': 'Email',
  'auth.field.name': 'Name',
  'auth.field.password': 'Password',
  'auth.field.password_confirmation': 'Confirm password',
  'auth.placeholder.email': 'Email',
  'auth.placeholder.name': 'Full name',
  'auth.placeholder.password': 'Password',
  'auth.placeholder.password_confirmation': 'Confirm password',
  'auth.validation.name_required': 'Name is required.',
  'auth.validation.email_required': 'Email is required.',
  'auth.validation.password_required': 'Password is required.',
  'auth.validation.password_confirmation_required': 'Password confirmation is required.',
  'auth.validation.password_policy':
    'Use at least 8 characters with uppercase, number, and an ASCII symbol (e.g., ! @ #). Emoji are not allowed.',
  'auth.validation.password_confirmation_mismatch':
    'Password confirmation must match your password.',
  'auth.signin.title': 'Welcome back',
  'auth.signin.cta_primary': 'Sign in',
  'auth.signin.cta_create': 'Create account',
  'auth.signin.or_continue': 'or continue with',
  'auth.signin.error.invalid_credentials':
    'Email or password is incorrect. Try again or reset your password.',
  'auth.signin.error.network': "Couldn't connect right now. Check your connection and try again.",
  'auth.signin.error.provider_conflict':
    'This email is already linked to another sign-in method. Sign in with your existing method first.',
  'auth.signin.error.configuration':
    'Authentication is not configured yet. Set Firebase keys and try again.',
  'auth.social.google': 'Google',
  'auth.social.apple': 'Apple',
  'auth.password.toggle_show': 'Show password',
  'auth.password.toggle_hide': 'Hide password',
  'auth.password.toggle_show_short': 'Show',
  'auth.password.toggle_hide_short': 'Hide',
  'auth.signup.title': 'Create your account',
  'auth.signup.cta_primary': 'Create account',
  'auth.signup.or_continue': 'or continue with',
  'auth.signup.password_helper':
    'Use at least 8 characters, including uppercase, number, and a symbol (e.g., ! @ #).',
  'auth.signup.error.duplicate_email': 'This email is already in use. Sign in to continue.',
  'auth.signup.error.network': "Couldn't connect right now. Check your connection and try again.",
  'auth.signup.error.provider_conflict':
    'This email is already linked to another sign-in method. Sign in with your existing method first.',
  'auth.signup.error.configuration':
    'Authentication is not configured yet. Set Firebase keys and try again.',
  'auth.signup.placeholder.body':
    'Create-account form implementation starts in the next screen slice.',
  'auth.signup.cta_back_signin': 'Back to sign in',
  'auth.role.title': 'How do you want to use the app?',
  'auth.role.intro': 'You can start on your own now and connect with a professional later.',
  'auth.role.option_self.title': 'I want to track my own progress',
  'auth.role.option_self.subtitle': 'Log meals and workouts by yourself. No professional required.',
  'auth.role.option_pro.title': "I'm a nutritionist or fitness coach",
  'auth.role.option_pro.subtitle': 'Manage clients, assign plans, and track student progress.',
  'auth.role.lock_note':
    "Account type can't be changed later. You can create another account with a different email if needed.",
  'auth.role.cta_continue': 'Continue',
  'auth.role.cta_back': 'Back',
  'auth.role.cta_start_self_guided': 'Start on my own now',
  'auth.role.validation.required': 'Choose how you want to use the app to continue.',
  'auth.role.error.save_failed': 'Could not save your role right now. Try again.',
  'auth.role.placeholder.title': 'Role selection',
  'auth.role.placeholder.body':
    'Sign-in flow is wired. Role-selection implementation is the next screen slice.',
  'auth.role.placeholder.cta_open_app_shell': 'Open app shell',
  'student.home.no_pro.title': 'No professional connected yet',
  'student.home.no_pro.body': 'You can still start tracking today on your own.',
  'student.home.cta_start_nutrition': 'Start my nutrition plan',
  'student.home.cta_start_training': 'Start my training plan',
  'student.home.cta_manage_professionals': 'Manage professionals',
  'student.home.offline.stale_badge': 'Data may be outdated',
  'student.home.offline.last_sync': 'Last updated: {datetime}',
  'student.home.offline.banner_read_only':
    "You're offline. You can view cached data, but updates are locked until connection returns.",
  'student.home.offline.write_lock': 'Connect to the internet to save changes.',
  'relationship.title': 'Connect with professionals',
  'relationship.intro': 'Have a professional? Enter their invite code.',
  'relationship.helper_self_guided': "Don't have one yet? You can keep using the app on your own.",
  'relationship.input.invite_code': 'Enter invite code',
  'relationship.cta_scan_qr': 'Scan QR code',
  'relationship.qr.permission_denied':
    "Camera access is required to scan a QR code. Grant permission in your device settings, or type the code manually.",
  'relationship.qr.invalid_payload':
    "This QR code doesn't contain a valid invite code. Try scanning again or enter the code manually.",
  'relationship.qr.close': 'Close scanner',
  'relationship.cta_submit_code': 'Connect',
  'relationship.error.invalid_code':
    'This invite code is invalid. Ask your professional for a new code.',
  'relationship.error.already_connected':
    'You are already connected to a professional in this specialty.',
  'relationship.error.pending_cap':
    'This professional has too many pending requests right now. Try again later.',
  'relationship.error.network': "Couldn't connect right now. Check your connection and try again.",
  'relationship.error.unknown': 'Something went wrong. Try again.',
  'relationship.pending.helper': 'Waiting for professional confirmation to activate this connection.',
  'relationship.pending.canceled_code_rotated':
    'This request was canceled because the professional regenerated their invite code. Ask for the new code to reconnect.',
  'relationship.empty.cta_continue_self': 'Continue self-guided',
  'relationship.unbind.cta': 'End connection',
  'relationship.unbind.confirm_title': 'End this professional connection?',
  'relationship.unbind.confirm_body':
    'You can reconnect later with an invite code. Your history will be kept.',
  'relationship.unbind.confirm_yes': 'End connection',
  'relationship.unbind.confirm_no': 'Keep connection',
  'relationship.unbind.error': 'Could not end the connection. Try again.',
  'relationship.credential.registry_id': 'Registry ID',
  'relationship.credential.authority': 'Authority',
  'relationship.credential.country': 'Country',
  'pro.pending.search.placeholder': 'Search pending requests',
  'pro.pending.filter.label': 'Filter requests',
  'pro.pending.bulk_deny.cta': 'Deny selected',
  'pro.pending.bulk_deny.confirm_title': 'Deny selected requests?',
  'pro.pending.bulk_deny.confirm_body':
    'Selected students can request again later with your invite code.',
  'pro.pending.bulk_deny.success': 'Requests denied successfully.',
  'pro.pending.confirm.cta': 'Accept',
  'pro.pending.deny.cta': 'Deny',
  'pro.pending.empty': 'No pending connection requests.',
  'pro.pending.error': 'Could not load pending requests. Try again.',
  'common.error.retry': 'Try again',
  'common.loading.default': 'Loading...',
  'common.empty.no_data': 'Nothing here yet.',
  'student.hydration.card_title': 'Water intake',
  'student.hydration.progress': '{consumed} / {goal} ml',
  'student.hydration.cta_log': 'Log water',
  'student.hydration.cta_set_goal': 'Set water goal',
  'student.hydration.goal_owner_student': 'Using your personal water goal',
  'student.hydration.goal_owner_nutritionist': 'Daily water goal defined by your nutritionist',
  'student.hydration.streak': 'Current streak: {days} days',
  'shell.common.period': '.',
  'shell.token.path.tabs_index': 'app/(tabs)/index.tsx',
  'shell.token.path.tabs_explore': 'app/(tabs)/explore.tsx',
  'shell.token.path.tabs_layout': 'app/(tabs)/_layout.tsx',
  'shell.token.path.components_hello_wave': 'components/HelloWave.tsx',
  'shell.token.path.components_parallax_scroll_view': 'components/ParallaxScrollView.tsx',
  'shell.token.path.app': 'app',
  'shell.token.path.app_example': 'app-example',
  'shell.token.command.reset_project': 'npm run reset-project',
  'shell.token.shortcut.devtools_ios': 'cmd + d',
  'shell.token.shortcut.devtools_android': 'cmd + m',
  'shell.token.shortcut.devtools_web': 'F12',
  'shell.token.shortcut.open_web': 'w',
  'shell.token.image_suffix.2x': '@2x',
  'shell.token.image_suffix.3x': '@3x',
  'shell.token.hook.use_color_scheme': 'useColorScheme()',
  'shell.token.library.react_native_reanimated': 'react-native-reanimated',
  'student.home.title': 'My Dashboard',
  'student.home.hydration.title': 'Water intake',
  'student.home.hydration.progress': '{consumed} / {goal} ml',
  'student.home.hydration.streak': 'Streak: {days} days',
  'student.home.hydration.goal_student': 'Using your personal water goal',
  'student.home.hydration.goal_nutritionist': 'Daily water goal set by your nutritionist',
  'student.home.hydration.no_goal': 'Set a daily water goal to track progress',
  'student.home.nutrition.section': 'Nutrition',
  'student.home.training.section': 'Training',
  'student.home.pending_connection': 'Pending professional confirmation',
  'student.home.cta_nutrition': 'Go to nutrition',
  'student.home.cta_training': 'Go to training',
  'student.home.cta_professionals': 'Manage professionals',
  'student.nutrition.title': 'Nutrition today',
  'student.nutrition.empty.title': 'No meals logged yet',
  'student.nutrition.empty.body': 'No nutritionist connected? You can still build and track your own plan today.',
  'student.nutrition.empty.cta': 'Start my nutrition plan',
  'student.nutrition.water.title': 'Water intake',
  'student.nutrition.water.personal_goal': 'Set your daily water goal.',
  'student.nutrition.water.nutritionist_goal': 'Daily water goal defined by your nutritionist.',
  'student.nutrition.water.cta_log': 'Log water',
  'student.nutrition.water.cta_set_goal': 'Set water goal',
  'student.nutrition.water.log.label': 'Amount (ml)',
  'student.nutrition.water.log.placeholder': 'e.g. 250',
  'student.nutrition.water.log.validation.required': 'Amount is required.',
  'student.nutrition.water.log.validation.must_be_positive': 'Amount must be greater than zero.',
  'student.nutrition.water.goal.label': 'Daily goal (ml)',
  'student.nutrition.water.goal.placeholder': 'e.g. 2000',
  'student.nutrition.water.goal.validation.required': 'Goal is required.',
  'student.nutrition.water.goal.validation.must_be_positive': 'Goal must be greater than zero.',
  'student.nutrition.plan_change.cta': 'Request plan change',
  'student.nutrition.plan_change.title': 'Request a plan change',
  'student.nutrition.plan_change.label': 'What would you like to change?',
  'student.nutrition.plan_change.placeholder': 'Describe what you would like adjusted...',
  'student.nutrition.plan_change.validation.required': 'Request description is required.',
  'student.nutrition.plan_change.validation.too_short': 'Please describe your request in more detail.',
  'student.nutrition.plan_change.error.plan_not_found': 'Plan not found. Pull to refresh.',
  'student.nutrition.plan_change.error.no_active_assignment': 'You do not have an active assigned plan.',
  'student.nutrition.plan_change.error.network': "Couldn't connect. Check your connection and try again.",
  'student.nutrition.plan_change.error.unknown': 'Something went wrong. Try again.',
  'student.nutrition.plan_change.success': 'Change request sent.',
  'student.nutrition.assigned_plan.read_only_notice': 'Your nutrition plan is professionally assigned. Contact your nutritionist to request changes.',
  'student.training.title': 'Training today',
  'student.training.empty.title': 'No workout scheduled yet',
  'student.training.empty.body': 'No coach connected? You can still create your own training plan now.',
  'student.training.empty.cta': 'Start my training plan',
  'student.training.plan_change.cta': 'Request plan change',
  'student.training.plan_change.title': 'Request a plan change',
  'student.training.plan_change.label': 'What would you like to change?',
  'student.training.plan_change.placeholder': 'Describe what you would like adjusted...',
  'student.training.plan_change.validation.required': 'Request description is required.',
  'student.training.plan_change.validation.too_short': 'Please describe your request in more detail.',
  'student.training.plan_change.error.plan_not_found': 'Plan not found. Pull to refresh.',
  'student.training.plan_change.error.no_active_assignment': 'You do not have an active assigned plan.',
  'student.training.plan_change.error.network': "Couldn't connect. Check your connection and try again.",
  'student.training.plan_change.error.unknown': 'Something went wrong. Try again.',
  'student.training.plan_change.success': 'Change request sent.',
  'student.training.assigned_plan.read_only_notice': 'Your training plan is professionally assigned. Contact your coach to request changes.',
  'pro.home.title': 'Dashboard',
  'pro.home.active_students': 'Active students',
  'pro.home.pending_requests': 'Pending requests',
  'pro.home.invite_code.title': 'Your invite code',
  'pro.home.invite_code.share': 'Share code',
  'pro.home.invite_code.rotate': 'Regenerate code',
  'pro.home.invite_code.rotate_confirm_title': 'Regenerate invite code?',
  'pro.home.invite_code.rotate_confirm_body': 'Your current code will be invalidated and all pending requests from it will be automatically canceled.',
  'pro.home.invite_code.rotate_confirm_yes': 'Regenerate',
  'pro.home.invite_code.rotate_confirm_no': 'Cancel',
  'pro.home.invite_code.rotate_error': 'Could not regenerate code. Try again.',
  'pro.home.invite_code.empty': 'No active invite code.',
  'pro.home.cta_roster': 'View student roster',
  'pro.home.cta_pending': 'Manage pending requests',
  'pro.home.subscription.warning': 'Your subscription is expiring soon. Renew to keep managing all your students.',
  'pro.home.subscription.cta_renew': 'Renew subscription',
  'pro.home.entitlement_lock': 'Student-plan actions are locked. Restore your subscription to unlock.',
  'pro.home.error': 'Could not load dashboard data. Try again.',
  'pro.specialty.title': 'Your specialties',
  'pro.specialty.nutritionist': 'Nutritionist',
  'pro.specialty.fitness_coach': 'Fitness Coach',
  'pro.specialty.add_nutritionist': 'Add Nutritionist',
  'pro.specialty.add_fitness_coach': 'Add Fitness Coach',
  'pro.specialty.remove': 'Remove',
  'pro.specialty.remove_blocked.active': 'Cannot remove: active students in this specialty.',
  'pro.specialty.remove_blocked.pending': 'Cannot remove: pending students in this specialty.',
  'pro.specialty.remove_blocked.last': 'Cannot remove: at least one specialty is required.',
  'pro.specialty.remove_error': 'Could not remove specialty. Try again.',
  'pro.specialty.add_error': 'Could not add specialty. Try again.',
  'pro.specialty.credential.title': 'Registry credential (optional)',
  'pro.specialty.credential.registry_id.label': 'Registry ID',
  'pro.specialty.credential.registry_id.placeholder': 'e.g. CRN-12345',
  'pro.specialty.credential.authority.label': 'Authority',
  'pro.specialty.credential.authority.placeholder': 'e.g. CFN',
  'pro.specialty.credential.country.label': 'Country',
  'pro.specialty.credential.country.placeholder': 'e.g. Brazil',
  'pro.specialty.credential.save': 'Save credential',
  'pro.specialty.credential.skip': 'Skip',
  'pro.specialty.credential.save_error': 'Could not save credential. Try again.',
  'pro.specialty.empty': 'No specialties added yet.',
  'pro.specialty.removal_assist.view_active': 'View active students',
  'pro.specialty.removal_assist.view_active_desc': 'See and manage active student assignments',
  'pro.specialty.removal_assist.view_pending': 'View pending requests',
  'pro.specialty.removal_assist.view_pending_desc': 'Review pending connection requests',
  'pro.specialty.removal_assist.bulk_deny': 'Deny pending requests',
  'pro.specialty.removal_assist.bulk_deny_desc': 'Bulk deny pending requests to clear blockers',
  'pro.specialty.removal_assist.add_specialty': 'Add another specialty',
  'pro.specialty.removal_assist.add_specialty_desc': 'Add Nutritionist or Fitness Coach to enable removal',
  'pro.students.title': 'My students',
  'pro.students.search.placeholder': 'Search students',
  'pro.students.filter.active': 'Active',
  'pro.students.filter.pending': 'Pending',
  'pro.students.filter.all': 'All',
  'pro.students.empty': 'No students yet.',
  'pro.students.error': 'Could not load student roster. Try again.',
  'pro.students.bulk_assign.cta': 'Bulk assign plan',
  'pro.students.bulk_assign.select_hint': 'Select students to assign a plan.',
  'pro.students.specialty.nutritionist': 'Nutritionist',
  'pro.students.specialty.fitness_coach': 'Fitness Coach',
  'pro.student_profile.title': 'Student profile',
  'pro.student_profile.specialty.nutritionist': 'Nutrition',
  'pro.student_profile.specialty.fitness_coach': 'Training',
  'pro.student_profile.assignment.active': 'Active',
  'pro.student_profile.assignment.pending': 'Pending confirmation',
  'pro.student_profile.assignment.none': 'No active assignment',
  'pro.student_profile.unbind.cta': 'End assignment',
  'pro.student_profile.unbind.confirm_title': 'End this assignment?',
  'pro.student_profile.unbind.confirm_body': 'The student will be unlinked. History is retained.',
  'pro.student_profile.unbind.confirm_yes': 'End assignment',
  'pro.student_profile.unbind.confirm_no': 'Keep assignment',
  'pro.student_profile.unbind.error': 'Could not end assignment. Try again.',
  'pro.student_profile.plan_change_requests.title': 'Plan change requests',
  'pro.student_profile.plan_change_requests.empty': 'No pending change requests.',
  'pro.student_profile.plan_change_requests.review': 'Mark reviewed',
  'pro.student_profile.plan_change_requests.dismiss': 'Dismiss',
  'pro.student_profile.plan_change_requests.load_error': 'Could not load change requests. Try again.',
  'pro.student_profile.plan_change_requests.action_error': 'Could not update request. Try again.',
  'pro.student_profile.water_goal.title': 'Student water goal',
  'pro.student_profile.water_goal.label': 'Daily goal (ml)',
  'pro.student_profile.water_goal.placeholder': 'e.g. 2500',
  'pro.student_profile.water_goal.save': 'Set goal',
  'pro.student_profile.water_goal.validation.required': 'Goal amount is required.',
  'pro.student_profile.water_goal.validation.must_be_positive': 'Goal must be greater than zero.',
  'pro.student_profile.water_goal.error': 'Could not set water goal. Try again.',
  'pro.student_profile.entitlement_lock': 'Plan actions are locked. Restore your subscription to unlock.',
  'pro.student_profile.error': 'Could not load student profile. Try again.',
  'pro.subscription.title': 'Subscription',
  'pro.subscription.status.active': 'Active',
  'pro.subscription.status.inactive': 'Inactive',
  'pro.subscription.status.unknown': 'Checking...',
  'pro.subscription.cap_usage': '{count} / {limit} active students',
  'pro.subscription.free_tier': 'Free up to 10 active students.',
  'pro.subscription.warning': 'Your subscription is expiring soon. Renew to avoid service interruption.',
  'pro.subscription.locked': 'Student-plan actions are locked. Restore or purchase a subscription to continue.',
  'pro.subscription.cta_purchase': 'Upgrade plan',
  'pro.subscription.cta_restore': 'Restore purchase',
  'pro.subscription.cta_refresh': 'Refresh status',
  'pro.subscription.purchase_note': 'Subscription is managed through your device app store.',
  'pro.subscription.error': 'Could not load subscription status. Try again.',
  'offline.banner': "You're offline. Showing cached data. Updates are locked until you reconnect.",
  'offline.write_lock': 'Connect to the internet to save changes.',
  'offline.stale_minutes': 'Last updated {value} min ago',
  'offline.stale_hours': 'Last updated {value}h ago',
  'offline.stale_days': 'Last updated {value}d ago',
  'settings.account.title': 'Account & Privacy',
  'settings.account.privacy_policy.label': 'Privacy Policy',
  'settings.account.privacy_policy.cta': 'View Privacy Policy',
  'settings.account.delete.title': 'Delete account',
  'settings.account.delete.body': 'Deleting your account removes your personal data. Some anonymized records may be retained as required by policy.',
  'settings.account.delete.cta': 'Request account deletion',
  'settings.account.delete.confirm_title': 'Delete your account?',
  'settings.account.delete.confirm_body': 'This action is irreversible. Your personal information will be removed. Anonymized history may be retained for legal, billing, and continuity requirements.',
  'settings.account.delete.confirm_yes': 'Delete account',
  'settings.account.delete.confirm_no': 'Cancel',
  'settings.account.delete.success': 'Your account deletion request has been submitted.',
  'settings.account.delete.error.network': "Couldn't connect. Check your connection and try again.",
  'settings.account.delete.error.unknown': 'Something went wrong. Try again.',
  'settings.account.delete.error.already_requested': 'A deletion request is already in progress.',
  'meal.builder.title.create': 'Create custom meal',
  'meal.builder.title.edit': 'Edit meal',
  'meal.builder.helper': 'Add total meal weight and nutrients. We use this to calculate any portion you log.',
  'meal.builder.field.name.label': 'Meal name',
  'meal.builder.field.name.placeholder': 'e.g. Grilled chicken bowl',
  'meal.builder.field.grams.label': 'Total weight (g)',
  'meal.builder.field.grams.placeholder': 'e.g. 350',
  'meal.builder.field.calories.label': 'Calories (kcal)',
  'meal.builder.field.calories.placeholder': 'e.g. 520',
  'meal.builder.field.carbs.label': 'Carbs (g)',
  'meal.builder.field.carbs.placeholder': 'e.g. 45',
  'meal.builder.field.proteins.label': 'Proteins (g)',
  'meal.builder.field.proteins.placeholder': 'e.g. 38',
  'meal.builder.field.fats.label': 'Fats (g)',
  'meal.builder.field.fats.placeholder': 'e.g. 12',
  'meal.builder.field.cost.label': 'Ingredient cost (optional)',
  'meal.builder.field.cost.placeholder': 'e.g. 4.50',
  'meal.builder.cta_save': 'Save meal',
  'meal.builder.cta_share': 'Share recipe',
  'meal.builder.image.cta_upload': 'Upload photo',
  'meal.builder.image.cta_change': 'Change photo',
  'meal.builder.image.uploading': 'Uploading... {percent}%',
  'meal.builder.image.upload_failed': 'Photo upload failed. Tap to retry.',
  'meal.builder.image.cta_retry': 'Retry upload',
  'meal.builder.validation.name_required': 'Meal name is required.',
  'meal.builder.validation.grams_required': 'Total weight is required.',
  'meal.builder.validation.grams_positive': 'Total weight must be greater than zero.',
  'meal.builder.validation.calories_required': 'Calories are required.',
  'meal.builder.validation.calories_non_negative': 'Calories must be zero or more.',
  'meal.builder.validation.carbs_required': 'Carbs are required.',
  'meal.builder.validation.carbs_non_negative': 'Carbs must be zero or more.',
  'meal.builder.validation.proteins_required': 'Proteins are required.',
  'meal.builder.validation.proteins_non_negative': 'Proteins must be zero or more.',
  'meal.builder.validation.fats_required': 'Fats are required.',
  'meal.builder.validation.fats_non_negative': 'Fats must be zero or more.',
  'meal.builder.validation.cost_non_negative': 'Ingredient cost must be zero or more.',
  'meal.builder.error.save': 'Could not save meal. Try again.',
  'meal.builder.error.load': 'Could not load meal. Try again.',
  'meal.builder.share.error.needs_save': 'Save the meal first to share it.',
  'meal.builder.share.error.unknown': 'Could not generate share link. Try again.',
  'meal.library.title': 'My custom meals',
  'meal.library.empty.title': 'No custom meals yet',
  'meal.library.empty.body': 'Create your first custom meal to log portions in seconds.',
  'meal.library.cta_create': 'Create meal',
  'meal.library.error': 'Could not load custom meals. Try again.',
  'meal.library.quick_log.title': 'Log meal',
  'meal.library.quick_log.helper': 'Enter grams consumed. We calculate calories and macros automatically.',
  'meal.library.quick_log.field.label': 'Grams consumed',
  'meal.library.quick_log.field.placeholder': 'e.g. 200',
  'meal.library.quick_log.preview.calories': '{calories} kcal',
  'meal.library.quick_log.preview.macros': '{carbs}g carbs · {proteins}g protein · {fats}g fat',
  'meal.library.quick_log.cta_log': 'Log meal',
  'meal.library.quick_log.cta_cancel': 'Cancel',
  'meal.library.quick_log.validation.required': 'Amount is required.',
  'meal.library.quick_log.validation.positive': 'Amount must be greater than zero.',
  'meal.library.quick_log.error': 'Could not save log entry. Try again.',
  'meal.library.quick_log.success': 'Meal logged.',
  'meal.library.cta_share': 'Share recipe',
  'meal.library.cta_edit': 'Edit',
  'shared_recipe.title': 'Save shared recipe',
  'shared_recipe.helper': 'Save this recipe to your account to use it in your daily tracking.',
  'shared_recipe.ownership_note': 'After saving, this copy is yours even if the original creator deletes theirs.',
  'shared_recipe.cta_save': 'Save to my account',
  'shared_recipe.cta_cancel': 'Cancel',
  'shared_recipe.existing_copy': 'You already saved this recipe in your account.',
  'shared_recipe.auth_required': "Sign in to save this recipe. We'll bring you back here right after login.",
  'shared_recipe.nutrition.calories': '{calories} kcal',
  'shared_recipe.nutrition.macros': '{carbs}g carbs · {proteins}g protein · {fats}g fat',
  'shared_recipe.nutrition.weight': '{grams}g total',
  'shared_recipe.error.invalid_token': 'This recipe link is invalid or has expired.',
  'shared_recipe.error.network': "Couldn't connect. Check your connection and try again.",
  'shared_recipe.error.unknown': 'Something went wrong. Try again.',
  'shared_recipe.error.save': 'Could not save recipe. Try again.',
  'shared_recipe.success': 'Recipe saved to your account.',
  'a11y.loading.default': 'Loading…',
  'a11y.loading.submitting': 'Submitting…',
  'a11y.loading.saving': 'Saving…',
  'a11y.loading.invite_code': 'Loading invite code…',
  'a11y.selected_count': '{count} selected',
  'a11y.student_row': '{name}, {specialty}, {status}',
  'a11y.stat_card': '{value} {label}',
  'meal.photo_analysis.cta': 'Analyze with AI',
  'meal.photo_analysis.analyzing': 'Analyzing your meal…',
  'meal.photo_analysis.disclaimer': 'These are AI estimates. Please verify before saving.',
  'meal.photo_analysis.error.unrecognizable': "Couldn't identify a meal in this photo. Try again or fill in manually.",
  'meal.photo_analysis.error.quota': 'AI analysis is temporarily unavailable. Please fill in manually.',
  'meal.photo_analysis.error.network': 'Network error during analysis. Check your connection and try again.',
  'meal.photo_analysis.error.generic': 'Analysis failed. You can still fill in the fields manually.',
  'meal.photo_analysis.attach_photo.label': 'Also attach this photo to the meal',
  'meal.photo_analysis.confidence.low': 'Low confidence — double-check these estimates',
  'pro.library.nutrition.title': 'Nutrition Plans',
  'pro.library.nutrition.empty': 'No nutrition plans yet. Create your first plan.',
  'pro.library.nutrition.cta_create': 'Create nutrition plan',
  'pro.library.training.title': 'Training Plans',
  'pro.library.training.empty': 'No training plans yet. Create your first plan.',
  'pro.library.training.cta_create': 'Create training plan',
  'pro.library.cta_open': 'Open',
  'pro.library.error': 'Could not load plans. Try again.',
  'pro.plan.nutrition.title.create': 'Create nutrition plan',
  'pro.plan.nutrition.title.edit': 'Edit nutrition plan',
  'pro.plan.training.title.create': 'Create training plan',
  'pro.plan.training.title.edit': 'Edit training plan',
  'pro.plan.field.name.label': 'Plan name',
  'pro.plan.field.name.placeholder': 'e.g. Caloric Deficit A',
  'pro.plan.field.calories_target.label': 'Calorie target (kcal)',
  'pro.plan.field.calories_target.placeholder': 'e.g. 2000',
  'pro.plan.field.carbs_target.label': 'Carbs target (g)',
  'pro.plan.field.proteins_target.label': 'Proteins target (g)',
  'pro.plan.field.fats_target.label': 'Fats target (g)',
  'pro.plan.section.meals': 'Meals',
  'pro.plan.section.sessions': 'Sessions',
  'pro.plan.cta.add_meal': 'Add food item',
  'pro.plan.cta.add_session': 'Add session',
  'pro.plan.cta.add_item': 'Add item',
  'pro.plan.cta.save': 'Save plan',
  'pro.plan.cta.assign': 'Assign to student',
  'pro.plan.cta.bulk_assign': 'Bulk assign',
  'pro.plan.cta.clone_template': 'Start from template',
  'pro.plan.template.starter_label': 'Starter templates',
  'pro.plan.template.picker_title': 'Choose a starter template',
  'pro.plan.template.cta_use': 'Use this template',
  'pro.plan.food_search.placeholder': 'Search foods…',
  'pro.plan.food_search.empty': 'No foods found. Try a different search term.',
  'pro.plan.food_search.stub_notice': 'Food search will be available in a future update.',
  'pro.plan.validation.name_required': 'Plan name is required.',
  'pro.plan.validation.name_too_short': 'Plan name must be at least 2 characters.',
  'pro.plan.validation.calories_non_negative': 'Calorie target must be zero or more.',
  'pro.plan.validation.macros_non_negative': 'Macro targets must be zero or more.',
  'pro.plan.error.save': 'Could not save plan. Try again.',
  'pro.plan.error.load': 'Could not load plan. Try again.',
  'pro.plan.error.assign': 'Could not assign plan. Try again.',
  'pro.plan.assign.title': 'Assign plan',
  'pro.plan.assign.student_count': '{count} student(s) selected',
  'pro.plan.assign.confirm': 'Confirm assignment',
  'pro.plan.assign.fine_tune_notice': 'Each student receives an independent copy you can fine-tune before confirming.',
  'pro.plan.session.field.name.label': 'Session name',
  'pro.plan.session.field.name.placeholder': 'e.g. Day A — Upper Body',
  'pro.plan.session.field.notes.label': 'Session notes (optional)',
  'pro.plan.item.field.name.label': 'Exercise / item name',
  'pro.plan.item.field.name.placeholder': 'e.g. Bench Press',
  'pro.plan.item.field.quantity.label': 'Quantity (optional)',
  'pro.plan.item.field.quantity.placeholder': 'e.g. 3 sets × 10 reps',
  'pro.plan.item.field.notes.label': 'Notes (optional)',
  'pro.plan.predefined.label': 'Predefined plan',
  'shell.tabs.home': 'Home',
  'shell.tabs.dashboard': 'Dashboard',
  'shell.tabs.students': 'Students',
  'shell.tabs.nutrition': 'Nutrition',
  'shell.tabs.training': 'Training',
  'shell.tabs.recipes': 'Recipes',
  'shell.tabs.account': 'Account',
  'shell.tabs.explore': 'Explore',
  'shell.placeholder.coming_soon': 'Coming soon. Check back after the next update.',
  'shell.modal.title': 'Modal',
  'shell.modal.body_title': 'This is a modal',
  'shell.modal.link_home': 'Go to home screen',
  'shell.home.title': 'Welcome!',
  'shell.home.step1.title': 'Step 1: Try it',
  'shell.home.step1.part1': 'Edit',
  'shell.home.step1.part2': 'to see changes. Press',
  'shell.home.step1.part3': 'to open developer tools.',
  'shell.home.step2.title': 'Step 2: Explore',
  'shell.home.step2.description':
    "Tap the Explore tab to learn more about what's included in this starter app.",
  'shell.home.step3.title': 'Step 3: Get a fresh start',
  'shell.home.step3.part1': 'When you\'re ready, run',
  'shell.home.step3.part2': 'to get a fresh',
  'shell.home.step3.part3': 'directory. This will move the current',
  'shell.home.step3.part4': 'to',
  'shell.home.menu.action': 'Action',
  'shell.home.menu.share': 'Share',
  'shell.home.menu.more': 'More',
  'shell.home.menu.delete': 'Delete',
  'shell.home.alert.action': 'Action pressed',
  'shell.home.alert.share': 'Share pressed',
  'shell.home.alert.delete': 'Delete pressed',
  'shell.explore.title': 'Explore',
  'shell.explore.description': 'This app includes example code to help you get started.',
  'shell.explore.section.routing.title': 'File-based routing',
  'shell.explore.section.routing.line1.part1': 'This app has two screens:',
  'shell.explore.section.routing.line1.part2': 'and',
  'shell.explore.section.routing.line1.part3': '.',
  'shell.explore.section.routing.line2.part1': 'The layout file in',
  'shell.explore.section.routing.line2.part2': 'sets up the tab navigator.',
  'shell.explore.section.routing.learn_more': 'Learn more',
  'shell.explore.section.platform.title': 'Android, iOS, and web support',
  'shell.explore.section.platform.body.part1':
    'You can open this project on Android, iOS, and the web. To open the web version, press',
  'shell.explore.section.platform.body.part2': 'in the terminal running this project.',
  'shell.explore.section.images.title': 'Images',
  'shell.explore.section.images.body.part1': 'For static images, you can use the',
  'shell.explore.section.images.body.part2': 'and',
  'shell.explore.section.images.body.part3':
    'suffixes to provide files for different screen densities',
  'shell.explore.section.images.learn_more': 'Learn more',
  'shell.explore.section.theme.title': 'Light and dark mode components',
  'shell.explore.section.theme.body.part1': 'This template has light and dark mode support. The',
  'shell.explore.section.theme.body.part2':
    "lets you inspect what the user's current color scheme is, and so you can adjust UI colors accordingly.",
  'shell.explore.section.theme.learn_more': 'Learn more',
  'shell.explore.section.animations.title': 'Animations',
  'shell.explore.section.animations.body.part1': 'This template includes an example of an animated component. The',
  'shell.explore.section.animations.body.part2': 'component uses the powerful',
  'shell.explore.section.animations.body.part3': 'library to create a waving hand animation.',
  'shell.explore.section.animations.ios_extra.part1': 'The',
  'shell.explore.section.animations.ios_extra.part2':
    'component provides a parallax effect for the header image.',
} as const;

export type TranslationKey = keyof typeof enUS;
