export const enUS = {
  'common.error.generic': 'Something went wrong. Try again.',
  'auth.field.email': 'Email',
  'auth.field.name': 'Name',
  'auth.field.password': 'Password',
  'auth.field.password_confirmation': 'Confirm password',
  'auth.placeholder.email': 'Email',
  'auth.placeholder.name': 'Full name',
  'auth.placeholder.password': 'Password',
  'auth.placeholder.password_confirmation': 'Confirm password',
  'auth.validation.name_required': 'Name is required.',
  'auth.validation.email_required': 'Email is required.',
  'auth.validation.password_required': 'Password is required.',
  'auth.validation.password_confirmation_required': 'Password confirmation is required.',
  'auth.validation.password_policy':
    'Use at least 8 characters with uppercase, number, and an ASCII symbol (e.g., ! @ #). Emoji are not allowed.',
  'auth.validation.password_confirmation_mismatch':
    'Password confirmation must match your password.',
  'auth.signin.title': 'Welcome back',
  'auth.signin.cta_primary': 'Sign in',
  'auth.signin.cta_create': 'Create account',
  'auth.signin.or_continue': 'or continue with',
  'auth.signin.error.invalid_credentials':
    'Email or password is incorrect. Try again or reset your password.',
  'auth.signin.error.network': "Couldn't connect right now. Check your connection and try again.",
  'auth.signin.error.provider_conflict':
    'This email is already linked to another sign-in method. Sign in with your existing method first.',
  'auth.signin.error.configuration':
    'Authentication is not configured yet. Set Firebase keys and try again.',
  'auth.social.google': 'Google',
  'auth.social.apple': 'Apple',
  'auth.password.toggle_show': 'Show password',
  'auth.password.toggle_hide': 'Hide password',
  'auth.password.toggle_show_short': 'Show',
  'auth.password.toggle_hide_short': 'Hide',
  'auth.signup.title': 'Create your account',
  'auth.signup.cta_primary': 'Create account',
  'auth.signup.or_continue': 'or continue with',
  'auth.signup.password_helper':
    'Use at least 8 characters, including uppercase, number, and a symbol (e.g., ! @ #).',
  'auth.signup.error.duplicate_email': 'This email is already in use. Sign in to continue.',
  'auth.signup.error.network': "Couldn't connect right now. Check your connection and try again.",
  'auth.signup.error.provider_conflict':
    'This email is already linked to another sign-in method. Sign in with your existing method first.',
  'auth.signup.error.configuration':
    'Authentication is not configured yet. Set Firebase keys and try again.',
  'auth.signup.placeholder.body':
    'Create-account form implementation starts in the next screen slice.',
  'auth.signup.cta_back_signin': 'Back to sign in',
  'auth.role.title': 'How do you want to use the app?',
  'auth.role.intro': 'You can start on your own now and connect with a professional later.',
  'auth.role.option_self.title': 'I want to track my own progress',
  'auth.role.option_self.subtitle': 'Log meals and workouts by yourself. No professional required.',
  'auth.role.option_pro.title': "I'm a nutritionist or fitness coach",
  'auth.role.option_pro.subtitle': 'Manage clients, assign plans, and track student progress.',
  'auth.role.lock_note':
    "Account type can't be changed later. You can create another account with a different email if needed.",
  'auth.role.cta_continue': 'Continue',
  'auth.role.cta_back': 'Back',
  'auth.role.cta_start_self_guided': 'Start on my own now',
  'auth.role.validation.required': 'Choose how you want to use the app to continue.',
  'auth.role.error.save_failed': 'Could not save your role right now. Try again.',
  'auth.role.placeholder.title': 'Role selection',
  'auth.role.placeholder.body':
    'Sign-in flow is wired. Role-selection implementation is the next screen slice.',
  'auth.role.placeholder.cta_open_app_shell': 'Open app shell',
  'student.home.no_pro.title': 'No professional connected yet',
  'student.home.no_pro.body': 'You can still start tracking today on your own.',
  'student.home.cta_start_nutrition': 'Start my nutrition plan',
  'student.home.cta_start_training': 'Start my training plan',
  'student.home.cta_manage_professionals': 'Manage professionals',
  'student.home.offline.stale_badge': 'Data may be outdated',
  'student.home.offline.last_sync': 'Last updated: {datetime}',
  'student.home.offline.banner_read_only':
    "You're offline. You can view cached data, but updates are locked until connection returns.",
  'student.home.offline.write_lock': 'Connect to the internet to save changes.',
  'relationship.title': 'Connect with professionals',
  'relationship.intro': 'Have a professional? Enter their invite code.',
  'relationship.helper_self_guided': "Don't have one yet? You can keep using the app on your own.",
  'relationship.input.invite_code': 'Enter invite code',
  'relationship.cta_scan_qr': 'Scan QR code',
  'relationship.cta_submit_code': 'Connect',
  'relationship.error.invalid_code':
    'This invite code is invalid. Ask your professional for a new code.',
  'relationship.error.already_connected':
    'You are already connected to a professional in this specialty.',
  'relationship.error.pending_cap':
    'This professional has too many pending requests right now. Try again later.',
  'relationship.error.network': "Couldn't connect right now. Check your connection and try again.",
  'relationship.error.unknown': 'Something went wrong. Try again.',
  'relationship.pending.helper': 'Waiting for professional confirmation to activate this connection.',
  'relationship.pending.canceled_code_rotated':
    'This request was canceled because the professional regenerated their invite code. Ask for the new code to reconnect.',
  'relationship.empty.cta_continue_self': 'Continue self-guided',
  'relationship.unbind.cta': 'End connection',
  'relationship.unbind.confirm_title': 'End this professional connection?',
  'relationship.unbind.confirm_body':
    'You can reconnect later with an invite code. Your history will be kept.',
  'relationship.unbind.confirm_yes': 'End connection',
  'relationship.unbind.confirm_no': 'Keep connection',
  'relationship.unbind.error': 'Could not end the connection. Try again.',
  'relationship.credential.registry_id': 'Registry ID',
  'relationship.credential.authority': 'Authority',
  'relationship.credential.country': 'Country',
  'pro.pending.search.placeholder': 'Search pending requests',
  'pro.pending.filter.label': 'Filter requests',
  'pro.pending.bulk_deny.cta': 'Deny selected',
  'pro.pending.bulk_deny.confirm_title': 'Deny selected requests?',
  'pro.pending.bulk_deny.confirm_body':
    'Selected students can request again later with your invite code.',
  'pro.pending.bulk_deny.success': 'Requests denied successfully.',
  'pro.pending.confirm.cta': 'Accept',
  'pro.pending.deny.cta': 'Deny',
  'pro.pending.empty': 'No pending connection requests.',
  'pro.pending.error': 'Could not load pending requests. Try again.',
  'common.error.retry': 'Try again',
  'common.loading.default': 'Loading...',
  'common.empty.no_data': 'Nothing here yet.',
  'student.hydration.card_title': 'Water intake',
  'student.hydration.progress': '{consumed} / {goal} ml',
  'student.hydration.cta_log': 'Log water',
  'student.hydration.cta_set_goal': 'Set water goal',
  'student.hydration.goal_owner_student': 'Using your personal water goal',
  'student.hydration.goal_owner_nutritionist': 'Daily water goal defined by your nutritionist',
  'student.hydration.streak': 'Current streak: {days} days',
  'shell.common.period': '.',
  'shell.token.path.tabs_index': 'app/(tabs)/index.tsx',
  'shell.token.path.tabs_explore': 'app/(tabs)/explore.tsx',
  'shell.token.path.tabs_layout': 'app/(tabs)/_layout.tsx',
  'shell.token.path.components_hello_wave': 'components/HelloWave.tsx',
  'shell.token.path.components_parallax_scroll_view': 'components/ParallaxScrollView.tsx',
  'shell.token.path.app': 'app',
  'shell.token.path.app_example': 'app-example',
  'shell.token.command.reset_project': 'npm run reset-project',
  'shell.token.shortcut.devtools_ios': 'cmd + d',
  'shell.token.shortcut.devtools_android': 'cmd + m',
  'shell.token.shortcut.devtools_web': 'F12',
  'shell.token.shortcut.open_web': 'w',
  'shell.token.image_suffix.2x': '@2x',
  'shell.token.image_suffix.3x': '@3x',
  'shell.token.hook.use_color_scheme': 'useColorScheme()',
  'shell.token.library.react_native_reanimated': 'react-native-reanimated',
  'shell.tabs.home': 'Home',
  'shell.tabs.explore': 'Explore',
  'shell.modal.title': 'Modal',
  'shell.modal.body_title': 'This is a modal',
  'shell.modal.link_home': 'Go to home screen',
  'shell.home.title': 'Welcome!',
  'shell.home.step1.title': 'Step 1: Try it',
  'shell.home.step1.part1': 'Edit',
  'shell.home.step1.part2': 'to see changes. Press',
  'shell.home.step1.part3': 'to open developer tools.',
  'shell.home.step2.title': 'Step 2: Explore',
  'shell.home.step2.description':
    "Tap the Explore tab to learn more about what's included in this starter app.",
  'shell.home.step3.title': 'Step 3: Get a fresh start',
  'shell.home.step3.part1': 'When you\'re ready, run',
  'shell.home.step3.part2': 'to get a fresh',
  'shell.home.step3.part3': 'directory. This will move the current',
  'shell.home.step3.part4': 'to',
  'shell.home.menu.action': 'Action',
  'shell.home.menu.share': 'Share',
  'shell.home.menu.more': 'More',
  'shell.home.menu.delete': 'Delete',
  'shell.home.alert.action': 'Action pressed',
  'shell.home.alert.share': 'Share pressed',
  'shell.home.alert.delete': 'Delete pressed',
  'shell.explore.title': 'Explore',
  'shell.explore.description': 'This app includes example code to help you get started.',
  'shell.explore.section.routing.title': 'File-based routing',
  'shell.explore.section.routing.line1.part1': 'This app has two screens:',
  'shell.explore.section.routing.line1.part2': 'and',
  'shell.explore.section.routing.line1.part3': '.',
  'shell.explore.section.routing.line2.part1': 'The layout file in',
  'shell.explore.section.routing.line2.part2': 'sets up the tab navigator.',
  'shell.explore.section.routing.learn_more': 'Learn more',
  'shell.explore.section.platform.title': 'Android, iOS, and web support',
  'shell.explore.section.platform.body.part1':
    'You can open this project on Android, iOS, and the web. To open the web version, press',
  'shell.explore.section.platform.body.part2': 'in the terminal running this project.',
  'shell.explore.section.images.title': 'Images',
  'shell.explore.section.images.body.part1': 'For static images, you can use the',
  'shell.explore.section.images.body.part2': 'and',
  'shell.explore.section.images.body.part3':
    'suffixes to provide files for different screen densities',
  'shell.explore.section.images.learn_more': 'Learn more',
  'shell.explore.section.theme.title': 'Light and dark mode components',
  'shell.explore.section.theme.body.part1': 'This template has light and dark mode support. The',
  'shell.explore.section.theme.body.part2':
    "lets you inspect what the user's current color scheme is, and so you can adjust UI colors accordingly.",
  'shell.explore.section.theme.learn_more': 'Learn more',
  'shell.explore.section.animations.title': 'Animations',
  'shell.explore.section.animations.body.part1': 'This template includes an example of an animated component. The',
  'shell.explore.section.animations.body.part2': 'component uses the powerful',
  'shell.explore.section.animations.body.part3': 'library to create a waving hand animation.',
  'shell.explore.section.animations.ios_extra.part1': 'The',
  'shell.explore.section.animations.ios_extra.part2':
    'component provides a parallax effect for the header image.',
} as const;

export type TranslationKey = keyof typeof enUS;
