export const enUS = {
  'common.error.generic': 'Something went wrong. Try again.',
  'common.back': 'Back',
  'settings.language_select.title': 'Language',
  'settings.language_select.save': 'Save',
  'settings.language_select.section_header': 'App Language',
  'auth.field.email': 'Email',
  'auth.field.name': 'Name',
  'auth.field.password': 'Password',
  'auth.field.password_confirmation': 'Confirm password',
  'auth.placeholder.email': 'Email',
  'auth.placeholder.name': 'Full name',
  'auth.placeholder.password': 'Password',
  'auth.placeholder.password_confirmation': 'Confirm password',
  'auth.validation.name_required': 'Name is required.',
  'auth.validation.email_required': 'Email is required.',
  'auth.validation.password_required': 'Password is required.',
  'auth.validation.password_confirmation_required': 'Password confirmation is required.',
  'auth.validation.password_policy':
    'Use at least 8 characters with uppercase, number, and an ASCII symbol (e.g., ! @ #). Emoji are not allowed.',
  'auth.validation.password_confirmation_mismatch':
    'Password confirmation must match your password.',
  'auth.signin.title': 'Welcome, Champion',
  'auth.signin.subtitle': 'Ready to crush your goals today?',
  'auth.signin.field.email': 'Email Address',
  'auth.signin.placeholder.email': 'champion@example.com',
  'auth.signin.placeholder.password': '••••••••',
  'auth.signin.cta_primary': 'Sign In',
  'auth.signin.new_here': 'New here?',
  'auth.signin.cta_create': 'Create an account',
  'auth.signin.or_continue': 'Or continue with',
  'auth.signin.error.invalid_credentials':
    'Email or password is incorrect. Try again or reset your password.',
  'auth.signin.error.network': "Couldn't connect right now. Check your connection and try again.",
  'auth.signin.error.provider_conflict':
    'This email is already linked to another sign-in method. Sign in with your existing method first.',
  'auth.signin.error.configuration':
    'Authentication is not configured yet. Set Firebase keys and try again.',
  'auth.terms.title': 'Terms and Privacy',
  'auth.terms.description': 'Before continuing, review and accept the latest terms for My Champions.',
  'auth.terms.open_link': 'Open terms and privacy policy',
  'auth.terms.checkbox': 'I have read and agree with the terms and privacy policy.',
  'auth.terms.accept_button': 'Accept and continue',
  'auth.terms.offline_hint': 'You need internet access to open the legal link.',
  'auth.terms.version': 'Required version: {version}',
  'auth.terms.error.link_unavailable': 'Could not open the terms link right now. Try again.',
  'auth.social.google': 'Google',
  'auth.social.apple': 'Apple',
  'auth.password.toggle_show': 'Show password',
  'auth.password.toggle_hide': 'Hide password',
  'auth.password.toggle_show_short': 'Show',
  'auth.password.toggle_hide_short': 'Hide',
  'auth.signup.title': 'Create your account',
  'auth.signup.cta_primary': 'Create account',
  'auth.signup.or_continue': 'or continue with',
  'auth.signup.password_helper':
    'Use at least 8 characters, including uppercase, number, and a symbol (e.g., ! @ #).',
  'auth.signup.error.duplicate_email': 'This email is already in use. Sign in to continue.',
  'auth.signup.error.network': "Couldn't connect right now. Check your connection and try again.",
  'auth.signup.error.provider_conflict':
    'This email is already linked to another sign-in method. Sign in with your existing method first.',
  'auth.signup.error.configuration':
    'Authentication is not configured yet. Set Firebase keys and try again.',
  'auth.signup.placeholder.body':
    'Create-account form implementation starts in the next screen slice.',
  'auth.signup.already_have': 'Already have an account?',
  'auth.signup.cta_back_signin': 'Back to sign in',
  'auth.role.title': 'Choose your path',
  'auth.role.intro': 'Are you here to track your own fitness journey, or to guide others as a professional?',
  'auth.role.option_self.title': 'I want to track my own progress',
  'auth.role.option_self.subtitle': 'Student account',
  'auth.role.option_self.description': 'Log meals, track workouts, and hit your goals — on your own or with a coach.',
  'auth.role.option_pro.title': "I'm a nutritionist or fitness coach",
  'auth.role.option_pro.subtitle': 'Professional account',
  'auth.role.option_pro.description': 'Create plans, manage your students, and track their progress in one place.',
  'auth.role.lock_note': "This can't be changed later — each role has a separate account.",
  'auth.role.cta_continue': 'Continue',
  'auth.role.cta_back': 'Back',
  'auth.role.validation.required': 'Choose how you want to use the app to continue.',
  'auth.role.error.save_failed': 'Could not save your role right now. Try again.',
  'auth.role.error.navigation_failed': 'Could not continue right now. Try again.',
  'auth.role.error.auth_required': 'Your session expired. Please sign in again.',
  'auth.role.placeholder.title': 'Role selection',
  'auth.role.placeholder.body':
    'Sign-in flow is wired. Role-selection implementation is the next screen slice.',
  'auth.role.placeholder.cta_open_app_shell': 'Open app shell',
  'student.home.no_pro.title': 'No professional connected yet',
  'student.home.no_pro.body': 'You can still start tracking today on your own.',
  'student.home.cta_start_nutrition': 'Start my nutrition plan',
  'student.home.cta_start_training': 'Start my training plan',
  'student.home.cta_manage_professionals': 'Manage professionals',
  'student.home.offline.stale_badge': 'Data may be outdated',
  'student.home.offline.last_sync': 'Last updated: {datetime}',
  'student.home.offline.banner_read_only':
    "You're offline. You can view cached data, but updates are locked until connection returns.",
  'student.home.offline.write_lock': 'Connect to the internet to save changes.',
  'relationship.title': 'Connect with professionals',
  'relationship.intro': 'Have a professional? Enter their invite code.',
  'relationship.helper_self_guided': "Don't have one yet? You can keep using the app on your own.",
  'relationship.input.invite_code': 'Enter invite code',
  'relationship.cta_scan_qr': 'Scan QR code',
  'relationship.qr.permission_denied':
    "Camera access is required to scan a QR code. Grant permission in your device settings, or type the code manually.",
  'relationship.qr.invalid_payload':
    "This QR code doesn't contain a valid invite code. Try scanning again or enter the code manually.",
  'relationship.qr.close': 'Close scanner',
  'relationship.cta_submit_code': 'Connect',
  'relationship.error.invalid_code':
    'This invite code is invalid. Ask your professional for a new code.',
  'relationship.error.already_connected':
    'You are already connected to a professional in this specialty.',
  'relationship.error.pending_cap':
    'This professional has too many pending requests right now. Try again later.',
  'relationship.error.network': "Couldn't connect right now. Check your connection and try again.",
  'relationship.error.unknown': 'Something went wrong. Try again.',
  'relationship.pending.helper': 'Waiting for professional confirmation to activate this connection.',
  'relationship.pending.canceled_code_rotated':
    'This request was canceled because the professional regenerated their invite code. Ask for the new code to reconnect.',
  'relationship.empty.cta_continue_self': 'Continue self-guided',
  'relationship.unbind.cta': 'End connection',
  'relationship.unbind.confirm_title': 'End this professional connection?',
  'relationship.unbind.confirm_body':
    'You can reconnect later with an invite code. Your history will be kept.',
  'relationship.unbind.confirm_yes': 'End connection',
  'relationship.unbind.confirm_no': 'Keep connection',
  'relationship.unbind.error': 'Could not end the connection. Try again.',
  'relationship.credential.registry_id': 'Registry ID',
  'relationship.credential.authority': 'Authority',
  'relationship.credential.country': 'Country',
  'pro.pending.search.placeholder': 'Search pending requests',
  'pro.pending.filter.label': 'Filter requests',
  'pro.pending.bulk_deny.cta': 'Deny selected',
  'pro.pending.bulk_deny.confirm_title': 'Deny selected requests?',
  'pro.pending.bulk_deny.confirm_body':
    'Selected students can request again later with your invite code.',
  'pro.pending.bulk_deny.success': 'Requests denied successfully.',
  'pro.pending.confirm.cta': 'Accept',
  'pro.pending.deny.cta': 'Deny',
  'pro.pending.empty': 'No pending connection requests.',
  'pro.pending.error': 'Could not load pending requests. Try again.',
  'common.error.retry': 'Try again',
  'pro.plan.cta.add_food': 'Add food item',
  'student.plan.cta.add_food': 'Add food item',
  'common.cta.add': 'Add',
  'common.cta.save': 'Save',
  'common.cta.cancel': 'Cancel',
  'common.cta.clear': 'Clear',
  'common.cta.delete': 'Delete',
  'pro.plan.food_search.error': 'Food search unavailable. Try again.',
  'pro.plan.food_search.error.quota': 'Food search is temporarily rate-limited. Try again soon.',
  'pro.plan.food_search.per_100g': '(per 100g)',
  'common.loading.default': 'Loading...',
  'common.empty.no_data': 'Nothing here yet.',
  'common.nutrition.calories': 'Calories',
  'common.nutrition.carbs': 'Carbs',
  'common.nutrition.proteins': 'Proteins',
  'common.nutrition.fats': 'Fats',
  'common.nutrition.fats_initial': 'F',
  'student.hydration.card_title': 'Water Intake',

  'student.hydration.progress': '{consumed} / {goal} ml',
  'student.hydration.cta_log': 'Log water',
  'student.hydration.goal_owner_student': 'Using your personal water goal',
  'student.hydration.goal_owner_nutritionist': 'Daily water goal defined by your nutritionist',
  'student.hydration.streak': 'Current streak: {days} days',
  'shell.common.period': '.',
  'shell.token.path.tabs_index': 'app/(tabs)/index.tsx',
  'shell.token.path.tabs_explore': 'app/(tabs)/explore.tsx',
  'shell.token.path.tabs_layout': 'app/(tabs)/_layout.tsx',
  'shell.token.path.components_hello_wave': 'components/HelloWave.tsx',
  'shell.token.path.components_parallax_scroll_view': 'components/ParallaxScrollView.tsx',
  'shell.token.path.app': 'app',
  'shell.token.path.app_example': 'app-example',
  'shell.token.command.reset_project': 'npm run reset-project',
  'shell.token.shortcut.devtools_ios': 'cmd + d',
  'shell.token.shortcut.devtools_android': 'cmd + m',
  'shell.token.shortcut.devtools_web': 'F12',
  'shell.token.shortcut.open_web': 'w',
  'shell.token.image_suffix.2x': '@2x',
  'shell.token.image_suffix.3x': '@3x',
  'shell.token.hook.use_color_scheme': 'useColorScheme()',
  'shell.token.library.react_native_reanimated': 'react-native-reanimated',
  'student.home.title': 'Home',
  'student.home.hydration.title': 'Hydration',
  'student.home.hydration.progress': '{consumed} / {goal} ml',
  'student.home.hydration.streak': 'Streak: {days} days',
  'student.home.hydration.goal_student': 'Using your personal water goal',
  'student.home.hydration.goal_nutritionist': 'Goal set by Nutritionist',
  'student.home.hydration.no_goal': 'Create a nutrition plan to define your daily water goal',
  'student.home.nutrition.section': 'Nutrition Plan',
  'student.home.training.section': 'Workout of the Day',
  'student.home.pending_connection': 'Pending Connection',
  'student.home.cta_nutrition': 'View Plan',
  'student.home.cta_training': 'Start Training',
  'student.home.cta_professionals': 'Manage professionals',
  'student.home.cta_start_self': 'Start on my own',
  'student.home.no_active_plan': 'No active plan',
  'student.home.nutrition.plan_available': 'Plan available for today',
  'student.home.training.plan_available': 'Full body session available',
  'student.home.offline.mode': 'Offline Mode',
  'student.home.offline.read_only_badge': 'Offline: Read-only',
  'student.home.loading.stale_title': 'Stale Data',
  'student.home.loading.stale_body': 'Last sync > 24h ago. Pull down to refresh.',
  'student.nutrition.title': 'Nutrition',
  'student.nutrition.empty.title': 'Meal plan unavailable',
  'student.nutrition.empty.body':
    'To receive a personalized meal plan and reach your goals, you need support from a qualified professional.',
  'student.nutrition.empty.cta': 'Hire a nutritionist',
  'student.nutrition.empty.self_guided_cta': 'Create my meal plan',

  'student.nutrition.water.title': 'Water intake',
  'student.nutrition.water.personal_goal': 'Personal Goal',
  'student.nutrition.water.nutritionist_goal': 'Goal set by Nutritionist',
  'student.nutrition.water.cta_log': 'Log Intake',
  'student.nutrition.water.goal_defined_in_plan': 'Water goal is defined in your nutrition plan.',
  'student.nutrition.water.log.label': 'Amount (ml)',
  'student.nutrition.water.log.placeholder': 'Amount (ml)',
  'student.nutrition.water.log.validation.required': 'Amount is required.',
  'student.nutrition.water.log.validation.must_be_positive': 'Amount must be greater than zero.',
  'student.nutrition.plan_change.cta': 'Request plan change',
  'student.nutrition.plan_change.title': 'Request a plan change',
  'student.nutrition.plan_change.label': 'What would you like to change?',
  'student.nutrition.plan_change.placeholder': 'Describe what you would like adjusted...',
  'student.nutrition.plan_change.validation.required': 'Request description is required.',
  'student.nutrition.plan_change.validation.too_short': 'Please describe your request in more detail.',
  'student.nutrition.plan_change.error.plan_not_found': 'Plan not found. Pull to refresh.',
  'student.nutrition.plan_change.error.no_active_assignment': 'You do not have an active assigned plan.',
  'student.nutrition.plan_change.error.network': "Couldn't connect. Check your connection and try again.",
  'student.nutrition.plan_change.error.unknown': 'Something went wrong. Try again.',
  'student.nutrition.plan_change.success': 'Change request sent.',
  'student.nutrition.assigned_plan.read_only_notice': 'Your nutrition plan is professionally assigned. Contact your nutritionist to request changes.',
  'student.training.title': 'Workouts',
  'student.training.calendar.cta': 'Open calendar',
  'student.training.session.title': "Today's guided plan",
  'student.training.session.body':
    'Your coach assigned a training structure. Track completion and request adjustments below.',
  'student.training.empty.title': 'No workouts found',
  'student.training.empty.body':
    "You don't have a personalized workout plan yet. Hire a personal trainer to receive a routine tailored to your goals.",
  'student.training.empty.cta': 'Hire a trainer',
  'student.training.empty.self_guided_cta': 'Create my workout plan',
  'student.training.plan_change.cta': 'Request plan change',
  'student.training.plan_change.title': 'Request a plan change',
  'student.training.plan_change.label': 'What would you like to change?',
  'student.training.plan_change.placeholder': 'Describe what you would like adjusted...',
  'student.training.plan_change.validation.required': 'Request description is required.',
  'student.training.plan_change.validation.too_short': 'Please describe your request in more detail.',
  'student.training.plan_change.error.plan_not_found': 'Plan not found. Pull to refresh.',
  'student.training.plan_change.error.no_active_assignment': 'You do not have an active assigned plan.',
  'student.training.plan_change.error.network': "Couldn't connect. Check your connection and try again.",
  'student.training.plan_change.error.unknown': 'Something went wrong. Try again.',
  'student.training.plan_change.success': 'Change request sent.',
  'student.training.assigned_plan.read_only_notice': 'Your training plan is professionally assigned. Contact your coach to request changes.',
  'pro.home.title': 'Dashboard',
  'pro.home.active_students': 'Active students',
  'pro.home.pending_requests': 'Pending requests',
  'pro.home.invite_code.title': 'Your invite code',
  'pro.home.invite_code.careful_sharing': 'Share only with trusted students to keep your roster organized.',
  'pro.home.invite_code.share': 'Share code',
  'pro.home.invite_code.rotate': 'Regenerate code',
  'pro.home.invite_code.rotate_confirm_title': 'Regenerate invite code?',
  'pro.home.invite_code.rotate_confirm_body': 'Your current code will be invalidated and all pending requests from it will be automatically canceled.',
  'pro.home.invite_code.rotate_confirm_yes': 'Regenerate',
  'pro.home.invite_code.rotate_confirm_no': 'Cancel',
  'pro.home.invite_code.rotate_error': 'Could not regenerate code. Try again.',
  'pro.home.invite_code.empty': 'No active invite code.',
  'pro.home.cta_roster': 'View student roster',
  'pro.home.cta_pending': 'Manage pending requests',
  'pro.home.subscription.warning': 'Your subscription is expiring soon. Renew to keep managing all your students.',
  'pro.home.subscription.cta_renew': 'Renew subscription',
  'pro.home.entitlement_lock': 'Student-plan actions are locked. Restore your subscription to unlock.',
  'pro.home.error': 'Could not load dashboard data. Try again.',
  'pro.specialty.title': 'Your specialties',
  'pro.specialty.subtitle': 'Set up the areas you work in as a professional. Students will be matched to you based on these specialties.',
  'pro.specialty.section.active': 'Active specialties',
  'pro.specialty.section.add': 'Add a specialty',
  'pro.specialty.credential.intro': 'Adding your professional registry number is optional and helps build trust with students. It is not verified or displayed publicly.',
  'pro.specialty.nutritionist': 'Nutritionist',
  'pro.specialty.fitness_coach': 'Fitness Coach',
  'pro.specialty.add_nutritionist': 'Add Nutritionist',
  'pro.specialty.add_fitness_coach': 'Add Fitness Coach',
  'pro.specialty.remove': 'Remove',
  'pro.specialty.remove_blocked.active': 'Cannot remove: active students in this specialty.',
  'pro.specialty.remove_blocked.pending': 'Cannot remove: pending students in this specialty.',
  'pro.specialty.remove_blocked.last': 'Cannot remove: at least one specialty is required.',
  'pro.specialty.remove_error': 'Could not remove specialty. Try again.',
  'pro.specialty.add_error': 'Could not add specialty. Try again.',
  'pro.specialty.credential.title': 'Registry credential (optional)',
  'pro.specialty.credential.registry_id.label': 'Registry ID',
  'pro.specialty.credential.registry_id.placeholder': 'e.g. CRN-12345',
  'pro.specialty.credential.authority.label': 'Authority',
  'pro.specialty.credential.authority.placeholder': 'e.g. CFN',
  'pro.specialty.credential.country.label': 'Country',
  'pro.specialty.credential.country.placeholder': 'e.g. Brazil',
  'pro.specialty.credential.save': 'Save credential',
  'pro.specialty.credential.skip': 'Skip',
  'pro.specialty.credential.skip_add': 'Add without credential',
  'pro.specialty.credential.save_error': 'Could not save credential. Try again.',
  'pro.specialty.empty': 'No specialties added yet.',
  'pro.specialty.removal_assist.view_active': 'View active students',
  'pro.specialty.removal_assist.view_active_desc': 'See and manage active student assignments',
  'pro.specialty.removal_assist.view_pending': 'View pending requests',
  'pro.specialty.removal_assist.view_pending_desc': 'Review pending connection requests',
  'pro.specialty.removal_assist.bulk_deny': 'Deny pending requests',
  'pro.specialty.removal_assist.bulk_deny_desc': 'Bulk deny pending requests to clear blockers',
  'pro.specialty.removal_assist.add_specialty': 'Add another specialty',
  'pro.specialty.removal_assist.add_specialty_desc': 'Add Nutritionist or Fitness Coach to enable removal',
  'pro.specialty.removal_blocked.title': 'Cannot remove specialty',
  'pro.specialty.removal_blocked.active_students_body': 'This specialty has {count} active student{plural}. Unbind or complete active assignments first.',
  'pro.specialty.removal_blocked.pending_students_body': 'This specialty has {count} pending student{plural}. Accept or deny pending requests first.',
  'pro.specialty.removal_blocked.last_specialty_body': 'You must have at least one specialty. Add a new specialty before removing this one.',
  'pro.specialty.remove_blocked.dismiss': 'Dismiss',
  'pro.specialty.cta_continue': 'Continue to dashboard',
  'pro.specialty.cta_skip': 'Skip for now',
  'pro.specialty.cta_skip_hint': 'You can set up your specialties later from your account settings.',
  'pro.students.title': 'My students',
  'pro.students.search.placeholder': 'Search students',
  'pro.students.filter.active': 'Active',
  'pro.students.filter.pending': 'Pending',
  'pro.students.filter.all': 'All',
  'pro.students.empty': 'No students yet.',
  'pro.students.empty.title': 'No students yet',
  'pro.students.empty.body': 'Start transforming lives by sharing your invite link.',
  'pro.students.empty.cta_add_first': 'Add first student',
  'pro.students.empty.cta_share_link': 'Share invite link',
  'pro.students.error': 'Could not load student roster. Try again.',
  'pro.students.bulk_assign.cta': 'Bulk assign plan',
  'pro.students.bulk_assign.cta_confirm': 'Assign to {count} students',
  'pro.students.bulk_assign.selection_mode': 'Bulk Assignment',
  'pro.students.bulk_assign.cancel': 'Cancel',
  'pro.students.bulk_assign.select_hint': 'Select students to assign a plan.',
  'pro.students.specialty.nutritionist': 'Nutritionist',
  'pro.students.specialty.fitness_coach': 'Fitness Coach',
  'pro.student_profile.title': 'Student profile',
  'pro.student_profile.specialty.nutritionist': 'Nutrition',
  'pro.student_profile.specialty.fitness_coach': 'Training',
  'pro.student_profile.assignment.active': 'Active',
  'pro.student_profile.assignment.pending': 'Pending confirmation',
  'pro.student_profile.assignment.none': 'No active assignment',
  'pro.student_profile.unbind.cta': 'End assignment',
  'pro.student_profile.unbind.confirm_title': 'End this assignment?',
  'pro.student_profile.unbind.confirm_body': 'The student will be unlinked. History is retained.',
  'pro.student_profile.unbind.confirm_yes': 'End assignment',
  'pro.student_profile.unbind.confirm_no': 'Keep assignment',
  'pro.student_profile.unbind.error': 'Could not end assignment. Try again.',
  'pro.student_profile.plan_change_requests.title': 'Plan change requests',
  'pro.student_profile.plan_change_requests.empty': 'No pending change requests.',
  'pro.student_profile.plan_change_requests.review': 'Mark reviewed',
  'pro.student_profile.plan_change_requests.dismiss': 'Dismiss',
  'pro.student_profile.plan_change_requests.load_error': 'Could not load change requests. Try again.',
  'pro.student_profile.plan_change_requests.action_error': 'Could not update request. Try again.',
  'pro.student_profile.water_goal.title': 'Student water goal',
  'pro.student_profile.water_goal.label': 'Daily goal (ml)',
  'pro.student_profile.water_goal.placeholder': 'e.g. 2500',
  'pro.student_profile.water_goal.save': 'Set goal',
  'pro.student_profile.water_goal.validation.required': 'Goal amount is required.',
  'pro.student_profile.water_goal.validation.must_be_positive': 'Goal must be greater than zero.',
  'pro.student_profile.water_goal.error': 'Could not set water goal. Try again.',
  'pro.student_profile.entitlement_lock': 'Plan actions are locked. Restore your subscription to unlock.',
  'pro.student_profile.error': 'Could not load student profile. Try again.',
  'pro.subscription.title': 'Subscription',
  'pro.subscription.status.active': 'Active',
  'pro.subscription.status.inactive': 'Inactive',
  'pro.subscription.status.unknown': 'Checking...',
  'pro.subscription.cap_usage': '{count} / {limit} active students',
  'pro.subscription.free_tier': 'free up to 10 students.',
  'pro.subscription.warning': 'Your subscription is expiring soon. Renew to avoid service interruption.',
  'pro.subscription.pre_lapse.title': 'Subscription expiring soon',
  'pro.subscription.pre_lapse.body': 'Your subscription is about to expire. Renew now to keep your plan active and avoid interruptions.',
  'pro.subscription.pre_lapse.cta_renew': 'Renew subscription',
  'pro.subscription.locked': 'Student-plan actions are locked. Restore or purchase a subscription to continue.',
  'pro.subscription.cta_purchase': 'Upgrade plan',
  'pro.subscription.cta_restore': 'Restore purchase',
  'pro.subscription.cta_refresh': 'Refresh status',
  'pro.subscription.purchase_note': 'Subscription is managed through your device app store.',
  'pro.subscription.error': 'Could not load subscription status. Try again.',
  'offline.banner': "You're offline. Showing cached data. Updates are locked until you reconnect.",
  'offline.write_lock': 'Connect to the internet to save changes.',
  'offline.stale_minutes': 'Last updated {value} min ago',
  'offline.stale_hours': 'Last updated {value}h ago',
  'offline.stale_days': 'Last updated {value}d ago',
  'settings.account.title': 'Account & Privacy',
  'settings.account.header_title': 'Account & Profile',
  'settings.account.section.account': 'Account',
  'settings.account.section.legal': 'Legal & Privacy',
  'settings.account.section.support': 'Support',
  'settings.account.section.danger': 'Danger Zone',
  'settings.account.role.student': 'Student',
  'settings.account.role.professional': 'Professional',
  'settings.account.email.label': 'Email',
  'settings.account.change_password.label': 'Change password',
  'settings.account.change_password.confirm_title': 'Reset password?',
  'settings.account.change_password.confirm_body': "We'll send a password reset link to {email}. Check your inbox after confirming.",
  'settings.account.change_password.confirm_yes': 'Send reset link',
  'settings.account.change_password.confirm_no': 'Cancel',
  'settings.account.change_password.success': 'Password reset email sent. Check your inbox.',
  'settings.account.change_password.error': 'Could not send reset email. Try again.',
  'settings.account.change_password.oauth_notice': 'Your password is managed by {provider}.',
  'settings.account.language.label': 'Language',
  'settings.account.language.en_us': 'English',
  'settings.account.language.pt_br': 'Português',
  'settings.account.language.es_es': 'Español',
  'settings.account.language.picker_title': 'Choose language',
  'settings.account.privacy_policy.label': 'Privacy Policy',
  'settings.account.privacy_policy.cta': 'View Privacy Policy',
  'settings.account.terms.label': 'Terms of Service',
  'settings.account.contact.label': 'Contact support',
  'settings.account.app_version.label': 'Version',
  'settings.account.sign_out.cta': 'Sign out',
  'settings.account.sign_out.confirm_title': 'Sign out?',
  'settings.account.sign_out.confirm_body': 'You will be returned to the sign-in screen.',
  'settings.account.sign_out.confirm_yes': 'Sign out',
  'settings.account.sign_out.confirm_no': 'Cancel',
  'settings.account.delete.title': 'Delete account',
  'settings.account.delete.body': 'Deleting your account removes your personal data. Some anonymized records may be retained as required by policy.',
  'settings.account.delete.cta': 'Request account deletion',
  'settings.account.delete.confirm_title': 'Delete your account?',
  'settings.account.delete.confirm_body': 'This action is irreversible. Your personal information will be removed. Anonymized history may be retained for legal, billing, and continuity requirements.',
  'settings.account.delete.confirm_yes': 'Delete account',
  'settings.account.delete.confirm_no': 'Cancel',
  'settings.account.delete.success': 'Your account deletion request has been submitted.',
  'settings.account.delete.error.network': "Couldn't connect. Check your connection and try again.",
  'settings.account.delete.error.unknown': 'Something went wrong. Try again.',
  'settings.account.delete.error.already_requested': 'A deletion request is already in progress.',
  'settings.account.delete.error.requires_recent_login':
    'For your security, please sign out and sign in again before deleting your account.',
  'settings.account.delete.error.unauthenticated': 'Your session expired. Please sign in again.',
  'meal.builder.title.create': 'Create custom meal',
  'meal.builder.title.edit': 'Edit meal',
  'meal.builder.helper': 'Add total meal weight and nutrients. We use this to calculate any portion you log.',
  'meal.builder.field.name.label': 'Meal name',
  'meal.builder.field.name.placeholder': 'e.g. Grilled chicken bowl',
  'meal.builder.field.grams.label': 'Total weight (g)',
  'meal.builder.field.grams.placeholder': 'e.g. 350',
  'meal.builder.field.calories.label': 'Calories (kcal)',
  'meal.builder.field.calories.placeholder': 'e.g. 520',
  'meal.builder.field.carbs.label': 'Carbs (g)',
  'meal.builder.field.carbs.placeholder': 'e.g. 45',
  'meal.builder.field.proteins.label': 'Proteins (g)',
  'meal.builder.field.proteins.placeholder': 'e.g. 38',
  'meal.builder.field.fats.label': 'Fats (g)',
  'meal.builder.field.fats.placeholder': 'e.g. 12',
  'meal.builder.field.cost.label': 'Ingredient cost (optional)',
  'meal.builder.field.cost.placeholder': 'e.g. 4.50',
  'meal.builder.cta_save': 'Save meal',
  'meal.builder.cta_share': 'Share recipe',
  'meal.builder.image.cta_upload': 'Upload photo',
  'meal.builder.image.cta_change': 'Change photo',
  'meal.builder.image.uploading': 'Uploading... {percent}%',
  'meal.builder.image.upload_failed': 'Photo upload failed. Tap to retry.',
   'meal.builder.image.cta_retry': 'Retry upload',
   // BL-007: custom meal image upload (SC-214)
   'custom_meal.image.upload_progress': 'Uploading image... {progress}%',
   'custom_meal.image.upload_failed': "We couldn't upload the image. Check your connection and try again.",
   'custom_meal.image.retry': 'Retry upload',
   'custom_meal.image.file_too_large': 'The image is too large. Please choose a smaller file.',
   'custom_meal.image.unauthorized': 'Upload failed. Please sign out and sign in again.',
   'meal.builder.validation.name_required': 'Meal name is required.',
  'meal.builder.validation.grams_required': 'Total weight is required.',
  'meal.builder.validation.grams_positive': 'Total weight must be greater than zero.',
  'meal.builder.validation.calories_required': 'Calories are required.',
  'meal.builder.validation.calories_non_negative': 'Calories must be zero or more.',
  'meal.builder.validation.carbs_required': 'Carbs are required.',
  'meal.builder.validation.carbs_non_negative': 'Carbs must be zero or more.',
  'meal.builder.validation.proteins_required': 'Proteins are required.',
  'meal.builder.validation.proteins_non_negative': 'Proteins must be zero or more.',
  'meal.builder.validation.fats_required': 'Fats are required.',
  'meal.builder.validation.fats_non_negative': 'Fats must be zero or more.',
  'meal.builder.validation.cost_non_negative': 'Ingredient cost must be zero or more.',
  'meal.builder.error.save': 'Could not save meal. Try again.',
  'meal.builder.error.load': 'Could not load meal. Try again.',
  'meal.builder.share.error.needs_save': 'Save the meal first to share it.',
  'meal.builder.share.error.unknown': 'Could not generate share link. Try again.',
  'meal.library.title': 'My custom meals',
  'meal.library.empty.title': 'No custom meals yet',
  'meal.library.empty.body': 'Create your first custom meal to log portions in seconds.',
  'meal.library.cta_create': 'Create meal',
  'meal.library.error': 'Could not load custom meals. Try again.',
  'meal.library.quick_log.title': 'Log meal',
  'meal.library.quick_log.helper': 'Enter grams consumed. We calculate calories and macros automatically.',
  'meal.library.quick_log.field.label': 'Grams consumed',
  'meal.library.quick_log.field.placeholder': 'e.g. 200',
  'meal.library.quick_log.preview.calories': '{calories} kcal',
  'meal.library.quick_log.preview.macros': '{carbs}g carbs · {proteins}g protein · {fats}g fat',
  'meal.library.quick_log.cta_log': 'Log meal',
  'meal.library.quick_log.cta_cancel': 'Cancel',
  'meal.library.quick_log.validation.required': 'Amount is required.',
  'meal.library.quick_log.validation.positive': 'Amount must be greater than zero.',
  'meal.library.quick_log.error': 'Could not save log entry. Try again.',
  'meal.library.quick_log.success': 'Meal logged.',
  'meal.library.cta_share': 'Share recipe',
  'meal.library.cta_edit': 'Edit',
  'shared_recipe.title': 'Save shared recipe',
  'shared_recipe.helper': 'Save this recipe to your account to use it in your daily tracking.',
  'shared_recipe.ownership_note': 'After saving, this copy is yours even if the original creator deletes theirs.',
  'shared_recipe.cta_save': 'Save to my account',
  'shared_recipe.cta_cancel': 'Cancel',
  'shared_recipe.existing_copy': 'You already saved this recipe in your account.',
  'shared_recipe.auth_required': "Sign in to save this recipe. We'll bring you back here right after login.",
  'shared_recipe.nutrition.calories': '{calories} kcal',
  'shared_recipe.nutrition.macros': '{carbs}g carbs · {proteins}g protein · {fats}g fat',
  'shared_recipe.nutrition.weight': '{grams}g total',
  'shared_recipe.error.invalid_token': 'This recipe link is invalid or has expired.',
  'shared_recipe.error.network': "Couldn't connect. Check your connection and try again.",
  'shared_recipe.error.unknown': 'Something went wrong. Try again.',
  'shared_recipe.error.save': 'Could not save recipe. Try again.',
  'shared_recipe.success': 'Recipe saved to your account.',
  'a11y.loading.default': 'Loading…',
  'a11y.loading.submitting': 'Submitting…',
  'a11y.loading.saving': 'Saving…',
  'a11y.loading.invite_code': 'Loading invite code…',
  'a11y.selected_count': '{count} selected',
  'a11y.student_row': '{name}, {specialty}, {status}',
  'a11y.stat_card': '{value} {label}',
  'a11y.brand_logo': 'My Champions logo',
  'meal.photo_analysis.cta': 'Analyze with AI',
  'meal.photo_analysis.analyzing': 'Analyzing your meal…',
  'meal.photo_analysis.disclaimer': 'These are AI estimates. Please verify before saving.',
  'meal.photo_analysis.error.unrecognizable': "Couldn't identify a meal in this photo. Try again or fill in manually.",
  'meal.photo_analysis.error.quota': 'AI analysis is temporarily unavailable. Please fill in manually.',
  'meal.photo_analysis.error.network': 'Network error during analysis. Check your connection and try again.',
  'meal.photo_analysis.error.generic': 'Analysis failed. You can still fill in the fields manually.',
  'meal.photo_analysis.attach_photo.label': 'Also attach this photo to the meal',
  'meal.photo_analysis.confidence.low': 'Low confidence — double-check these estimates',
  'meal.photo_analysis.paywall.locked': 'AI analysis is a premium feature',
  'meal.photo_analysis.paywall.cta_upgrade': 'Upgrade to unlock',
  'meal.photo_analysis.paywall.loading': 'Checking subscription\u2026',
  'pro.library.nutrition.title': 'Nutrition Plans',
  'pro.library.nutrition.empty': 'No nutrition plans yet. Create your first plan.',
  'pro.library.nutrition.cta_create': 'Create nutrition plan',
  'pro.library.training.title': 'Training Plans',
  'pro.library.training.empty': 'No training plans yet. Create your first plan.',
  'pro.library.training.cta_create': 'Create training plan',
  'pro.library.cta_open': 'Open',
  'pro.library.error': 'Could not load plans. Try again.',
  'pro.library.nutrition.helper':
    'Create your diet presets. After assigning to a student, you only need to fine-tune it.',
  'pro.library.training.helper':
    'Create your workout presets. After assigning to a student, you only need to fine-tune it.',
  'pro.plan.nutrition.title.create': 'Create nutrition plan',
  'pro.plan.nutrition.title.edit': 'Edit nutrition plan',
  'pro.plan.training.title.create': 'Create training plan',
  'pro.plan.training.title.edit': 'Edit training plan',
  'pro.plan.field.name.label': 'Plan name',
  'pro.plan.field.name.placeholder': 'e.g. Caloric Deficit A',
  'pro.plan.field.hydration_goal.label': 'Daily water goal (ml)',
  'pro.plan.field.hydration_goal.placeholder': 'e.g. 2200',
  'pro.plan.field.calories_target.label': 'Calorie target (kcal)',
  'pro.plan.field.calories_target.placeholder': 'e.g. 2000',
  'pro.plan.field.carbs_target.label': 'Carbs target (g)',
  'pro.plan.field.proteins_target.label': 'Proteins target (g)',
  'pro.plan.field.fats_target.label': 'Fats target (g)',
  'pro.plan.section.meals': 'Meals',
  'pro.plan.section.meal_items': 'Meal Items',
  'pro.plan.section.sessions': 'Sessions',
  'pro.plan.cta.add_meal': 'Add meal',
  'pro.plan.cta.add_session': 'Add session',
  'student.plan.cta.add_session': 'Add session',
  'pro.plan.delete.title': 'Delete plan?',
  'pro.plan.delete.body': 'This action cannot be undone. All meals and items in this plan will be permanently removed.',
  'pro.plan.error.delete': 'Could not delete plan. Try again.',
  'pro.plan.meal.name.placeholder': 'e.g. Breakfast',
  'pro.plan.cta.add_item': 'Add item',
  'pro.plan.cta.save': 'Save plan',
  'student.plan.cta.save': 'Save my plan',
  'pro.plan.cta.sort': 'Sort',
  'pro.plan.cta.sort_done': 'Done',
  'pro.plan.cta.move_up': 'Move up',
  'pro.plan.cta.move_down': 'Move down',
  'pro.plan.cta.assign': 'Assign to student',
  'pro.plan.cta.bulk_assign': 'Bulk assign',
  'pro.plan.food_search.placeholder': 'Search foods…',
  'pro.plan.food_search.empty': 'No foods found. Try a different search term.',
  'pro.plan.food_search.stub_notice': 'Add food items to start this plan.',
  'pro.plan.validation.name_required': 'Plan name is required.',
  'pro.plan.validation.name_too_short': 'Plan name must be at least 2 characters.',
  'pro.plan.validation.hydration_goal_required': 'Daily water goal is required.',
  'pro.plan.validation.hydration_goal_positive': 'Daily water goal must be greater than zero.',
  'pro.plan.validation.calories_non_negative': 'Calorie target must be zero or more.',
  'pro.plan.validation.macros_non_negative': 'Macro targets must be zero or more.',
  'pro.plan.error.save': 'Could not save plan. Try again.',
  'pro.plan.error.load': 'Could not load plan. Try again.',
  'pro.plan.error.assign': 'Could not assign plan. Try again.',
  'pro.plan.picker.title': 'Select a plan',
  'pro.plan.picker.empty': 'No predefined plans found. Create one first in your library.',
  'pro.plan.picker.cta_assign': 'Assign',
  'pro.student_profile.assignment.cta_assign': 'Assign plan',
  'pro.plan.assign.success': 'Plan assigned successfully.',
  'pro.plan.assign.error': 'Could not assign plan. Try again.',
  'pro.plan.assign.title': 'Assign plan',
  'pro.plan.assign.student_count': '{count} student(s) selected',
  'pro.plan.assign.confirm': 'Confirm assignment',
  'pro.plan.assign.fine_tune_notice': 'Each student receives an independent copy you can fine-tune before confirming.',
  'pro.plan.builder.guidance.training.title': 'How to Build a Plan',
  'pro.plan.builder.guidance.training.body': 'A Training Plan is a collection of workout sessions. Add sessions like "Upper Body" or "Warm-up", then add exercises to each session.',
  'pro.plan.builder.guidance.nutrition.title': 'Nutrition Planning',
  'pro.plan.builder.guidance.nutrition.body': 'Define calorie and macro targets, then list the meals and portions. A clear plan helps your students stay consistent.',
  'student.plan.builder.guidance.training.title': 'Plan Builder Tips',
  'student.plan.builder.guidance.training.body': 'Create your routine by adding sessions and exercises. You can assign this plan to yourself once saved.',
  'student.plan.builder.guidance.nutrition.title': 'Meal Plan Tips',
  'student.plan.builder.guidance.nutrition.body': 'Set your daily targets and list your meals. Use these targets to stay on track with your nutritional goals.',
  'pro.plan.field.name.support': 'Give your plan a clear name that identifies the training goal.',
  'student.plan.field.name.placeholder': 'e.g. My Training Plan',
  'student.plan.field.name.support': 'Name your plan to keep track of your progress.',
  'pro.plan.session.field.name.label': 'Session name',
  'student.plan.session.field.name.placeholder': 'e.g. Leg Day',
  'pro.plan.field.nutrition_name.support': 'Title',
  'student.plan.field.nutrition_name.support': 'Title',
  'student.plan.field.hydration_goal.label': 'Daily water goal (ml)',
  'student.plan.field.hydration_goal.placeholder': 'e.g. 2200',
  'pro.plan.section.sessions.support': 'Add groups of exercises to organize your workout routine.',
  'student.plan.section.sessions.support': 'Organize your workout into separate sessions.',
  'pro.plan.section.meals.support': 'First create meals, then define the foods in each one.',
  'student.plan.section.meals.support': 'Organize your daily meals and portions.',
  'pro.plan.training.empty.title': 'Start building',
  'pro.plan.training.empty.body': 'Tap "Add Session" below to create your first workout block.',
  'student.plan.training.empty.title': 'No sessions yet',
  'student.plan.training.empty.body': 'Tap the button below to start your routine.',
  'pro.plan.nutrition.empty.title': 'No meals added',
  'pro.plan.nutrition.empty.body': 'Tap "Add Meal" below to list your first food item.',
  'student.plan.nutrition.empty.title': 'Empty meal list',
  'student.plan.nutrition.empty.body': 'Start by adding your first meal.',
  'pro.plan.session.no_exercises': 'No exercises added yet.',
  'student.plan.session.no_exercises': 'Add your first exercise here.',
  'pro.plan.nutrition.no_items': 'No exercises added to this session.',
  'student.plan.nutrition.no_items': 'Add exercises to this session.',
  'student.plan.validation.hydration_goal_required': 'Daily water goal is required.',
  'student.plan.validation.hydration_goal_positive': 'Daily water goal must be greater than zero.',
  'pro.plan.training.item.no_sets': 'Sets/Reps not set',
  'student.plan.training.item.no_sets': 'Tap to edit sets',
  'pro.plan.nutrition.item.no_sets': 'No sets/reps yet',
  'student.plan.nutrition.item.no_sets': 'Tap to edit sets',
  'pro.plan.discard.title': 'Discard changes?',
  'pro.plan.discard.body': 'You have unsaved changes. Are you sure you want to leave?',
  'pro.plan.discard.yes': 'Discard',
  'pro.plan.discard.no': 'Keep editing',
  'pro.plan.draft.title': 'Unsaved version found',
  'pro.plan.draft.body': 'Would you like to continue from where you left off?',
  'pro.plan.draft.yes': 'Yes, continue',
  'pro.plan.draft.no': 'No, start over',
  'pro.plan.session.field.name.placeholder': 'e.g. Day A — Upper Body',
  'pro.plan.session.field.notes.label': 'Session notes (optional)',
  'pro.plan.item.field.name.label': 'Exercise / item name',
  'pro.plan.item.field.name.placeholder': 'e.g. Bench Press',
  'pro.plan.item.field.quantity.label': 'Quantity (optional)',
  'pro.plan.item.field.quantity.placeholder': 'e.g. 3 sets × 10 reps',
  'pro.plan.item.field.notes.label': 'Notes (optional)',
  'pro.plan.item.field.notes.placeholder': 'e.g. Focus on form',
  'pro.plan.item.field.nutrition_name.label': 'Meal / food name',
  'pro.plan.item.field.nutrition_name.placeholder': 'e.g. Grilled chicken',
  'pro.plan.item.field.nutrition_quantity.label': 'Amount(g)',
  'pro.plan.item.field.nutrition_quantity.placeholder': 'e.g. 150g',
  'pro.plan.item.field.nutrition_notes.label': 'Notes (optional)',
  'pro.plan.item.field.nutrition_notes.placeholder': 'e.g. No salt',
  'pro.plan.item.search.placeholder': 'Search for an exercise...',
  'pro.plan.item.search.empty': 'No exercises found.',
  'pro.plan.item.search.error': 'Error searching for exercises.',
  'pro.plan.item.search.back': 'Back to search',
  'pro.plan.item.detail.description': 'Description',
  'pro.plan.item.detail.instructions': 'Instructions',
  'pro.plan.item.detail.important_points': 'Important Points',
  // Exercise service muscle group slugs (localized subtitle in search results)
  'exercise.muscle_group.chest': 'Chest',
  'exercise.muscle_group.back': 'Back',
  'exercise.muscle_group.shoulders': 'Shoulders',
  'exercise.muscle_group.biceps': 'Biceps',
  'exercise.muscle_group.triceps': 'Triceps',
  'exercise.muscle_group.forearms': 'Forearms',
  'exercise.muscle_group.quads': 'Quads',
  'exercise.muscle_group.hamstrings': 'Hamstrings',
  'exercise.muscle_group.glutes': 'Glutes',
  'exercise.muscle_group.calves': 'Calves',
  'exercise.muscle_group.core': 'Core',
  'exercise.muscle_group.full_body': 'Full Body',
  'pro.plan.predefined.label': 'Predefined plan',
  'student.plan.error.save': 'Could not save your plan. Try again.',
  'student.plan.error.load': 'Could not load your plan. Try again.',
  'student.plan.nutrition.title.create': 'Create my nutrition plan',
  'student.plan.nutrition.title.edit': 'Edit my nutrition plan',
  'student.plan.training.title.create': 'Create my workout plan',
  'student.plan.training.title.edit': 'Edit my workout plan',
  'student.plan.section.meals': 'Meals in my plan',
  'student.plan.section.sessions': 'Workout sessions',
  'student.plan.food_search.stub_notice': 'Add meal items to start your self-guided plan.',
  'student.plan.section.meal_items': 'Meal Items',
  'student.plan.cta.add_meal': 'Add meal',
  'student.plan.delete.title': 'Delete my plan?',
  'student.plan.delete.body': 'This action cannot be undone. All meals and items in your plan will be permanently removed.',
  'student.plan.error.delete': 'Could not delete your plan. Try again.',
  'student.plan.field.name.label': 'My plan name',
  'student.plan.training.empty_sessions': 'No sessions yet. Add one to begin your plan.',
  'shell.tabs.home': 'Home',
  'shell.tabs.dashboard': 'Dashboard',
  'shell.tabs.students': 'Students',
  'shell.tabs.nutrition': 'Nutrition',
  'shell.tabs.training': 'Training',
  'shell.tabs.exercise': 'Exercise',
  'shell.tabs.recipes': 'Recipes',
  'shell.tabs.account': 'Account',
  'shell.tabs.profile': 'Profile',
  'shell.tabs.explore': 'Explore',
  'shell.placeholder.coming_soon': 'Coming soon. Check back after the next update.',
  'shell.modal.title': 'Modal',
  'shell.modal.body_title': 'This is a modal',
  'shell.modal.link_home': 'Go to home screen',
  'shell.home.title': 'Welcome!',
  'shell.home.step1.title': 'Step 1: Try it',
  'shell.home.step1.part1': 'Edit',
  'shell.home.step1.part2': 'to see changes. Press',
  'shell.home.step1.part3': 'to open developer tools.',
  'shell.home.step2.title': 'Step 2: Explore',
  'shell.home.step2.description':
    "Tap the Explore tab to learn more about what's included in this starter app.",
  'shell.home.step3.title': 'Step 3: Get a fresh start',
  'shell.home.step3.part1': 'When you\'re ready, run',
  'shell.home.step3.part2': 'to get a fresh',
  'shell.home.step3.part3': 'directory. This will move the current',
  'shell.home.step3.part4': 'to',
  'shell.home.menu.action': 'Action',
  'shell.home.menu.share': 'Share',
  'shell.home.menu.more': 'More',
  'shell.home.menu.delete': 'Delete',
  'shell.home.alert.action': 'Action pressed',
  'shell.home.alert.share': 'Share pressed',
  'shell.home.alert.delete': 'Delete pressed',
  'shell.explore.title': 'Explore',
  'shell.explore.description': 'This app includes example code to help you get started.',
  'shell.explore.section.routing.title': 'File-based routing',
  'shell.explore.section.routing.line1.part1': 'This app has two screens:',
  'shell.explore.section.routing.line1.part2': 'and',
  'shell.explore.section.routing.line1.part3': '.',
  'shell.explore.section.routing.line2.part1': 'The layout file in',
  'shell.explore.section.routing.line2.part2': 'sets up the tab navigator.',
  'shell.explore.section.routing.learn_more': 'Learn more',
  'shell.explore.section.platform.title': 'Android, iOS, and web support',
  'shell.explore.section.platform.body.part1':
    'You can open this project on Android, iOS, and the web. To open the web version, press',
  'shell.explore.section.platform.body.part2': 'in the terminal running this project.',
  'shell.explore.section.images.title': 'Images',
  'shell.explore.section.images.body.part1': 'For static images, you can use the',
  'shell.explore.section.images.body.part2': 'and',
  'shell.explore.section.images.body.part3':
    'suffixes to provide files for different screen densities',
  'shell.explore.section.images.learn_more': 'Learn more',
  'shell.explore.section.theme.title': 'Light and dark mode components',
  'shell.explore.section.theme.body.part1': 'This template has light and dark mode support. The',
  'shell.explore.section.theme.body.part2':
    "lets you inspect what the user's current color scheme is, and so you can adjust UI colors accordingly.",
  'shell.explore.section.theme.learn_more': 'Learn more',
  'shell.explore.section.animations.title': 'Animations',
  'shell.explore.section.animations.body.part1': 'This template includes an example of an animated component. The',
  'shell.explore.section.animations.body.part2': 'component uses the powerful',
  'shell.explore.section.animations.body.part3': 'library to create a waving hand animation.',
  'shell.explore.section.animations.ios_extra.part1': 'The',
  'shell.explore.section.animations.ios_extra.part2':
    'component provides a parallax effect for the header image.',

  // Support
  'settings.account.support.dialog.title': 'Talk to support',
  'settings.account.support.dialog.disclaimer': 'This screen is for messaging our support team.',
  'settings.account.support.field.subject.label': 'Subject',
  'settings.account.support.field.subject.placeholder': 'e.g. Login issue',
  'settings.account.support.field.body.label': 'Message',
  'settings.account.support.field.body.placeholder': 'How can we help?',
  'settings.account.support.cta_submit': 'Send message',
  'settings.account.support.success': 'Message sent successfully!',
  'settings.account.support.error': 'Error sending message. Try again.',
  'settings.account.support.validation.subject_required': 'Subject is required.',
  'settings.account.support.validation.body_required': 'Message is required.',
} as const;

export type TranslationKey = keyof typeof enUS;
