import type { TranslationKey } from './en-US';

export const esES: Record<TranslationKey, string> = {
  'common.error.generic': 'Algo salió mal. Inténtalo de nuevo.',
  'auth.field.email': 'Correo electrónico',
  'auth.field.name': 'Nombre',
  'auth.field.password': 'Contraseña',
  'auth.field.password_confirmation': 'Confirmar contraseña',
  'auth.placeholder.email': 'Correo electrónico',
  'auth.placeholder.name': 'Nombre completo',
  'auth.placeholder.password': 'Contraseña',
  'auth.placeholder.password_confirmation': 'Confirmar contraseña',
  'auth.validation.name_required': 'El nombre es obligatorio.',
  'auth.validation.email_required': 'El correo es obligatorio.',
  'auth.validation.password_required': 'La contraseña es obligatoria.',
  'auth.validation.password_confirmation_required':
    'La confirmación de contraseña es obligatoria.',
  'auth.validation.password_policy':
    'Usa al menos 8 caracteres con mayúscula, número y símbolo ASCII (ej.: ! @ #). No se permiten emojis.',
  'auth.validation.password_confirmation_mismatch':
    'La confirmación debe coincidir con tu contraseña.',
  'auth.signin.title': 'Bienvenido, Campeón',
  'auth.signin.subtitle': '¿Listo para superar tus metas hoy?',
  'auth.signin.field.email': 'Correo electrónico',
  'auth.signin.placeholder.email': 'champion@example.com',
  'auth.signin.placeholder.password': '••••••••',
  'auth.signin.cta_primary': 'Iniciar sesión',
  'auth.signin.new_here': '¿Nuevo por aquí?',
  'auth.signin.cta_create': 'Crear una cuenta',
  'auth.signin.or_continue': 'O continuar con',
  'auth.signin.error.invalid_credentials':
    'El correo o la contraseña son incorrectos. Inténtalo de nuevo o restablece tu contraseña.',
  'auth.signin.error.network':
    'No se pudo conectar ahora. Comprueba tu conexión e inténtalo de nuevo.',
  'auth.signin.error.provider_conflict':
    'Este correo ya está vinculado a otro método de acceso. Inicia sesión primero con ese método.',
  'auth.signin.error.configuration':
    'La autenticación aún no está configurada. Define las claves de Firebase e inténtalo de nuevo.',
  'auth.terms.title': 'Términos y Privacidad',
  'auth.terms.description':
    'Antes de continuar, revisa y acepta los términos más recientes de My Champions.',
  'auth.terms.open_link': 'Abrir términos y política de privacidad',
  'auth.terms.checkbox': 'He leído y acepto los términos y la política de privacidad.',
  'auth.terms.accept_button': 'Aceptar y continuar',
  'auth.terms.offline_hint': 'Necesitas internet para abrir el enlace legal.',
  'auth.terms.version': 'Versión obligatoria: {version}',
  'auth.terms.error.link_unavailable':
    'No se pudo abrir el enlace de términos ahora. Inténtalo de nuevo.',
  'auth.social.google': 'Google',
  'auth.social.apple': 'Apple',
  'auth.password.toggle_show': 'Mostrar contraseña',
  'auth.password.toggle_hide': 'Ocultar contraseña',
  'auth.password.toggle_show_short': 'Mostrar',
  'auth.password.toggle_hide_short': 'Ocultar',
  'auth.signup.title': 'Crea tu cuenta',
  'auth.signup.cta_primary': 'Crear cuenta',
  'auth.signup.or_continue': 'o continuar con',
  'auth.signup.password_helper':
    'Usa al menos 8 caracteres, incluyendo mayúscula, número y símbolo (ej.: ! @ #).',
  'auth.signup.error.duplicate_email':
    'Este correo ya está en uso. Inicia sesión para continuar.',
  'auth.signup.error.network':
    'No se pudo conectar ahora. Comprueba tu conexión e inténtalo de nuevo.',
  'auth.signup.error.provider_conflict':
    'Este correo ya está vinculado a otro método de acceso. Inicia sesión primero con ese método.',
  'auth.signup.error.configuration':
    'La autenticación aún no está configurada. Define las claves de Firebase e inténtalo de nuevo.',
  'auth.signup.placeholder.body':
    'La implementación del formulario de creación de cuenta comienza en el siguiente bloque.',
  'auth.signup.already_have': '¿Ya tienes una cuenta?',
  'auth.signup.cta_back_signin': 'Volver a iniciar sesión',
  'auth.role.title': '¿Cómo quieres usar la app?',
  'auth.role.intro': 'Puedes empezar por tu cuenta ahora y conectarte con un profesional después.',
  'auth.role.option_self.title': 'Quiero seguir mi propio progreso',
  'auth.role.option_self.subtitle': 'Cuenta de alumno',
  'auth.role.option_pro.title': 'Soy nutricionista o entrenador físico',
  'auth.role.option_pro.subtitle': 'Cuenta profesional',
  'auth.role.lock_note': 'El tipo de cuenta no se puede cambiar después. Elige cuidadosamente según tus necesidades.',
  'auth.role.cta_continue': 'Continuar',
  'auth.role.cta_back': 'Volver',
  'auth.role.validation.required': 'Elige cómo quieres usar la app para continuar.',
  'auth.role.error.save_failed': 'No se pudo guardar tu perfil ahora. Inténtalo de nuevo.',
  'auth.role.error.navigation_failed': 'No se pudo continuar ahora. Inténtalo de nuevo.',
  'auth.role.error.auth_required': 'Tu sesión expiró. Inicia sesión de nuevo.',
  'auth.role.placeholder.title': 'Selección de rol',
  'auth.role.placeholder.body':
    'El flujo de inicio de sesión ya está conectado. La implementación de selección de rol es el siguiente bloque.',
  'auth.role.placeholder.cta_open_app_shell': 'Abrir app',
  'student.home.no_pro.title': 'Aún no hay profesional conectado',
  'student.home.no_pro.body': 'Aún puedes empezar a hacer seguimiento hoy por tu cuenta.',
  'student.home.cta_start_nutrition': 'Iniciar mi plan de nutrición',
  'student.home.cta_start_training': 'Iniciar mi plan de entrenamiento',
  'student.home.cta_manage_professionals': 'Gestionar profesionales',
  'student.home.offline.stale_badge': 'Los datos pueden estar desactualizados',
  'student.home.offline.last_sync': 'Última actualización: {datetime}',
  'student.home.offline.banner_read_only':
    'Estás sin conexión. Puedes ver los datos en caché, pero las actualizaciones están bloqueadas hasta que vuelva la conexión.',
  'student.home.offline.write_lock': 'Conéctate a internet para guardar los cambios.',
  'relationship.title': 'Conectar con profesionales',
  'relationship.intro': '¿Tienes un profesional? Introduce su código de invitación.',
  'relationship.helper_self_guided': '¿Aún no tienes uno? Puedes seguir usando la app por tu cuenta.',
  'relationship.input.invite_code': 'Introduce el código de invitación',
  'relationship.cta_scan_qr': 'Escanear código QR',
  'relationship.qr.permission_denied':
    'Se necesita acceso a la cámara para escanear un código QR. Concede el permiso en los ajustes del dispositivo o introduce el código manualmente.',
  'relationship.qr.invalid_payload':
    'Este código QR no contiene un código de invitación válido. Intenta escanearlo de nuevo o introdúcelo manualmente.',
  'relationship.qr.close': 'Cerrar escáner',
  'relationship.cta_submit_code': 'Conectar',
  'relationship.error.invalid_code':
    'Este código de invitación no es válido. Pide un nuevo código a tu profesional.',
  'relationship.error.already_connected':
    'Ya estás conectado a un profesional en esta especialidad.',
  'relationship.error.pending_cap':
    'Este profesional tiene demasiadas solicitudes pendientes ahora. Inténtalo más tarde.',
  'relationship.error.network': 'No se pudo conectar ahora. Comprueba tu conexión e inténtalo de nuevo.',
  'relationship.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'relationship.pending.helper': 'Esperando confirmación del profesional para activar esta conexión.',
  'relationship.pending.canceled_code_rotated':
    'Esta solicitud fue cancelada porque el profesional regeneró su código de invitación. Pide el nuevo código para volver a conectarte.',
  'relationship.empty.cta_continue_self': 'Continuar por mi cuenta',
  'relationship.unbind.cta': 'Terminar conexión',
  'relationship.unbind.confirm_title': '¿Terminar esta conexión profesional?',
  'relationship.unbind.confirm_body':
    'Puedes volver a conectarte más tarde con un código de invitación. Tu historial se conservará.',
  'relationship.unbind.confirm_yes': 'Terminar conexión',
  'relationship.unbind.confirm_no': 'Mantener conexión',
  'relationship.unbind.error': 'No se pudo terminar la conexión. Inténtalo de nuevo.',
  'relationship.credential.registry_id': 'ID de registro',
  'relationship.credential.authority': 'Organismo',
  'relationship.credential.country': 'País',
  'pro.pending.search.placeholder': 'Buscar solicitudes pendientes',
  'pro.pending.filter.label': 'Filtrar solicitudes',
  'pro.pending.bulk_deny.cta': 'Rechazar seleccionadas',
  'pro.pending.bulk_deny.confirm_title': '¿Rechazar solicitudes seleccionadas?',
  'pro.pending.bulk_deny.confirm_body':
    'Los alumnos seleccionados pueden volver a solicitar más tarde con tu código de invitación.',
  'pro.pending.bulk_deny.success': 'Solicitudes rechazadas correctamente.',
  'pro.pending.confirm.cta': 'Aceptar',
  'pro.pending.deny.cta': 'Rechazar',
  'pro.pending.empty': 'No hay solicitudes de conexión pendientes.',
  'pro.pending.error': 'No se pudieron cargar las solicitudes pendientes. Inténtalo de nuevo.',
  'common.error.retry': 'Reintentar',
  'common.loading.default': 'Cargando...',
  'common.empty.no_data': 'Todavía no hay nada aquí.',
  'student.hydration.card_title': 'Consumo de agua',
  'student.hydration.progress': '{consumed} / {goal} ml',
  'student.hydration.cta_log': 'Registrar agua',
  'student.hydration.cta_set_goal': 'Definir objetivo de agua',
  'student.hydration.goal_owner_student': 'Usando tu objetivo personal de agua',
  'student.hydration.goal_owner_nutritionist':
    'Objetivo diario de agua definido por tu nutricionista',
  'student.hydration.streak': 'Racha actual: {days} días',
  'shell.common.period': '.',
  'shell.token.path.tabs_index': 'app/(tabs)/index.tsx',
  'shell.token.path.tabs_explore': 'app/(tabs)/explore.tsx',
  'shell.token.path.tabs_layout': 'app/(tabs)/_layout.tsx',
  'shell.token.path.components_hello_wave': 'components/HelloWave.tsx',
  'shell.token.path.components_parallax_scroll_view': 'components/ParallaxScrollView.tsx',
  'shell.token.path.app': 'app',
  'shell.token.path.app_example': 'app-example',
  'shell.token.command.reset_project': 'npm run reset-project',
  'shell.token.shortcut.devtools_ios': 'cmd + d',
  'shell.token.shortcut.devtools_android': 'cmd + m',
  'shell.token.shortcut.devtools_web': 'F12',
  'shell.token.shortcut.open_web': 'w',
  'shell.token.image_suffix.2x': '@2x',
  'shell.token.image_suffix.3x': '@3x',
  'shell.token.hook.use_color_scheme': 'useColorScheme()',
  'shell.token.library.react_native_reanimated': 'react-native-reanimated',
  'student.home.title': 'Inicio',
  'student.home.hydration.title': 'Hidratación',
  'student.home.hydration.progress': '{consumed} / {goal} ml',
  'student.home.hydration.streak': 'Racha: {days} días',
  'student.home.hydration.goal_student': 'Usando tu objetivo personal de agua',
  'student.home.hydration.goal_nutritionist': 'Meta definida por el nutricionista',
  'student.home.hydration.no_goal': 'Establece un objetivo diario de agua para seguir tu progreso',
  'student.home.nutrition.section': 'Plan de Nutrición',
  'student.home.training.section': 'Entrenamiento del Día',
  'student.home.pending_connection': 'Conexión Pendiente',
  'student.home.cta_nutrition': 'Ver Plan',
  'student.home.cta_training': 'Iniciar Entrenamiento',
  'student.home.cta_professionals': 'Gestionar profesionales',
  'student.home.cta_start_self': 'Empezar por mi cuenta',
  'student.home.no_active_plan': 'Sin plan activo',
  'student.home.nutrition.plan_available': 'Plan disponible para hoy',
  'student.home.training.plan_available': 'Sesión de cuerpo completo disponible',
  'student.home.offline.mode': 'Modo Sin Conexión',
  'student.home.offline.read_only_badge': 'Sin conexión: Solo lectura',
  'student.home.loading.stale_title': 'Datos Desactualizados',
  'student.home.loading.stale_body': 'Última sincronización > 24h. Desliza hacia abajo para actualizar.',
  'student.nutrition.title': 'Nutrición',
  'student.nutrition.empty.title': 'Plan alimentario no disponible',
  'student.nutrition.empty.body':
    'Para recibir un plan alimentario personalizado y alcanzar tus objetivos, necesitas el acompañamiento de un profesional cualificado.',
  'student.nutrition.empty.cta': 'Contratar nutricionista',
  'student.nutrition.empty.self_guided_cta': 'Crear mi plan de alimentación',
  'student.nutrition.water.title': 'Ingesta de agua',
  'student.nutrition.water.personal_goal': 'Objetivo Personal',
  'student.nutrition.water.nutritionist_goal': 'Objetivo definido por tu Nutricionista',
  'student.nutrition.water.cta_log': 'Registrar Consumo',
  'student.nutrition.water.cta_set_goal': 'Definir Objetivo Diario',
  'student.nutrition.water.log.label': 'Cantidad (ml)',
  'student.nutrition.water.log.placeholder': 'Cantidad (ml)',
  'student.nutrition.water.log.validation.required': 'La cantidad es obligatoria.',
  'student.nutrition.water.log.validation.must_be_positive': 'La cantidad debe ser mayor que cero.',
  'student.nutrition.water.goal.label': 'Objetivo (ml)',
  'student.nutrition.water.goal.placeholder': 'Objetivo (ml)',
  'student.nutrition.water.goal.validation.required': 'El objetivo es obligatorio.',
  'student.nutrition.water.goal.validation.must_be_positive': 'El objetivo debe ser mayor que cero.',
  'student.nutrition.plan_change.cta': 'Solicitar cambio de plan',
  'student.nutrition.plan_change.title': 'Solicitar cambio de plan',
  'student.nutrition.plan_change.label': '¿Qué te gustaría cambiar?',
  'student.nutrition.plan_change.placeholder': 'Describe lo que te gustaría ajustar...',
  'student.nutrition.plan_change.validation.required': 'La descripción es obligatoria.',
  'student.nutrition.plan_change.validation.too_short': 'Por favor, describe tu solicitud con más detalle.',
  'student.nutrition.plan_change.error.plan_not_found': 'Plan no encontrado. Actualiza la pantalla.',
  'student.nutrition.plan_change.error.no_active_assignment': 'No tienes un plan asignado activo.',
  'student.nutrition.plan_change.error.network': 'Sin conexión. Comprueba tu red e inténtalo de nuevo.',
  'student.nutrition.plan_change.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'student.nutrition.plan_change.success': 'Solicitud de cambio enviada.',
  'student.nutrition.assigned_plan.read_only_notice': 'Tu plan de nutrición fue asignado por un profesional. Contacta a tu nutricionista para solicitar cambios.',
  'student.training.title': 'Entrenamientos',
  'student.training.calendar.cta': 'Abrir calendario',
  'student.training.session.title': 'Plan guiado de hoy',
  'student.training.session.body':
    'Tu entrenador asignó una estructura de entrenamiento. Registra tu ejecución y solicita ajustes abajo.',
  'student.training.empty.title': 'No se encontraron entrenamientos',
  'student.training.empty.body':
    'Aún no tienes un plan de entrenamiento personalizado. Contrata a un entrenador personal para recibir una rutina adaptada a tus objetivos.',
  'student.training.empty.cta': 'Contratar entrenador',
  'student.training.empty.self_guided_cta': 'Crear mi plan de entrenamiento',
  'student.training.plan_change.cta': 'Solicitar cambio de plan',
  'student.training.plan_change.title': 'Solicitar cambio de plan',
  'student.training.plan_change.label': '¿Qué te gustaría cambiar?',
  'student.training.plan_change.placeholder': 'Describe lo que te gustaría ajustar...',
  'student.training.plan_change.validation.required': 'La descripción es obligatoria.',
  'student.training.plan_change.validation.too_short': 'Por favor, describe tu solicitud con más detalle.',
  'student.training.plan_change.error.plan_not_found': 'Plan no encontrado. Actualiza la pantalla.',
  'student.training.plan_change.error.no_active_assignment': 'No tienes un plan asignado activo.',
  'student.training.plan_change.error.network': 'Sin conexión. Comprueba tu red e inténtalo de nuevo.',
  'student.training.plan_change.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'student.training.plan_change.success': 'Solicitud de cambio enviada.',
  'student.training.assigned_plan.read_only_notice': 'Tu plan de entrenamiento fue asignado por un profesional. Contacta a tu entrenador para solicitar cambios.',
  'pro.home.title': 'Panel',
  'pro.home.active_students': 'Alumnos activos',
  'pro.home.pending_requests': 'Solicitudes pendientes',
  'pro.home.invite_code.title': 'Tu código de invitación',
  'pro.home.invite_code.share': 'Compartir código',
  'pro.home.invite_code.rotate': 'Regenerar código',
  'pro.home.invite_code.rotate_confirm_title': '¿Regenerar código de invitación?',
  'pro.home.invite_code.rotate_confirm_body': 'Tu código actual quedará invalidado y todas las solicitudes pendientes vinculadas a él se cancelarán automáticamente.',
  'pro.home.invite_code.rotate_confirm_yes': 'Regenerar',
  'pro.home.invite_code.rotate_confirm_no': 'Cancelar',
  'pro.home.invite_code.rotate_error': 'No se pudo regenerar el código. Inténtalo de nuevo.',
  'pro.home.invite_code.empty': 'No hay código de invitación activo.',
  'pro.home.cta_roster': 'Ver lista de alumnos',
  'pro.home.cta_pending': 'Gestionar solicitudes pendientes',
  'pro.home.subscription.warning': 'Tu suscripción está a punto de expirar. Renuévala para seguir gestionando a todos tus alumnos.',
  'pro.home.subscription.cta_renew': 'Renovar suscripción',
  'pro.home.entitlement_lock': 'Las acciones de plan de alumno están bloqueadas. Restaura tu suscripción para desbloquear.',
  'pro.home.error': 'No se pudieron cargar los datos del panel. Inténtalo de nuevo.',
  'pro.specialty.title': 'Tus especialidades',
  'pro.specialty.nutritionist': 'Nutricionista',
  'pro.specialty.fitness_coach': 'Entrenador físico',
  'pro.specialty.add_nutritionist': 'Añadir Nutricionista',
  'pro.specialty.add_fitness_coach': 'Añadir Entrenador físico',
  'pro.specialty.remove': 'Eliminar',
  'pro.specialty.remove_blocked.active': 'No se puede eliminar: hay alumnos activos en esta especialidad.',
  'pro.specialty.remove_blocked.pending': 'No se puede eliminar: hay alumnos pendientes en esta especialidad.',
  'pro.specialty.remove_blocked.last': 'No se puede eliminar: se requiere al menos una especialidad.',
  'pro.specialty.remove_error': 'No se pudo eliminar la especialidad. Inténtalo de nuevo.',
  'pro.specialty.add_error': 'No se pudo añadir la especialidad. Inténtalo de nuevo.',
  'pro.specialty.credential.title': 'Credencial de registro (opcional)',
  'pro.specialty.credential.registry_id.label': 'Número de registro',
  'pro.specialty.credential.registry_id.placeholder': 'ej.: CRN-12345',
  'pro.specialty.credential.authority.label': 'Organismo',
  'pro.specialty.credential.authority.placeholder': 'ej.: CFN',
  'pro.specialty.credential.country.label': 'País',
  'pro.specialty.credential.country.placeholder': 'ej.: España',
  'pro.specialty.credential.save': 'Guardar credencial',
  'pro.specialty.credential.skip': 'Omitir',
  'pro.specialty.credential.save_error': 'No se pudo guardar la credencial. Inténtalo de nuevo.',
  'pro.specialty.empty': 'Aún no hay especialidades añadidas.',
  'pro.specialty.removal_assist.view_active': 'Ver alumnos activos',
  'pro.specialty.removal_assist.view_active_desc': 'Vea y gestione las asignaciones de alumnos activos',
  'pro.specialty.removal_assist.view_pending': 'Ver solicitudes pendientes',
  'pro.specialty.removal_assist.view_pending_desc': 'Revise las solicitudes de conexión pendientes',
  'pro.specialty.removal_assist.bulk_deny': 'Rechazar solicitudes pendientes',
  'pro.specialty.removal_assist.bulk_deny_desc': 'Rechace en masa las solicitudes pendientes para limpiar bloqueos',
  'pro.specialty.removal_assist.add_specialty': 'Añadir otra especialidad',
  'pro.specialty.removal_assist.add_specialty_desc': 'Añada Nutricionista o Entrenador Personal para permitir la eliminación',
  'pro.specialty.removal_blocked.title': 'No se puede eliminar la especialidad',
  'pro.specialty.removal_blocked.active_students_body': 'Esta especialidad tiene {count} alumno{plural} activo. Desvincule o complete las asignaciones activas primero.',
  'pro.specialty.removal_blocked.pending_students_body': 'Esta especialidad tiene {count} alumno{plural} pendiente. Acepte o rechace las solicitudes pendientes primero.',
  'pro.specialty.removal_blocked.last_specialty_body': 'Debe tener al menos una especialidad. Añada una nueva especialidad antes de eliminar esta.',
  'pro.specialty.remove_blocked.dismiss': 'Descartar',
  'pro.students.title': 'Mis alumnos',
  'pro.students.search.placeholder': 'Buscar alumnos',
  'pro.students.filter.active': 'Activos',
  'pro.students.filter.pending': 'Pendientes',
  'pro.students.filter.all': 'Todos',
  'pro.students.empty': 'Aún no hay alumnos.',
  'pro.students.error': 'No se pudo cargar la lista de alumnos. Inténtalo de nuevo.',
  'pro.students.bulk_assign.cta': 'Asignar plan en masa',
  'pro.students.bulk_assign.select_hint': 'Selecciona alumnos para asignar un plan.',
  'pro.students.specialty.nutritionist': 'Nutricionista',
  'pro.students.specialty.fitness_coach': 'Entrenador físico',
  'pro.student_profile.title': 'Perfil del alumno',
  'pro.student_profile.specialty.nutritionist': 'Nutrición',
  'pro.student_profile.specialty.fitness_coach': 'Entrenamiento',
  'pro.student_profile.assignment.active': 'Activo',
  'pro.student_profile.assignment.pending': 'Esperando confirmación',
  'pro.student_profile.assignment.none': 'Sin asignación activa',
  'pro.student_profile.unbind.cta': 'Terminar asignación',
  'pro.student_profile.unbind.confirm_title': '¿Terminar esta asignación?',
  'pro.student_profile.unbind.confirm_body': 'El alumno quedará desvinculado. El historial se conservará.',
  'pro.student_profile.unbind.confirm_yes': 'Terminar asignación',
  'pro.student_profile.unbind.confirm_no': 'Mantener asignación',
  'pro.student_profile.unbind.error': 'No se pudo terminar la asignación. Inténtalo de nuevo.',
  'pro.student_profile.plan_change_requests.load_error': 'No se pudieron cargar las solicitudes. Inténtalo de nuevo.',
  'pro.student_profile.plan_change_requests.action_error': 'No se pudo actualizar la solicitud. Inténtalo de nuevo.',
  'pro.student_profile.plan_change_requests.title': 'Solicitudes de cambio de plan',
  'pro.student_profile.plan_change_requests.empty': 'No hay solicitudes de cambio pendientes.',
  'pro.student_profile.plan_change_requests.review': 'Marcar como revisado',
  'pro.student_profile.plan_change_requests.dismiss': 'Descartar',
  'pro.student_profile.water_goal.title': 'Objetivo de agua del alumno',
  'pro.student_profile.water_goal.label': 'Objetivo diario (ml)',
  'pro.student_profile.water_goal.placeholder': 'ej.: 2500',
  'pro.student_profile.water_goal.save': 'Establecer objetivo',
  'pro.student_profile.water_goal.validation.required': 'La cantidad del objetivo es obligatoria.',
  'pro.student_profile.water_goal.validation.must_be_positive': 'El objetivo debe ser mayor que cero.',
  'pro.student_profile.water_goal.error': 'No se pudo establecer el objetivo de agua. Inténtalo de nuevo.',
  'pro.student_profile.entitlement_lock': 'Las acciones de plan están bloqueadas. Restaura tu suscripción para desbloquear.',
  'pro.student_profile.error': 'No se pudo cargar el perfil del alumno. Inténtalo de nuevo.',
  'pro.subscription.title': 'Suscripción',
  'pro.subscription.status.active': 'Activa',
  'pro.subscription.status.inactive': 'Inactiva',
  'pro.subscription.status.unknown': 'Verificando...',
  'pro.subscription.cap_usage': '{count} / {limit} alumnos activos',
  'pro.subscription.free_tier': 'Gratis para hasta 10 alumnos activos.',
  'pro.subscription.warning': 'Tu suscripción está a punto de expirar. Renuévala para evitar interrupciones del servicio.',
  'pro.subscription.pre_lapse.title': 'Suscripción por vencer',
  'pro.subscription.pre_lapse.body': 'Tu suscripción está a punto de caducar. Renuévala ahora para mantener tu plan activo y evitar interrupciones.',
  'pro.subscription.pre_lapse.cta_renew': 'Renovar suscripción',
  'pro.subscription.locked': 'Las acciones de plan de alumno están bloqueadas. Restaura o adquiere una suscripción para continuar.',
  'pro.subscription.cta_purchase': 'Mejorar plan',
  'pro.subscription.cta_restore': 'Restaurar compra',
  'pro.subscription.cta_refresh': 'Actualizar estado',
  'pro.subscription.purchase_note': 'La suscripción se gestiona a través de la tienda de apps de tu dispositivo.',
  'pro.subscription.error': 'No se pudo cargar el estado de la suscripción. Inténtalo de nuevo.',
  'offline.banner': 'Estás sin conexión. Mostrando datos en caché. Las actualizaciones están bloqueadas hasta reconectar.',
  'offline.write_lock': 'Conéctate a internet para guardar cambios.',
  'offline.stale_minutes': 'Última actualización hace {value} min',
  'offline.stale_hours': 'Última actualización hace {value}h',
  'offline.stale_days': 'Última actualización hace {value}d',
  'shell.tabs.home': 'Inicio',
  'shell.tabs.dashboard': 'Panel',
  'shell.tabs.students': 'Alumnos',
  'shell.tabs.nutrition': 'Nutrición',
  'shell.tabs.training': 'Entrenamiento',
  'shell.tabs.exercise': 'Ejercicio',
  'shell.tabs.recipes': 'Recetas',
  'shell.tabs.account': 'Cuenta',
  'shell.tabs.profile': 'Perfil',
  'shell.tabs.explore': 'Explorar',
  'shell.placeholder.coming_soon': 'Próximamente. Vuelve después de la próxima actualización.',
  'shell.modal.title': 'Modal',
  'shell.modal.body_title': 'Este es un modal',
  'shell.modal.link_home': 'Ir a la pantalla de inicio',
  'shell.home.title': '¡Bienvenido!',
  'shell.home.step1.title': 'Paso 1: Pruébalo',
  'shell.home.step1.part1': 'Edita',
  'shell.home.step1.part2': 'para ver los cambios. Pulsa',
  'shell.home.step1.part3': 'para abrir las herramientas de desarrollo.',
  'shell.home.step2.title': 'Paso 2: Explora',
  'shell.home.step2.description':
    'Toca la pestaña Explorar para conocer lo que incluye esta app base.',
  'shell.home.step3.title': 'Paso 3: Empieza desde cero',
  'shell.home.step3.part1': 'Cuando estés listo, ejecuta',
  'shell.home.step3.part2': 'para obtener un directorio',
  'shell.home.step3.part3': 'Esto moverá el directorio actual',
  'shell.home.step3.part4': 'a',
  'shell.home.menu.action': 'Acción',
  'shell.home.menu.share': 'Compartir',
  'shell.home.menu.more': 'Más',
  'shell.home.menu.delete': 'Eliminar',
  'shell.home.alert.action': 'Acción pulsada',
  'shell.home.alert.share': 'Compartir pulsado',
  'shell.home.alert.delete': 'Eliminar pulsado',
  'shell.explore.title': 'Explorar',
  'shell.explore.description':
    'Esta app incluye código de ejemplo para ayudarte a empezar.',
  'shell.explore.section.routing.title': 'Enrutado basado en archivos',
  'shell.explore.section.routing.line1.part1': 'Esta app tiene dos pantallas:',
  'shell.explore.section.routing.line1.part2': 'y',
  'shell.explore.section.routing.line1.part3': '.',
  'shell.explore.section.routing.line2.part1': 'El archivo de layout en',
  'shell.explore.section.routing.line2.part2': 'configura el navegador de pestañas.',
  'shell.explore.section.routing.learn_more': 'Más información',
  'shell.explore.section.platform.title': 'Soporte para Android, iOS y web',
  'shell.explore.section.platform.body.part1':
    'Puedes abrir este proyecto en Android, iOS y web. Para abrir la versión web, pulsa',
  'shell.explore.section.platform.body.part2': 'en el terminal que ejecuta este proyecto.',
  'shell.explore.section.images.title': 'Imágenes',
  'shell.explore.section.images.body.part1':
    'Para imágenes estáticas, puedes usar los sufijos',
  'shell.explore.section.images.body.part2': 'y',
  'shell.explore.section.images.body.part3':
    'para proporcionar archivos para distintas densidades de pantalla',
  'shell.explore.section.images.learn_more': 'Más información',
  'shell.explore.section.theme.title': 'Componentes para modo claro y oscuro',
  'shell.explore.section.theme.body.part1':
    'Esta plantilla tiene soporte para modo claro y oscuro. La función',
  'shell.explore.section.theme.body.part2':
    'te permite inspeccionar el esquema de color actual del usuario y ajustar los colores de la UI.',
  'shell.explore.section.theme.learn_more': 'Más información',
  'shell.explore.section.animations.title': 'Animaciones',
  'shell.explore.section.animations.body.part1':
    'Esta plantilla incluye un ejemplo de componente animado. El componente',
  'shell.explore.section.animations.body.part2': 'usa la potente librería',
  'shell.explore.section.animations.body.part3':
    'para crear una animación de una mano saludando.',
  'shell.explore.section.animations.ios_extra.part1': 'El componente',
  'shell.explore.section.animations.ios_extra.part2':
    'proporciona un efecto parallax para la imagen de cabecera.',
  'settings.account.title': 'Cuenta y Privacidad',
  'settings.account.section.account': 'Cuenta',
  'settings.account.section.legal': 'Legal y Privacidad',
  'settings.account.section.support': 'Soporte',
  'settings.account.section.danger': 'Zona de peligro',
  'settings.account.role.student': 'Estudiante',
  'settings.account.role.professional': 'Profesional',
  'settings.account.email.label': 'Correo electrónico',
  'settings.account.change_password.label': 'Cambiar contraseña',
  'settings.account.change_password.confirm_title': '¿Restablecer contraseña?',
  'settings.account.change_password.confirm_body': 'Te enviaremos un enlace para restablecer tu contraseña a {email}. Revisa tu bandeja de entrada tras confirmar.',
  'settings.account.change_password.confirm_yes': 'Enviar enlace',
  'settings.account.change_password.confirm_no': 'Cancelar',
  'settings.account.change_password.success': 'Correo de restablecimiento enviado. Revisa tu bandeja de entrada.',
  'settings.account.change_password.error': 'No se pudo enviar el correo de restablecimiento. Inténtalo de nuevo.',
  'settings.account.change_password.oauth_notice': 'Tu contraseña está gestionada por {provider}.',
  'settings.account.language.label': 'Idioma',
  'settings.account.language.en_us': 'English',
  'settings.account.language.pt_br': 'Português',
  'settings.account.language.es_es': 'Español',
  'settings.account.language.picker_title': 'Elegir idioma',
  'settings.account.privacy_policy.label': 'Política de Privacidad',
  'settings.account.privacy_policy.cta': 'Ver Política de Privacidad',
  'settings.account.terms.label': 'Términos de servicio',
  'settings.account.contact.label': 'Contactar soporte',
  'settings.account.app_version.label': 'Versión',
  'settings.account.sign_out.cta': 'Cerrar sesión',
  'settings.account.sign_out.confirm_title': '¿Cerrar sesión?',
  'settings.account.sign_out.confirm_body': 'Volverás a la pantalla de inicio de sesión.',
  'settings.account.sign_out.confirm_yes': 'Cerrar sesión',
  'settings.account.sign_out.confirm_no': 'Cancelar',
  'settings.account.delete.title': 'Eliminar cuenta',
  'settings.account.delete.body': 'Eliminar tu cuenta elimina tus datos personales. Algunos registros anonimizados pueden conservarse según lo exija la política.',
  'settings.account.delete.cta': 'Solicitar eliminación de cuenta',
  'settings.account.delete.confirm_title': '¿Eliminar tu cuenta?',
  'settings.account.delete.confirm_body': 'Esta acción es irreversible. Tu información personal será eliminada. El historial anonimizado puede conservarse por requisitos legales, financieros y de continuidad.',
  'settings.account.delete.confirm_yes': 'Eliminar cuenta',
  'settings.account.delete.confirm_no': 'Cancelar',
  'settings.account.delete.success': 'Tu solicitud de eliminación de cuenta ha sido enviada.',
  'settings.account.delete.error.network': 'No se pudo conectar. Comprueba tu conexión e inténtalo de nuevo.',
  'settings.account.delete.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'settings.account.delete.error.already_requested': 'Ya hay una solicitud de eliminación en curso.',
  'meal.builder.title.create': 'Crear comida personalizada',
  'meal.builder.title.edit': 'Editar comida',
  'meal.builder.helper': 'Indica el peso total de la comida y los nutrientes. Lo usamos para calcular cualquier porción que registres.',
  'meal.builder.field.name.label': 'Nombre de la comida',
  'meal.builder.field.name.placeholder': 'ej.: Bowl de pollo a la plancha',
  'meal.builder.field.grams.label': 'Peso total (g)',
  'meal.builder.field.grams.placeholder': 'ej.: 350',
  'meal.builder.field.calories.label': 'Calorías (kcal)',
  'meal.builder.field.calories.placeholder': 'ej.: 520',
  'meal.builder.field.carbs.label': 'Carbohidratos (g)',
  'meal.builder.field.carbs.placeholder': 'ej.: 45',
  'meal.builder.field.proteins.label': 'Proteínas (g)',
  'meal.builder.field.proteins.placeholder': 'ej.: 38',
  'meal.builder.field.fats.label': 'Grasas (g)',
  'meal.builder.field.fats.placeholder': 'ej.: 12',
  'meal.builder.field.cost.label': 'Coste de ingredientes (opcional)',
  'meal.builder.field.cost.placeholder': 'ej.: 4,50',
  'meal.builder.cta_save': 'Guardar comida',
  'meal.builder.cta_share': 'Compartir receta',
  'meal.builder.image.cta_upload': 'Subir foto',
  'meal.builder.image.cta_change': 'Cambiar foto',
  'meal.builder.image.uploading': 'Subiendo... {percent}%',
  'meal.builder.image.upload_failed': 'Error al subir la foto. Toca para reintentar.',
   'meal.builder.image.cta_retry': 'Reintentar subida',
   // BL-007: custom meal image upload (SC-214)
   'custom_meal.image.upload_progress': 'Subiendo imagen... {progress}%',
   'custom_meal.image.upload_failed': 'No se pudo subir la imagen. Comprueba tu conexión e inténtalo de nuevo.',
   'custom_meal.image.retry': 'Reintentar subida',
   'custom_meal.image.file_too_large': 'La imagen es demasiado grande. Por favor, elige un archivo más pequeño.',
   'custom_meal.image.unauthorized': 'Error al subir. Por favor, cierra sesión y vuelve a iniciarla.',
   'meal.builder.validation.name_required': 'El nombre de la comida es obligatorio.',
  'meal.builder.validation.grams_required': 'El peso total es obligatorio.',
  'meal.builder.validation.grams_positive': 'El peso total debe ser mayor que cero.',
  'meal.builder.validation.calories_required': 'Las calorías son obligatorias.',
  'meal.builder.validation.calories_non_negative': 'Las calorías deben ser cero o más.',
  'meal.builder.validation.carbs_required': 'Los carbohidratos son obligatorios.',
  'meal.builder.validation.carbs_non_negative': 'Los carbohidratos deben ser cero o más.',
  'meal.builder.validation.proteins_required': 'Las proteínas son obligatorias.',
  'meal.builder.validation.proteins_non_negative': 'Las proteínas deben ser cero o más.',
  'meal.builder.validation.fats_required': 'Las grasas son obligatorias.',
  'meal.builder.validation.fats_non_negative': 'Las grasas deben ser cero o más.',
  'meal.builder.validation.cost_non_negative': 'El coste de ingredientes debe ser cero o más.',
  'meal.builder.error.save': 'No se pudo guardar la comida. Inténtalo de nuevo.',
  'meal.builder.error.load': 'No se pudo cargar la comida. Inténtalo de nuevo.',
  'meal.builder.share.error.needs_save': 'Guarda la comida primero para compartirla.',
  'meal.builder.share.error.unknown': 'No se pudo generar el enlace para compartir. Inténtalo de nuevo.',
  'meal.library.title': 'Mis comidas personalizadas',
  'meal.library.empty.title': 'Aún no hay comidas personalizadas',
  'meal.library.empty.body': 'Crea tu primera comida personalizada para registrar porciones en segundos.',
  'meal.library.cta_create': 'Crear comida',
  'meal.library.error': 'No se pudieron cargar las comidas personalizadas. Inténtalo de nuevo.',
  'meal.library.quick_log.title': 'Registrar comida',
  'meal.library.quick_log.helper': 'Indica los gramos consumidos. Calculamos las calorías y macros automáticamente.',
  'meal.library.quick_log.field.label': 'Gramos consumidos',
  'meal.library.quick_log.field.placeholder': 'ej.: 200',
  'meal.library.quick_log.preview.calories': '{calories} kcal',
  'meal.library.quick_log.preview.macros': '{carbs}g carbohidratos · {proteins}g proteína · {fats}g grasa',
  'meal.library.quick_log.cta_log': 'Registrar comida',
  'meal.library.quick_log.cta_cancel': 'Cancelar',
  'meal.library.quick_log.validation.required': 'La cantidad es obligatoria.',
  'meal.library.quick_log.validation.positive': 'La cantidad debe ser mayor que cero.',
  'meal.library.quick_log.error': 'No se pudo guardar el registro. Inténtalo de nuevo.',
  'meal.library.quick_log.success': 'Comida registrada.',
  'meal.library.cta_share': 'Compartir receta',
  'meal.library.cta_edit': 'Editar',
  'shared_recipe.title': 'Guardar receta compartida',
  'shared_recipe.helper': 'Guarda esta receta en tu cuenta para usarla en tu seguimiento diario.',
  'shared_recipe.ownership_note': 'Después de guardar, esta copia es tuya aunque el creador original la elimine.',
  'shared_recipe.cta_save': 'Guardar en mi cuenta',
  'shared_recipe.cta_cancel': 'Cancelar',
  'shared_recipe.existing_copy': 'Ya guardaste esta receta en tu cuenta.',
  'shared_recipe.auth_required': 'Inicia sesión para guardar esta receta. Te redirigiremos aquí justo después.',
  'shared_recipe.nutrition.calories': '{calories} kcal',
  'shared_recipe.nutrition.macros': '{carbs}g carbohidratos · {proteins}g proteína · {fats}g grasa',
  'shared_recipe.nutrition.weight': '{grams}g total',
  'shared_recipe.error.invalid_token': 'Este enlace de receta no es válido o ha expirado.',
  'shared_recipe.error.network': 'No se pudo conectar. Comprueba tu conexión e inténtalo de nuevo.',
  'shared_recipe.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'shared_recipe.error.save': 'No se pudo guardar la receta. Inténtalo de nuevo.',
  'shared_recipe.success': 'Receta guardada en tu cuenta.',
  'a11y.loading.default': 'Cargando…',
  'a11y.loading.submitting': 'Enviando…',
  'a11y.loading.saving': 'Guardando…',
  'a11y.loading.invite_code': 'Cargando código de invitación…',
  'a11y.selected_count': '{count} seleccionado(s)',
  'a11y.student_row': '{name}, {specialty}, {status}',
  'a11y.stat_card': '{value} {label}',
  'meal.photo_analysis.cta': 'Analizar con IA',
  'meal.photo_analysis.analyzing': 'Analizando tu comida…',
  'meal.photo_analysis.disclaimer': 'Estos son valores estimados por IA. Verifícalos antes de guardar.',
  'meal.photo_analysis.error.unrecognizable': 'No se pudo identificar una comida en esta foto. Inténtalo de nuevo o rellena manualmente.',
  'meal.photo_analysis.error.quota': 'El análisis de IA no está disponible temporalmente. Por favor, rellena manualmente.',
  'meal.photo_analysis.error.network': 'Error de red durante el análisis. Comprueba tu conexión e inténtalo de nuevo.',
  'meal.photo_analysis.error.generic': 'El análisis falló. Aún puedes rellenar los campos manualmente.',
  'meal.photo_analysis.attach_photo.label': 'También adjuntar esta foto a la comida',
  'meal.photo_analysis.confidence.low': 'Baja confianza — revisa estos valores',
  'meal.photo_analysis.paywall.locked': 'El análisis con IA es una función premium',
  'meal.photo_analysis.paywall.cta_upgrade': 'Actualizar para desbloquear',
  'meal.photo_analysis.paywall.loading': 'Verificando suscripción\u2026',
  'pro.library.nutrition.title': 'Planes de Nutrición',
  'pro.library.nutrition.empty': 'Aún no hay planes de nutrición. Crea tu primer plan.',
  'pro.library.nutrition.cta_create': 'Crear plan de nutrición',
  'pro.library.training.title': 'Planes de Entrenamiento',
  'pro.library.training.empty': 'Aún no hay planes de entrenamiento. Crea tu primer plan.',
  'pro.library.training.cta_create': 'Crear plan de entrenamiento',
  'pro.library.cta_open': 'Abrir',
  'pro.library.error': 'No se pudieron cargar los planes. Inténtalo de nuevo.',
  'pro.template.library.title': 'Plantillas de Inicio',
  'pro.template.library.filter.label': 'Buscar plantillas',
  'pro.template.library.empty': 'No hay plantillas de inicio disponibles.',
  'pro.template.clone.cta': 'Clonar plantilla',
  'pro.template.clone.modal.title': 'Clonar plantilla',
  'pro.template.clone.modal.label': 'Nombre del nuevo plan',
  'pro.template.clone.modal.placeholder': 'ej. Mi plan personalizado',
  'pro.template.clone.validation.template_id_required': 'Se requiere ID de plantilla',
  'pro.template.clone.validation.invalid_template': 'Formato de ID de plantilla inválido',
  'pro.template.clone.validation.name_required': 'El nombre del plan es obligatorio',
  'pro.template.clone.validation.name_too_short': 'El nombre del plan debe tener al menos 2 caracteres',
  'pro.template.clone.validation.name_too_long': 'El nombre del plan no debe exceder 100 caracteres',
  'pro.template.clone.success': 'Plantilla clonada exitosamente',
  'pro.template.clone.error': 'Error al clonar plantilla. Inténtalo de nuevo.',
  'pro.template.immutable_notice': 'Las plantillas de inicio son de solo lectura. Clona para personalizar.',
  'pro.plan.nutrition.title.create': 'Crear plan de nutrición',
  'pro.plan.nutrition.title.edit': 'Editar plan de nutrición',
  'pro.plan.training.title.create': 'Crear plan de entrenamiento',
  'pro.plan.training.title.edit': 'Editar plan de entrenamiento',
  'pro.plan.field.name.label': 'Nombre del plan',
  'pro.plan.field.name.placeholder': 'p.ej. Déficit Calórico A',
  'pro.plan.field.calories_target.label': 'Meta de calorías (kcal)',
  'pro.plan.field.calories_target.placeholder': 'p.ej. 2000',
  'pro.plan.field.carbs_target.label': 'Meta de carbohidratos (g)',
  'pro.plan.field.proteins_target.label': 'Meta de proteínas (g)',
  'pro.plan.field.fats_target.label': 'Meta de grasas (g)',
  'pro.plan.section.meals': 'Comidas',
  'pro.plan.section.sessions': 'Sesiones',
  'pro.plan.cta.add_meal': 'Añadir alimento',
  'pro.plan.cta.add_session': 'Añadir sesión',
  'pro.plan.cta.add_item': 'Añadir ítem',
  'pro.plan.cta.save': 'Guardar plan',
  'pro.plan.cta.assign': 'Asignar al alumno',
  'pro.plan.cta.bulk_assign': 'Asignación masiva',
  'pro.plan.cta.clone_template': 'Empezar desde plantilla',
  'pro.plan.template.starter_label': 'Plantillas iniciales',
  'pro.plan.template.picker_title': 'Elige una plantilla inicial',
  'pro.plan.template.cta_use': 'Usar esta plantilla',
  'pro.plan.food_search.placeholder': 'Buscar alimentos…',
  'pro.plan.food_search.empty': 'No se encontraron alimentos. Prueba otro término.',
  'pro.plan.food_search.stub_notice': 'La búsqueda de alimentos estará disponible en una próxima actualización.',
  'pro.plan.validation.name_required': 'El nombre del plan es obligatorio.',
  'pro.plan.validation.name_too_short': 'El nombre del plan debe tener al menos 2 caracteres.',
  'pro.plan.validation.calories_non_negative': 'La meta de calorías debe ser cero o más.',
  'pro.plan.validation.macros_non_negative': 'Las metas de macronutrientes deben ser cero o más.',
  'pro.plan.error.save': 'No se pudo guardar el plan. Inténtalo de nuevo.',
  'pro.plan.error.load': 'No se pudo cargar el plan. Inténtalo de nuevo.',
  'pro.plan.error.assign': 'No se pudo asignar el plan. Inténtalo de nuevo.',
  'pro.plan.assign.title': 'Asignar plan',
  'pro.plan.assign.student_count': '{count} alumno(s) seleccionado(s)',
  'pro.plan.assign.confirm': 'Confirmar asignación',
  'pro.plan.assign.fine_tune_notice': 'Cada alumno recibe una copia independiente que puedes ajustar antes de confirmar.',
  'pro.plan.session.field.name.label': 'Nombre de la sesión',
  'pro.plan.session.field.name.placeholder': 'p.ej. Día A — Tren superior',
  'pro.plan.session.field.notes.label': 'Notas de la sesión (opcional)',
  'pro.plan.item.field.name.label': 'Nombre del ejercicio / ítem',
  'pro.plan.item.field.name.placeholder': 'p.ej. Press de banca',
  'pro.plan.item.field.quantity.label': 'Cantidad (opcional)',
  'pro.plan.item.field.quantity.placeholder': 'p.ej. 3 series × 10 reps',
  'pro.plan.item.field.notes.label': 'Notas (opcional)',
  'pro.plan.predefined.label': 'Plan predefinido',
  'student.plan.error.save': 'No se pudo guardar tu plan. Inténtalo de nuevo.',
  'student.plan.error.load': 'No se pudo cargar tu plan. Inténtalo de nuevo.',
  'student.plan.nutrition.title.create': 'Crear mi plan de alimentación',
  'student.plan.nutrition.title.edit': 'Editar mi plan de alimentación',
  'student.plan.training.title.create': 'Crear mi plan de entrenamiento',
  'student.plan.training.title.edit': 'Editar mi plan de entrenamiento',
  'student.plan.section.meals': 'Comidas de mi plan',
  'student.plan.section.sessions': 'Sesiones de entrenamiento',
  'student.plan.food_search.stub_notice': 'Añade comidas para comenzar tu plan autoguiado.',
  'student.plan.cta.add_meal': 'Añadir comida',
  'student.plan.cta.add_session': 'Añadir sesión de entrenamiento',
  'student.plan.cta.save': 'Guardar mi plan',
  'student.plan.field.name.label': 'Nombre de mi plan',
  'student.plan.training.empty_sessions': 'Aún no hay sesiones. Añade una para empezar tu plan.',
};
