import type { TranslationKey } from './en-US';

export const esES: Record<TranslationKey, string> = {
  'common.error.generic': 'Algo salió mal. Inténtalo de nuevo.',
  'auth.field.email': 'Correo electrónico',
  'auth.field.name': 'Nombre',
  'auth.field.password': 'Contraseña',
  'auth.field.password_confirmation': 'Confirmar contraseña',
  'auth.placeholder.email': 'Correo electrónico',
  'auth.placeholder.name': 'Nombre completo',
  'auth.placeholder.password': 'Contraseña',
  'auth.placeholder.password_confirmation': 'Confirmar contraseña',
  'auth.validation.name_required': 'El nombre es obligatorio.',
  'auth.validation.email_required': 'El correo es obligatorio.',
  'auth.validation.password_required': 'La contraseña es obligatoria.',
  'auth.validation.password_confirmation_required':
    'La confirmación de contraseña es obligatoria.',
  'auth.validation.password_policy':
    'Usa al menos 8 caracteres con mayúscula, número y símbolo ASCII (ej.: ! @ #). No se permiten emojis.',
  'auth.validation.password_confirmation_mismatch':
    'La confirmación debe coincidir con tu contraseña.',
  'auth.signin.title': 'Bienvenido de nuevo',
  'auth.signin.cta_primary': 'Iniciar sesión',
  'auth.signin.cta_create': 'Crear cuenta',
  'auth.signin.or_continue': 'o continuar con',
  'auth.signin.error.invalid_credentials':
    'El correo o la contraseña son incorrectos. Inténtalo de nuevo o restablece tu contraseña.',
  'auth.signin.error.network':
    'No se pudo conectar ahora. Comprueba tu conexión e inténtalo de nuevo.',
  'auth.signin.error.provider_conflict':
    'Este correo ya está vinculado a otro método de acceso. Inicia sesión primero con ese método.',
  'auth.signin.error.configuration':
    'La autenticación aún no está configurada. Define las claves de Firebase e inténtalo de nuevo.',
  'auth.social.google': 'Google',
  'auth.social.apple': 'Apple',
  'auth.password.toggle_show': 'Mostrar contraseña',
  'auth.password.toggle_hide': 'Ocultar contraseña',
  'auth.password.toggle_show_short': 'Mostrar',
  'auth.password.toggle_hide_short': 'Ocultar',
  'auth.signup.title': 'Crea tu cuenta',
  'auth.signup.cta_primary': 'Crear cuenta',
  'auth.signup.or_continue': 'o continuar con',
  'auth.signup.password_helper':
    'Usa al menos 8 caracteres, incluyendo mayúscula, número y símbolo (ej.: ! @ #).',
  'auth.signup.error.duplicate_email':
    'Este correo ya está en uso. Inicia sesión para continuar.',
  'auth.signup.error.network':
    'No se pudo conectar ahora. Comprueba tu conexión e inténtalo de nuevo.',
  'auth.signup.error.provider_conflict':
    'Este correo ya está vinculado a otro método de acceso. Inicia sesión primero con ese método.',
  'auth.signup.error.configuration':
    'La autenticación aún no está configurada. Define las claves de Firebase e inténtalo de nuevo.',
  'auth.signup.placeholder.body':
    'La implementación del formulario de creación de cuenta comienza en el siguiente bloque.',
  'auth.signup.cta_back_signin': 'Volver a iniciar sesión',
  'auth.role.title': '¿Cómo quieres usar la app?',
  'auth.role.intro': 'Puedes empezar por tu cuenta ahora y conectarte con un profesional después.',
  'auth.role.option_self.title': 'Quiero seguir mi propio progreso',
  'auth.role.option_self.subtitle':
    'Registra comidas y entrenamientos por tu cuenta. No necesitas un profesional.',
  'auth.role.option_pro.title': 'Soy nutricionista o entrenador físico',
  'auth.role.option_pro.subtitle':
    'Gestiona clientes, asigna planes y sigue el progreso de tus alumnos.',
  'auth.role.lock_note':
    'El tipo de cuenta no se puede cambiar después. Puedes crear otra cuenta con otro correo si lo necesitas.',
  'auth.role.cta_continue': 'Continuar',
  'auth.role.cta_back': 'Volver',
  'auth.role.cta_start_self_guided': 'Empezar por mi cuenta ahora',
  'auth.role.validation.required': 'Elige cómo quieres usar la app para continuar.',
  'auth.role.error.save_failed': 'No se pudo guardar tu perfil ahora. Inténtalo de nuevo.',
  'auth.role.placeholder.title': 'Selección de rol',
  'auth.role.placeholder.body':
    'El flujo de inicio de sesión ya está conectado. La implementación de selección de rol es el siguiente bloque.',
  'auth.role.placeholder.cta_open_app_shell': 'Abrir app',
  'student.home.no_pro.title': 'Aún no hay profesional conectado',
  'student.home.no_pro.body': 'Aún puedes empezar a hacer seguimiento hoy por tu cuenta.',
  'student.home.cta_start_nutrition': 'Iniciar mi plan de nutrición',
  'student.home.cta_start_training': 'Iniciar mi plan de entrenamiento',
  'student.home.cta_manage_professionals': 'Gestionar profesionales',
  'student.home.offline.stale_badge': 'Los datos pueden estar desactualizados',
  'student.home.offline.last_sync': 'Última actualización: {datetime}',
  'student.home.offline.banner_read_only':
    'Estás sin conexión. Puedes ver los datos en caché, pero las actualizaciones están bloqueadas hasta que vuelva la conexión.',
  'student.home.offline.write_lock': 'Conéctate a internet para guardar los cambios.',
  'relationship.title': 'Conectar con profesionales',
  'relationship.intro': '¿Tienes un profesional? Introduce su código de invitación.',
  'relationship.helper_self_guided': '¿Aún no tienes uno? Puedes seguir usando la app por tu cuenta.',
  'relationship.input.invite_code': 'Introduce el código de invitación',
  'relationship.cta_scan_qr': 'Escanear código QR',
  'relationship.cta_submit_code': 'Conectar',
  'relationship.error.invalid_code':
    'Este código de invitación no es válido. Pide un nuevo código a tu profesional.',
  'relationship.error.already_connected':
    'Ya estás conectado a un profesional en esta especialidad.',
  'relationship.error.pending_cap':
    'Este profesional tiene demasiadas solicitudes pendientes ahora. Inténtalo más tarde.',
  'relationship.error.network': 'No se pudo conectar ahora. Comprueba tu conexión e inténtalo de nuevo.',
  'relationship.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'relationship.pending.helper': 'Esperando confirmación del profesional para activar esta conexión.',
  'relationship.pending.canceled_code_rotated':
    'Esta solicitud fue cancelada porque el profesional regeneró su código de invitación. Pide el nuevo código para volver a conectarte.',
  'relationship.empty.cta_continue_self': 'Continuar por mi cuenta',
  'relationship.unbind.cta': 'Terminar conexión',
  'relationship.unbind.confirm_title': '¿Terminar esta conexión profesional?',
  'relationship.unbind.confirm_body':
    'Puedes volver a conectarte más tarde con un código de invitación. Tu historial se conservará.',
  'relationship.unbind.confirm_yes': 'Terminar conexión',
  'relationship.unbind.confirm_no': 'Mantener conexión',
  'relationship.unbind.error': 'No se pudo terminar la conexión. Inténtalo de nuevo.',
  'relationship.credential.registry_id': 'ID de registro',
  'relationship.credential.authority': 'Organismo',
  'relationship.credential.country': 'País',
  'pro.pending.search.placeholder': 'Buscar solicitudes pendientes',
  'pro.pending.filter.label': 'Filtrar solicitudes',
  'pro.pending.bulk_deny.cta': 'Rechazar seleccionadas',
  'pro.pending.bulk_deny.confirm_title': '¿Rechazar solicitudes seleccionadas?',
  'pro.pending.bulk_deny.confirm_body':
    'Los alumnos seleccionados pueden volver a solicitar más tarde con tu código de invitación.',
  'pro.pending.bulk_deny.success': 'Solicitudes rechazadas correctamente.',
  'pro.pending.confirm.cta': 'Aceptar',
  'pro.pending.deny.cta': 'Rechazar',
  'pro.pending.empty': 'No hay solicitudes de conexión pendientes.',
  'pro.pending.error': 'No se pudieron cargar las solicitudes pendientes. Inténtalo de nuevo.',
  'common.error.retry': 'Reintentar',
  'common.loading.default': 'Cargando...',
  'common.empty.no_data': 'Todavía no hay nada aquí.',
  'student.hydration.card_title': 'Consumo de agua',
  'student.hydration.progress': '{consumed} / {goal} ml',
  'student.hydration.cta_log': 'Registrar agua',
  'student.hydration.cta_set_goal': 'Definir objetivo de agua',
  'student.hydration.goal_owner_student': 'Usando tu objetivo personal de agua',
  'student.hydration.goal_owner_nutritionist':
    'Objetivo diario de agua definido por tu nutricionista',
  'student.hydration.streak': 'Racha actual: {days} días',
  'shell.common.period': '.',
  'shell.token.path.tabs_index': 'app/(tabs)/index.tsx',
  'shell.token.path.tabs_explore': 'app/(tabs)/explore.tsx',
  'shell.token.path.tabs_layout': 'app/(tabs)/_layout.tsx',
  'shell.token.path.components_hello_wave': 'components/HelloWave.tsx',
  'shell.token.path.components_parallax_scroll_view': 'components/ParallaxScrollView.tsx',
  'shell.token.path.app': 'app',
  'shell.token.path.app_example': 'app-example',
  'shell.token.command.reset_project': 'npm run reset-project',
  'shell.token.shortcut.devtools_ios': 'cmd + d',
  'shell.token.shortcut.devtools_android': 'cmd + m',
  'shell.token.shortcut.devtools_web': 'F12',
  'shell.token.shortcut.open_web': 'w',
  'shell.token.image_suffix.2x': '@2x',
  'shell.token.image_suffix.3x': '@3x',
  'shell.token.hook.use_color_scheme': 'useColorScheme()',
  'shell.token.library.react_native_reanimated': 'react-native-reanimated',
  'student.home.title': 'Mi Panel',
  'student.home.hydration.title': 'Ingesta de agua',
  'student.home.hydration.progress': '{consumed} / {goal} ml',
  'student.home.hydration.streak': 'Racha: {days} días',
  'student.home.hydration.goal_student': 'Usando tu objetivo personal de agua',
  'student.home.hydration.goal_nutritionist': 'Objetivo diario definido por tu nutricionista',
  'student.home.hydration.no_goal': 'Establece un objetivo diario de agua para seguir tu progreso',
  'student.home.nutrition.section': 'Nutrición',
  'student.home.training.section': 'Entrenamiento',
  'student.home.pending_connection': 'Esperando confirmación del profesional',
  'student.home.cta_nutrition': 'Ir a nutrición',
  'student.home.cta_training': 'Ir a entrenamiento',
  'student.home.cta_professionals': 'Gestionar profesionales',
  'student.nutrition.title': 'Nutrición de hoy',
  'student.nutrition.empty.title': 'No hay comidas registradas aún',
  'student.nutrition.empty.body': '¿Sin nutricionista? Aún puedes crear y seguir tu propio plan hoy.',
  'student.nutrition.empty.cta': 'Iniciar mi plan de nutrición',
  'student.nutrition.water.title': 'Ingesta de agua',
  'student.nutrition.water.personal_goal': 'Establece tu objetivo diario de agua.',
  'student.nutrition.water.nutritionist_goal': 'Objetivo diario de agua definido por tu nutricionista.',
  'student.nutrition.water.cta_log': 'Registrar agua',
  'student.nutrition.water.cta_set_goal': 'Definir objetivo de agua',
  'student.nutrition.water.log.label': 'Cantidad (ml)',
  'student.nutrition.water.log.placeholder': 'ej.: 250',
  'student.nutrition.water.log.validation.required': 'La cantidad es obligatoria.',
  'student.nutrition.water.log.validation.must_be_positive': 'La cantidad debe ser mayor que cero.',
  'student.nutrition.water.goal.label': 'Objetivo diario (ml)',
  'student.nutrition.water.goal.placeholder': 'ej.: 2000',
  'student.nutrition.water.goal.validation.required': 'El objetivo es obligatorio.',
  'student.nutrition.water.goal.validation.must_be_positive': 'El objetivo debe ser mayor que cero.',
  'student.nutrition.plan_change.cta': 'Solicitar cambio de plan',
  'student.nutrition.plan_change.title': 'Solicitar cambio de plan',
  'student.nutrition.plan_change.label': '¿Qué te gustaría cambiar?',
  'student.nutrition.plan_change.placeholder': 'Describe lo que te gustaría ajustar...',
  'student.nutrition.plan_change.validation.required': 'La descripción es obligatoria.',
  'student.nutrition.plan_change.validation.too_short': 'Por favor, describe tu solicitud con más detalle.',
  'student.nutrition.plan_change.error.plan_not_found': 'Plan no encontrado. Actualiza la pantalla.',
  'student.nutrition.plan_change.error.no_active_assignment': 'No tienes un plan asignado activo.',
  'student.nutrition.plan_change.error.network': 'Sin conexión. Comprueba tu red e inténtalo de nuevo.',
  'student.nutrition.plan_change.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'student.nutrition.plan_change.success': 'Solicitud de cambio enviada.',
  'student.nutrition.assigned_plan.read_only_notice': 'Tu plan de nutrición fue asignado por un profesional. Contacta a tu nutricionista para solicitar cambios.',
  'student.training.title': 'Entrenamiento de hoy',
  'student.training.empty.title': 'Aún no hay entrenamiento programado',
  'student.training.empty.body': '¿Sin entrenador? Aún puedes crear tu propio plan de entrenamiento ahora.',
  'student.training.empty.cta': 'Iniciar mi plan de entrenamiento',
  'student.training.plan_change.cta': 'Solicitar cambio de plan',
  'student.training.plan_change.title': 'Solicitar cambio de plan',
  'student.training.plan_change.label': '¿Qué te gustaría cambiar?',
  'student.training.plan_change.placeholder': 'Describe lo que te gustaría ajustar...',
  'student.training.plan_change.success': 'Solicitud de cambio enviada.',
  'student.training.plan_change.error.unknown': 'Algo salió mal. Inténtalo de nuevo.',
  'student.training.assigned_plan.read_only_notice': 'Tu plan de entrenamiento fue asignado por un profesional. Contacta a tu entrenador para solicitar cambios.',
  'pro.home.title': 'Panel',
  'pro.home.active_students': 'Alumnos activos',
  'pro.home.pending_requests': 'Solicitudes pendientes',
  'pro.home.invite_code.title': 'Tu código de invitación',
  'pro.home.invite_code.share': 'Compartir código',
  'pro.home.invite_code.rotate': 'Regenerar código',
  'pro.home.invite_code.rotate_confirm_title': '¿Regenerar código de invitación?',
  'pro.home.invite_code.rotate_confirm_body': 'Tu código actual quedará invalidado y todas las solicitudes pendientes vinculadas a él se cancelarán automáticamente.',
  'pro.home.invite_code.rotate_confirm_yes': 'Regenerar',
  'pro.home.invite_code.rotate_confirm_no': 'Cancelar',
  'pro.home.invite_code.rotate_error': 'No se pudo regenerar el código. Inténtalo de nuevo.',
  'pro.home.invite_code.empty': 'No hay código de invitación activo.',
  'pro.home.cta_roster': 'Ver lista de alumnos',
  'pro.home.cta_pending': 'Gestionar solicitudes pendientes',
  'pro.home.subscription.warning': 'Tu suscripción está a punto de expirar. Renuévala para seguir gestionando a todos tus alumnos.',
  'pro.home.subscription.cta_renew': 'Renovar suscripción',
  'pro.home.entitlement_lock': 'Las acciones de plan de alumno están bloqueadas. Restaura tu suscripción para desbloquear.',
  'pro.home.error': 'No se pudieron cargar los datos del panel. Inténtalo de nuevo.',
  'pro.specialty.title': 'Tus especialidades',
  'pro.specialty.nutritionist': 'Nutricionista',
  'pro.specialty.fitness_coach': 'Entrenador físico',
  'pro.specialty.add_nutritionist': 'Añadir Nutricionista',
  'pro.specialty.add_fitness_coach': 'Añadir Entrenador físico',
  'pro.specialty.remove': 'Eliminar',
  'pro.specialty.remove_blocked.active': 'No se puede eliminar: hay alumnos activos en esta especialidad.',
  'pro.specialty.remove_blocked.pending': 'No se puede eliminar: hay alumnos pendientes en esta especialidad.',
  'pro.specialty.remove_blocked.last': 'No se puede eliminar: se requiere al menos una especialidad.',
  'pro.specialty.remove_error': 'No se pudo eliminar la especialidad. Inténtalo de nuevo.',
  'pro.specialty.add_error': 'No se pudo añadir la especialidad. Inténtalo de nuevo.',
  'pro.specialty.credential.title': 'Credencial de registro (opcional)',
  'pro.specialty.credential.registry_id.label': 'Número de registro',
  'pro.specialty.credential.registry_id.placeholder': 'ej.: CRN-12345',
  'pro.specialty.credential.authority.label': 'Organismo',
  'pro.specialty.credential.authority.placeholder': 'ej.: CFN',
  'pro.specialty.credential.country.label': 'País',
  'pro.specialty.credential.country.placeholder': 'ej.: España',
  'pro.specialty.credential.save': 'Guardar credencial',
  'pro.specialty.credential.skip': 'Omitir',
  'pro.specialty.credential.save_error': 'No se pudo guardar la credencial. Inténtalo de nuevo.',
  'pro.specialty.empty': 'Aún no hay especialidades añadidas.',
  'pro.students.title': 'Mis alumnos',
  'pro.students.search.placeholder': 'Buscar alumnos',
  'pro.students.filter.active': 'Activos',
  'pro.students.filter.pending': 'Pendientes',
  'pro.students.filter.all': 'Todos',
  'pro.students.empty': 'Aún no hay alumnos.',
  'pro.students.error': 'No se pudo cargar la lista de alumnos. Inténtalo de nuevo.',
  'pro.students.bulk_assign.cta': 'Asignar plan en masa',
  'pro.students.bulk_assign.select_hint': 'Selecciona alumnos para asignar un plan.',
  'pro.students.specialty.nutritionist': 'Nutricionista',
  'pro.students.specialty.fitness_coach': 'Entrenador físico',
  'pro.student_profile.title': 'Perfil del alumno',
  'pro.student_profile.specialty.nutritionist': 'Nutrición',
  'pro.student_profile.specialty.fitness_coach': 'Entrenamiento',
  'pro.student_profile.assignment.active': 'Activo',
  'pro.student_profile.assignment.pending': 'Esperando confirmación',
  'pro.student_profile.assignment.none': 'Sin asignación activa',
  'pro.student_profile.unbind.cta': 'Terminar asignación',
  'pro.student_profile.unbind.confirm_title': '¿Terminar esta asignación?',
  'pro.student_profile.unbind.confirm_body': 'El alumno quedará desvinculado. El historial se conservará.',
  'pro.student_profile.unbind.confirm_yes': 'Terminar asignación',
  'pro.student_profile.unbind.confirm_no': 'Mantener asignación',
  'pro.student_profile.unbind.error': 'No se pudo terminar la asignación. Inténtalo de nuevo.',
  'pro.student_profile.plan_change_requests.title': 'Solicitudes de cambio de plan',
  'pro.student_profile.plan_change_requests.empty': 'No hay solicitudes de cambio pendientes.',
  'pro.student_profile.plan_change_requests.review': 'Marcar como revisado',
  'pro.student_profile.plan_change_requests.dismiss': 'Descartar',
  'pro.student_profile.water_goal.title': 'Objetivo de agua del alumno',
  'pro.student_profile.water_goal.label': 'Objetivo diario (ml)',
  'pro.student_profile.water_goal.placeholder': 'ej.: 2500',
  'pro.student_profile.water_goal.save': 'Establecer objetivo',
  'pro.student_profile.water_goal.validation.required': 'La cantidad del objetivo es obligatoria.',
  'pro.student_profile.water_goal.validation.must_be_positive': 'El objetivo debe ser mayor que cero.',
  'pro.student_profile.water_goal.error': 'No se pudo establecer el objetivo de agua. Inténtalo de nuevo.',
  'pro.student_profile.entitlement_lock': 'Las acciones de plan están bloqueadas. Restaura tu suscripción para desbloquear.',
  'pro.student_profile.error': 'No se pudo cargar el perfil del alumno. Inténtalo de nuevo.',
  'pro.subscription.title': 'Suscripción',
  'pro.subscription.status.active': 'Activa',
  'pro.subscription.status.inactive': 'Inactiva',
  'pro.subscription.status.unknown': 'Verificando...',
  'pro.subscription.cap_usage': '{count} / {limit} alumnos activos',
  'pro.subscription.free_tier': 'Gratis para hasta 10 alumnos activos.',
  'pro.subscription.warning': 'Tu suscripción está a punto de expirar. Renuévala para evitar interrupciones del servicio.',
  'pro.subscription.locked': 'Las acciones de plan de alumno están bloqueadas. Restaura o adquiere una suscripción para continuar.',
  'pro.subscription.cta_purchase': 'Mejorar plan',
  'pro.subscription.cta_restore': 'Restaurar compra',
  'pro.subscription.cta_refresh': 'Actualizar estado',
  'pro.subscription.purchase_note': 'La suscripción se gestiona a través de la tienda de apps de tu dispositivo.',
  'pro.subscription.error': 'No se pudo cargar el estado de la suscripción. Inténtalo de nuevo.',
  'offline.banner': 'Estás sin conexión. Mostrando datos en caché. Las actualizaciones están bloqueadas hasta reconectar.',
  'offline.write_lock': 'Conéctate a internet para guardar cambios.',
  'offline.stale_minutes': 'Última actualización hace {value} min',
  'offline.stale_hours': 'Última actualización hace {value}h',
  'offline.stale_days': 'Última actualización hace {value}d',
  'shell.tabs.home': 'Inicio',
  'shell.tabs.explore': 'Explorar',
  'shell.modal.title': 'Modal',
  'shell.modal.body_title': 'Este es un modal',
  'shell.modal.link_home': 'Ir a la pantalla de inicio',
  'shell.home.title': '¡Bienvenido!',
  'shell.home.step1.title': 'Paso 1: Pruébalo',
  'shell.home.step1.part1': 'Edita',
  'shell.home.step1.part2': 'para ver los cambios. Pulsa',
  'shell.home.step1.part3': 'para abrir las herramientas de desarrollo.',
  'shell.home.step2.title': 'Paso 2: Explora',
  'shell.home.step2.description':
    'Toca la pestaña Explorar para conocer lo que incluye esta app base.',
  'shell.home.step3.title': 'Paso 3: Empieza desde cero',
  'shell.home.step3.part1': 'Cuando estés listo, ejecuta',
  'shell.home.step3.part2': 'para obtener un directorio',
  'shell.home.step3.part3': 'Esto moverá el directorio actual',
  'shell.home.step3.part4': 'a',
  'shell.home.menu.action': 'Acción',
  'shell.home.menu.share': 'Compartir',
  'shell.home.menu.more': 'Más',
  'shell.home.menu.delete': 'Eliminar',
  'shell.home.alert.action': 'Acción pulsada',
  'shell.home.alert.share': 'Compartir pulsado',
  'shell.home.alert.delete': 'Eliminar pulsado',
  'shell.explore.title': 'Explorar',
  'shell.explore.description':
    'Esta app incluye código de ejemplo para ayudarte a empezar.',
  'shell.explore.section.routing.title': 'Enrutado basado en archivos',
  'shell.explore.section.routing.line1.part1': 'Esta app tiene dos pantallas:',
  'shell.explore.section.routing.line1.part2': 'y',
  'shell.explore.section.routing.line1.part3': '.',
  'shell.explore.section.routing.line2.part1': 'El archivo de layout en',
  'shell.explore.section.routing.line2.part2': 'configura el navegador de pestañas.',
  'shell.explore.section.routing.learn_more': 'Más información',
  'shell.explore.section.platform.title': 'Soporte para Android, iOS y web',
  'shell.explore.section.platform.body.part1':
    'Puedes abrir este proyecto en Android, iOS y web. Para abrir la versión web, pulsa',
  'shell.explore.section.platform.body.part2': 'en el terminal que ejecuta este proyecto.',
  'shell.explore.section.images.title': 'Imágenes',
  'shell.explore.section.images.body.part1':
    'Para imágenes estáticas, puedes usar los sufijos',
  'shell.explore.section.images.body.part2': 'y',
  'shell.explore.section.images.body.part3':
    'para proporcionar archivos para distintas densidades de pantalla',
  'shell.explore.section.images.learn_more': 'Más información',
  'shell.explore.section.theme.title': 'Componentes para modo claro y oscuro',
  'shell.explore.section.theme.body.part1':
    'Esta plantilla tiene soporte para modo claro y oscuro. La función',
  'shell.explore.section.theme.body.part2':
    'te permite inspeccionar el esquema de color actual del usuario y ajustar los colores de la UI.',
  'shell.explore.section.theme.learn_more': 'Más información',
  'shell.explore.section.animations.title': 'Animaciones',
  'shell.explore.section.animations.body.part1':
    'Esta plantilla incluye un ejemplo de componente animado. El componente',
  'shell.explore.section.animations.body.part2': 'usa la potente librería',
  'shell.explore.section.animations.body.part3':
    'para crear una animación de una mano saludando.',
  'shell.explore.section.animations.ios_extra.part1': 'El componente',
  'shell.explore.section.animations.ios_extra.part2':
    'proporciona un efecto parallax para la imagen de cabecera.',
};
