import type { TranslationKey } from './en-US';

export const ptBR: Record<TranslationKey, string> = {
  'common.error.generic': 'Algo deu errado. Tente novamente.',
  'auth.field.email': 'E-mail',
  'auth.field.name': 'Nome',
  'auth.field.password': 'Senha',
  'auth.field.password_confirmation': 'Confirmar senha',
  'auth.placeholder.email': 'E-mail',
  'auth.placeholder.name': 'Nome completo',
  'auth.placeholder.password': 'Senha',
  'auth.placeholder.password_confirmation': 'Confirmar senha',
  'auth.validation.name_required': 'Nome é obrigatório.',
  'auth.validation.email_required': 'E-mail é obrigatório.',
  'auth.validation.password_required': 'Senha é obrigatória.',
  'auth.validation.password_confirmation_required': 'A confirmação de senha é obrigatória.',
  'auth.validation.password_policy':
    'Use pelo menos 8 caracteres com letra maiúscula, número e símbolo ASCII (ex.: ! @ #). Emoji não é permitido.',
  'auth.validation.password_confirmation_mismatch':
    'A confirmação de senha deve ser igual à senha.',
  'auth.signin.title': 'Que bom ter você de volta',
  'auth.signin.cta_primary': 'Entrar',
  'auth.signin.cta_create': 'Criar conta',
  'auth.signin.or_continue': 'ou continue com',
  'auth.signin.error.invalid_credentials':
    'E-mail ou senha incorretos. Tente novamente ou redefina sua senha.',
  'auth.signin.error.network': 'Não foi possível conectar agora. Verifique sua conexão e tente novamente.',
  'auth.signin.error.provider_conflict':
    'Este e-mail já está vinculado a outro método de acesso. Entre primeiro com o método já vinculado.',
  'auth.signin.error.configuration':
    'A autenticação ainda não está configurada. Defina as chaves do Firebase e tente novamente.',
  'auth.social.google': 'Google',
  'auth.social.apple': 'Apple',
  'auth.password.toggle_show': 'Mostrar senha',
  'auth.password.toggle_hide': 'Ocultar senha',
  'auth.password.toggle_show_short': 'Mostrar',
  'auth.password.toggle_hide_short': 'Ocultar',
  'auth.signup.title': 'Crie sua conta',
  'auth.signup.cta_primary': 'Criar conta',
  'auth.signup.or_continue': 'ou continue com',
  'auth.signup.password_helper':
    'Use pelo menos 8 caracteres, incluindo maiúscula, número e símbolo (ex.: ! @ #).',
  'auth.signup.error.duplicate_email': 'Este e-mail já está em uso. Entre para continuar.',
  'auth.signup.error.network': 'Não foi possível conectar agora. Verifique sua conexão e tente novamente.',
  'auth.signup.error.provider_conflict':
    'Este e-mail já está vinculado a outro método de acesso. Entre primeiro com o método já vinculado.',
  'auth.signup.error.configuration':
    'A autenticação ainda não está configurada. Defina as chaves do Firebase e tente novamente.',
  'auth.signup.placeholder.body':
    'A implementação do formulário de criação de conta começa na próxima etapa.',
  'auth.signup.cta_back_signin': 'Voltar para entrar',
  'auth.role.title': 'Como você quer usar o app?',
  'auth.role.intro': 'Você pode começar por conta própria agora e se conectar com um profissional depois.',
  'auth.role.option_self.title': 'Quero acompanhar meu próprio progresso',
  'auth.role.option_self.subtitle':
    'Registre refeições e treinos por conta própria. Nenhum profissional é necessário.',
  'auth.role.option_pro.title': 'Sou nutricionista ou treinador físico',
  'auth.role.option_pro.subtitle':
    'Gerencie clientes, atribua planos e acompanhe o progresso dos alunos.',
  'auth.role.lock_note':
    'O tipo de conta não pode ser alterado depois. Você pode criar outra conta com outro e-mail, se precisar.',
  'auth.role.cta_continue': 'Continuar',
  'auth.role.cta_back': 'Voltar',
  'auth.role.cta_start_self_guided': 'Começar por conta própria agora',
  'auth.role.validation.required': 'Escolha como quer usar o app para continuar.',
  'auth.role.error.save_failed': 'Não foi possível salvar seu perfil agora. Tente novamente.',
  'auth.role.placeholder.title': 'Seleção de perfil',
  'auth.role.placeholder.body':
    'O fluxo de login já está ligado. A implementação da seleção de perfil é a próxima etapa.',
  'auth.role.placeholder.cta_open_app_shell': 'Abrir app',
  'student.hydration.card_title': 'Consumo de água',
  'student.hydration.progress': '{consumed} / {goal} ml',
  'student.hydration.cta_log': 'Registrar água',
  'student.hydration.cta_set_goal': 'Definir meta de água',
  'student.hydration.goal_owner_student': 'Usando sua meta pessoal de água',
  'student.hydration.goal_owner_nutritionist': 'Meta diária de água definida pelo seu nutricionista',
  'student.hydration.streak': 'Sequência atual: {days} dias',
  'shell.common.period': '.',
  'shell.token.path.tabs_index': 'app/(tabs)/index.tsx',
  'shell.token.path.tabs_explore': 'app/(tabs)/explore.tsx',
  'shell.token.path.tabs_layout': 'app/(tabs)/_layout.tsx',
  'shell.token.path.components_hello_wave': 'components/HelloWave.tsx',
  'shell.token.path.components_parallax_scroll_view': 'components/ParallaxScrollView.tsx',
  'shell.token.path.app': 'app',
  'shell.token.path.app_example': 'app-example',
  'shell.token.command.reset_project': 'npm run reset-project',
  'shell.token.shortcut.devtools_ios': 'cmd + d',
  'shell.token.shortcut.devtools_android': 'cmd + m',
  'shell.token.shortcut.devtools_web': 'F12',
  'shell.token.shortcut.open_web': 'w',
  'shell.token.image_suffix.2x': '@2x',
  'shell.token.image_suffix.3x': '@3x',
  'shell.token.hook.use_color_scheme': 'useColorScheme()',
  'shell.token.library.react_native_reanimated': 'react-native-reanimated',
  'shell.tabs.home': 'Início',
  'shell.tabs.explore': 'Explorar',
  'shell.modal.title': 'Modal',
  'shell.modal.body_title': 'Este é um modal',
  'shell.modal.link_home': 'Ir para a tela inicial',
  'shell.home.title': 'Boas-vindas!',
  'shell.home.step1.title': 'Passo 1: Teste',
  'shell.home.step1.part1': 'Edite',
  'shell.home.step1.part2': 'para ver as mudanças. Pressione',
  'shell.home.step1.part3': 'para abrir as ferramentas de desenvolvimento.',
  'shell.home.step2.title': 'Passo 2: Explore',
  'shell.home.step2.description':
    'Toque na aba Explorar para conhecer o que está incluído neste app base.',
  'shell.home.step3.title': 'Passo 3: Comece do zero',
  'shell.home.step3.part1': 'Quando estiver pronto, execute',
  'shell.home.step3.part2': 'para obter um novo diretório',
  'shell.home.step3.part3': 'Isso moverá o diretório atual',
  'shell.home.step3.part4': 'para',
  'shell.home.menu.action': 'Ação',
  'shell.home.menu.share': 'Compartilhar',
  'shell.home.menu.more': 'Mais',
  'shell.home.menu.delete': 'Excluir',
  'shell.home.alert.action': 'Ação pressionada',
  'shell.home.alert.share': 'Compartilhar pressionado',
  'shell.home.alert.delete': 'Excluir pressionado',
  'shell.explore.title': 'Explorar',
  'shell.explore.description': 'Este app inclui código de exemplo para ajudar você a começar.',
  'shell.explore.section.routing.title': 'Roteamento por arquivos',
  'shell.explore.section.routing.line1.part1': 'Este app tem duas telas:',
  'shell.explore.section.routing.line1.part2': 'e',
  'shell.explore.section.routing.line1.part3': '.',
  'shell.explore.section.routing.line2.part1': 'O arquivo de layout em',
  'shell.explore.section.routing.line2.part2': 'configura o navegador de abas.',
  'shell.explore.section.routing.learn_more': 'Saiba mais',
  'shell.explore.section.platform.title': 'Suporte para Android, iOS e web',
  'shell.explore.section.platform.body.part1':
    'Você pode abrir este projeto em Android, iOS e web. Para abrir a versão web, pressione',
  'shell.explore.section.platform.body.part2': 'no terminal que está rodando este projeto.',
  'shell.explore.section.images.title': 'Imagens',
  'shell.explore.section.images.body.part1': 'Para imagens estáticas, você pode usar os sufixos',
  'shell.explore.section.images.body.part2': 'e',
  'shell.explore.section.images.body.part3':
    'para fornecer arquivos para diferentes densidades de tela',
  'shell.explore.section.images.learn_more': 'Saiba mais',
  'shell.explore.section.theme.title': 'Componentes para modo claro e escuro',
  'shell.explore.section.theme.body.part1': 'Este template tem suporte a modo claro e escuro. A função',
  'shell.explore.section.theme.body.part2':
    'permite verificar o esquema de cores atual do usuário e ajustar as cores da UI.',
  'shell.explore.section.theme.learn_more': 'Saiba mais',
  'shell.explore.section.animations.title': 'Animações',
  'shell.explore.section.animations.body.part1':
    'Este template inclui um exemplo de componente animado. O componente',
  'shell.explore.section.animations.body.part2': 'usa a poderosa biblioteca',
  'shell.explore.section.animations.body.part3': 'para criar uma animação de mão acenando.',
  'shell.explore.section.animations.ios_extra.part1': 'O componente',
  'shell.explore.section.animations.ios_extra.part2':
    'fornece um efeito parallax para a imagem do cabeçalho.',
};
