import type { TranslationKey } from './en-US';

export const ptBR: Record<TranslationKey, string> = {
  'common.error.generic': 'Algo deu errado. Tente novamente.',
  'auth.field.email': 'E-mail',
  'auth.field.name': 'Nome',
  'auth.field.password': 'Senha',
  'auth.field.password_confirmation': 'Confirmar senha',
  'auth.placeholder.email': 'E-mail',
  'auth.placeholder.name': 'Nome completo',
  'auth.placeholder.password': 'Senha',
  'auth.placeholder.password_confirmation': 'Confirmar senha',
  'auth.validation.name_required': 'Nome é obrigatório.',
  'auth.validation.email_required': 'E-mail é obrigatório.',
  'auth.validation.password_required': 'Senha é obrigatória.',
  'auth.validation.password_confirmation_required': 'A confirmação de senha é obrigatória.',
  'auth.validation.password_policy':
    'Use pelo menos 8 caracteres com letra maiúscula, número e símbolo ASCII (ex.: ! @ #). Emoji não é permitido.',
  'auth.validation.password_confirmation_mismatch':
    'A confirmação de senha deve ser igual à senha.',
  'auth.signin.title': 'Que bom ter você de volta',
  'auth.signin.cta_primary': 'Entrar',
  'auth.signin.cta_create': 'Criar conta',
  'auth.signin.or_continue': 'ou continue com',
  'auth.signin.error.invalid_credentials':
    'E-mail ou senha incorretos. Tente novamente ou redefina sua senha.',
  'auth.signin.error.network': 'Não foi possível conectar agora. Verifique sua conexão e tente novamente.',
  'auth.signin.error.provider_conflict':
    'Este e-mail já está vinculado a outro método de acesso. Entre primeiro com o método já vinculado.',
  'auth.signin.error.configuration':
    'A autenticação ainda não está configurada. Defina as chaves do Firebase e tente novamente.',
  'auth.social.google': 'Google',
  'auth.social.apple': 'Apple',
  'auth.password.toggle_show': 'Mostrar senha',
  'auth.password.toggle_hide': 'Ocultar senha',
  'auth.password.toggle_show_short': 'Mostrar',
  'auth.password.toggle_hide_short': 'Ocultar',
  'auth.signup.title': 'Crie sua conta',
  'auth.signup.cta_primary': 'Criar conta',
  'auth.signup.or_continue': 'ou continue com',
  'auth.signup.password_helper':
    'Use pelo menos 8 caracteres, incluindo maiúscula, número e símbolo (ex.: ! @ #).',
  'auth.signup.error.duplicate_email': 'Este e-mail já está em uso. Entre para continuar.',
  'auth.signup.error.network': 'Não foi possível conectar agora. Verifique sua conexão e tente novamente.',
  'auth.signup.error.provider_conflict':
    'Este e-mail já está vinculado a outro método de acesso. Entre primeiro com o método já vinculado.',
  'auth.signup.error.configuration':
    'A autenticação ainda não está configurada. Defina as chaves do Firebase e tente novamente.',
  'auth.signup.placeholder.body':
    'A implementação do formulário de criação de conta começa na próxima etapa.',
  'auth.signup.cta_back_signin': 'Voltar para entrar',
  'auth.role.title': 'Como você quer usar o app?',
  'auth.role.intro': 'Você pode começar por conta própria agora e se conectar com um profissional depois.',
  'auth.role.option_self.title': 'Quero acompanhar meu próprio progresso',
  'auth.role.option_self.subtitle':
    'Registre refeições e treinos por conta própria. Nenhum profissional é necessário.',
  'auth.role.option_pro.title': 'Sou nutricionista ou treinador físico',
  'auth.role.option_pro.subtitle':
    'Gerencie clientes, atribua planos e acompanhe o progresso dos alunos.',
  'auth.role.lock_note':
    'O tipo de conta não pode ser alterado depois. Você pode criar outra conta com outro e-mail, se precisar.',
  'auth.role.cta_continue': 'Continuar',
  'auth.role.cta_back': 'Voltar',
  'auth.role.cta_start_self_guided': 'Começar por conta própria agora',
  'auth.role.validation.required': 'Escolha como quer usar o app para continuar.',
  'auth.role.error.save_failed': 'Não foi possível salvar seu perfil agora. Tente novamente.',
  'auth.role.placeholder.title': 'Seleção de perfil',
  'auth.role.placeholder.body':
    'O fluxo de login já está ligado. A implementação da seleção de perfil é a próxima etapa.',
  'auth.role.placeholder.cta_open_app_shell': 'Abrir app',
  'student.home.no_pro.title': 'Nenhum profissional conectado ainda',
  'student.home.no_pro.body': 'Você ainda pode começar a acompanhar hoje por conta própria.',
  'student.home.cta_start_nutrition': 'Começar meu plano de nutrição',
  'student.home.cta_start_training': 'Começar meu plano de treino',
  'student.home.cta_manage_professionals': 'Gerenciar profissionais',
  'student.home.offline.stale_badge': 'Os dados podem estar desatualizados',
  'student.home.offline.last_sync': 'Última atualização: {datetime}',
  'student.home.offline.banner_read_only':
    'Você está offline. Você pode ver dados em cache, mas as atualizações ficam bloqueadas até a conexão voltar.',
  'student.home.offline.write_lock': 'Conecte-se à internet para salvar alterações.',
  'relationship.title': 'Conectar com profissionais',
  'relationship.intro': 'Tem um profissional? Insira o código de convite.',
  'relationship.helper_self_guided': 'Ainda não tem? Você pode continuar usando o app por conta própria.',
  'relationship.input.invite_code': 'Inserir código de convite',
  'relationship.cta_scan_qr': 'Escanear QR code',
  'relationship.qr.permission_denied':
    'O acesso à câmera é necessário para escanear um QR code. Conceda a permissão nas configurações do dispositivo ou insira o código manualmente.',
  'relationship.qr.invalid_payload':
    'Este QR code não contém um código de convite válido. Tente escanear novamente ou insira o código manualmente.',
  'relationship.qr.close': 'Fechar scanner',
  'relationship.cta_submit_code': 'Conectar',
  'relationship.error.invalid_code':
    'Este código de convite é inválido. Peça um novo código ao profissional.',
  'relationship.error.already_connected':
    'Você já está conectado a um profissional nesta especialidade.',
  'relationship.error.pending_cap':
    'Este profissional está com muitas solicitações pendentes agora. Tente novamente mais tarde.',
  'relationship.error.network': 'Não foi possível conectar agora. Verifique sua conexão e tente novamente.',
  'relationship.error.unknown': 'Algo deu errado. Tente novamente.',
  'relationship.pending.helper': 'Aguardando confirmação do profissional para ativar esta conexão.',
  'relationship.pending.canceled_code_rotated':
    'Esta solicitação foi cancelada porque o profissional regenerou o código de convite. Peça o novo código para se conectar novamente.',
  'relationship.empty.cta_continue_self': 'Continuar por conta própria',
  'relationship.unbind.cta': 'Encerrar conexão',
  'relationship.unbind.confirm_title': 'Encerrar esta conexão profissional?',
  'relationship.unbind.confirm_body':
    'Você pode se reconectar depois com um código de convite. Seu histórico será mantido.',
  'relationship.unbind.confirm_yes': 'Encerrar conexão',
  'relationship.unbind.confirm_no': 'Manter conexão',
  'relationship.unbind.error': 'Não foi possível encerrar a conexão. Tente novamente.',
  'relationship.credential.registry_id': 'Registro profissional',
  'relationship.credential.authority': 'Órgão',
  'relationship.credential.country': 'País',
  'pro.pending.search.placeholder': 'Buscar solicitações pendentes',
  'pro.pending.filter.label': 'Filtrar solicitações',
  'pro.pending.bulk_deny.cta': 'Negar selecionadas',
  'pro.pending.bulk_deny.confirm_title': 'Negar solicitações selecionadas?',
  'pro.pending.bulk_deny.confirm_body':
    'Alunos selecionados podem solicitar novamente depois com seu código de convite.',
  'pro.pending.bulk_deny.success': 'Solicitações negadas com sucesso.',
  'pro.pending.confirm.cta': 'Aceitar',
  'pro.pending.deny.cta': 'Negar',
  'pro.pending.empty': 'Nenhuma solicitação de conexão pendente.',
  'pro.pending.error': 'Não foi possível carregar as solicitações pendentes. Tente novamente.',
  'common.error.retry': 'Tentar novamente',
  'common.loading.default': 'Carregando...',
  'common.empty.no_data': 'Ainda não há nada aqui.',
  'student.hydration.card_title': 'Consumo de água',
  'student.hydration.progress': '{consumed} / {goal} ml',
  'student.hydration.cta_log': 'Registrar água',
  'student.hydration.cta_set_goal': 'Definir meta de água',
  'student.hydration.goal_owner_student': 'Usando sua meta pessoal de água',
  'student.hydration.goal_owner_nutritionist': 'Meta diária de água definida pelo seu nutricionista',
  'student.hydration.streak': 'Sequência atual: {days} dias',
  'shell.common.period': '.',
  'shell.token.path.tabs_index': 'app/(tabs)/index.tsx',
  'shell.token.path.tabs_explore': 'app/(tabs)/explore.tsx',
  'shell.token.path.tabs_layout': 'app/(tabs)/_layout.tsx',
  'shell.token.path.components_hello_wave': 'components/HelloWave.tsx',
  'shell.token.path.components_parallax_scroll_view': 'components/ParallaxScrollView.tsx',
  'shell.token.path.app': 'app',
  'shell.token.path.app_example': 'app-example',
  'shell.token.command.reset_project': 'npm run reset-project',
  'shell.token.shortcut.devtools_ios': 'cmd + d',
  'shell.token.shortcut.devtools_android': 'cmd + m',
  'shell.token.shortcut.devtools_web': 'F12',
  'shell.token.shortcut.open_web': 'w',
  'shell.token.image_suffix.2x': '@2x',
  'shell.token.image_suffix.3x': '@3x',
  'shell.token.hook.use_color_scheme': 'useColorScheme()',
  'shell.token.library.react_native_reanimated': 'react-native-reanimated',
  'student.home.title': 'Meu Painel',
  'student.home.hydration.title': 'Ingestão de água',
  'student.home.hydration.progress': '{consumed} / {goal} ml',
  'student.home.hydration.streak': 'Sequência: {days} dias',
  'student.home.hydration.goal_student': 'Usando seu objetivo pessoal de água',
  'student.home.hydration.goal_nutritionist': 'Objetivo diário definido pelo seu nutricionista',
  'student.home.hydration.no_goal': 'Defina um objetivo diário de água para acompanhar o progresso',
  'student.home.nutrition.section': 'Nutrição',
  'student.home.training.section': 'Treino',
  'student.home.pending_connection': 'Aguardando confirmação do profissional',
  'student.home.cta_nutrition': 'Ir para nutrição',
  'student.home.cta_training': 'Ir para treino',
  'student.home.cta_professionals': 'Gerenciar profissionais',
  'student.nutrition.title': 'Nutrição de hoje',
  'student.nutrition.empty.title': 'Nenhuma refeição registrada ainda',
  'student.nutrition.empty.body': 'Sem nutricionista? Você ainda pode criar e monitorar seu próprio plano hoje.',
  'student.nutrition.empty.cta': 'Iniciar meu plano de nutrição',
  'student.nutrition.water.title': 'Ingestão de água',
  'student.nutrition.water.personal_goal': 'Defina seu objetivo diário de água.',
  'student.nutrition.water.nutritionist_goal': 'Objetivo diário definido pelo seu nutricionista.',
  'student.nutrition.water.cta_log': 'Registrar água',
  'student.nutrition.water.cta_set_goal': 'Definir objetivo de água',
  'student.nutrition.water.log.label': 'Quantidade (ml)',
  'student.nutrition.water.log.placeholder': 'ex.: 250',
  'student.nutrition.water.log.validation.required': 'A quantidade é obrigatória.',
  'student.nutrition.water.log.validation.must_be_positive': 'A quantidade deve ser maior que zero.',
  'student.nutrition.water.goal.label': 'Objetivo diário (ml)',
  'student.nutrition.water.goal.placeholder': 'ex.: 2000',
  'student.nutrition.water.goal.validation.required': 'O objetivo é obrigatório.',
  'student.nutrition.water.goal.validation.must_be_positive': 'O objetivo deve ser maior que zero.',
  'student.nutrition.plan_change.cta': 'Solicitar mudança no plano',
  'student.nutrition.plan_change.title': 'Solicitar mudança no plano',
  'student.nutrition.plan_change.label': 'O que você gostaria de mudar?',
  'student.nutrition.plan_change.placeholder': 'Descreva o que você gostaria de ajustar...',
  'student.nutrition.plan_change.validation.required': 'A descrição da solicitação é obrigatória.',
  'student.nutrition.plan_change.validation.too_short': 'Por favor, descreva sua solicitação com mais detalhes.',
  'student.nutrition.plan_change.error.plan_not_found': 'Plano não encontrado. Atualize a tela.',
  'student.nutrition.plan_change.error.no_active_assignment': 'Você não tem um plano atribuído ativo.',
  'student.nutrition.plan_change.error.network': 'Sem conexão. Verifique sua conexão e tente novamente.',
  'student.nutrition.plan_change.error.unknown': 'Algo deu errado. Tente novamente.',
  'student.nutrition.plan_change.success': 'Solicitação de mudança enviada.',
  'student.nutrition.assigned_plan.read_only_notice': 'Seu plano de nutrição foi atribuído por um profissional. Entre em contato com seu nutricionista para solicitar mudanças.',
  'student.training.title': 'Treino de hoje',
  'student.training.empty.title': 'Nenhum treino agendado ainda',
  'student.training.empty.body': 'Sem personal trainer? Você ainda pode criar seu próprio plano de treino agora.',
  'student.training.empty.cta': 'Iniciar meu plano de treino',
  'student.training.plan_change.cta': 'Solicitar mudança no plano',
  'student.training.plan_change.title': 'Solicitar mudança no plano',
  'student.training.plan_change.label': 'O que você gostaria de mudar?',
  'student.training.plan_change.placeholder': 'Descreva o que você gostaria de ajustar...',
  'student.training.plan_change.validation.required': 'A descrição da solicitação é obrigatória.',
  'student.training.plan_change.validation.too_short': 'Por favor, descreva sua solicitação com mais detalhes.',
  'student.training.plan_change.error.plan_not_found': 'Plano não encontrado. Atualize a tela.',
  'student.training.plan_change.error.no_active_assignment': 'Você não tem um plano atribuído ativo.',
  'student.training.plan_change.error.network': 'Sem conexão. Verifique sua conexão e tente novamente.',
  'student.training.plan_change.error.unknown': 'Algo deu errado. Tente novamente.',
  'student.training.plan_change.success': 'Solicitação de mudança enviada.',
  'student.training.assigned_plan.read_only_notice': 'Seu plano de treino foi atribuído por um profissional. Entre em contato com seu treinador para solicitar mudanças.',
  'pro.home.title': 'Painel',
  'pro.home.active_students': 'Alunos ativos',
  'pro.home.pending_requests': 'Solicitações pendentes',
  'pro.home.invite_code.title': 'Seu código de convite',
  'pro.home.invite_code.share': 'Compartilhar código',
  'pro.home.invite_code.rotate': 'Regenerar código',
  'pro.home.invite_code.rotate_confirm_title': 'Regenerar código de convite?',
  'pro.home.invite_code.rotate_confirm_body': 'Seu código atual será invalidado e todas as solicitações pendentes vinculadas a ele serão canceladas automaticamente.',
  'pro.home.invite_code.rotate_confirm_yes': 'Regenerar',
  'pro.home.invite_code.rotate_confirm_no': 'Cancelar',
  'pro.home.invite_code.rotate_error': 'Não foi possível regenerar o código. Tente novamente.',
  'pro.home.invite_code.empty': 'Nenhum código de convite ativo.',
  'pro.home.cta_roster': 'Ver lista de alunos',
  'pro.home.cta_pending': 'Gerenciar solicitações pendentes',
  'pro.home.subscription.warning': 'Sua assinatura está prestes a expirar. Renove para continuar gerenciando todos os seus alunos.',
  'pro.home.subscription.cta_renew': 'Renovar assinatura',
  'pro.home.entitlement_lock': 'As ações de plano de aluno estão bloqueadas. Restaure sua assinatura para desbloquear.',
  'pro.home.error': 'Não foi possível carregar os dados do painel. Tente novamente.',
  'pro.specialty.title': 'Suas especialidades',
  'pro.specialty.nutritionist': 'Nutricionista',
  'pro.specialty.fitness_coach': 'Personal Trainer',
  'pro.specialty.add_nutritionist': 'Adicionar Nutricionista',
  'pro.specialty.add_fitness_coach': 'Adicionar Personal Trainer',
  'pro.specialty.remove': 'Remover',
  'pro.specialty.remove_blocked.active': 'Não é possível remover: há alunos ativos nesta especialidade.',
  'pro.specialty.remove_blocked.pending': 'Não é possível remover: há alunos pendentes nesta especialidade.',
  'pro.specialty.remove_blocked.last': 'Não é possível remover: pelo menos uma especialidade é obrigatória.',
  'pro.specialty.remove_error': 'Não foi possível remover a especialidade. Tente novamente.',
  'pro.specialty.add_error': 'Não foi possível adicionar a especialidade. Tente novamente.',
  'pro.specialty.credential.title': 'Credencial de registro (opcional)',
  'pro.specialty.credential.registry_id.label': 'Número de registro',
  'pro.specialty.credential.registry_id.placeholder': 'ex.: CRN-12345',
  'pro.specialty.credential.authority.label': 'Órgão',
  'pro.specialty.credential.authority.placeholder': 'ex.: CFN',
  'pro.specialty.credential.country.label': 'País',
  'pro.specialty.credential.country.placeholder': 'ex.: Brasil',
  'pro.specialty.credential.save': 'Salvar credencial',
  'pro.specialty.credential.skip': 'Pular',
  'pro.specialty.credential.save_error': 'Não foi possível salvar a credencial. Tente novamente.',
  'pro.specialty.empty': 'Nenhuma especialidade adicionada ainda.',
  'pro.specialty.removal_assist.view_active': 'Ver alunos ativos',
  'pro.specialty.removal_assist.view_active_desc': 'Veja e gerencie as atribuições de alunos ativos',
  'pro.specialty.removal_assist.view_pending': 'Ver solicitações pendentes',
  'pro.specialty.removal_assist.view_pending_desc': 'Revise as solicitações de conexão pendentes',
  'pro.specialty.removal_assist.bulk_deny': 'Negar solicitações pendentes',
  'pro.specialty.removal_assist.bulk_deny_desc': 'Negar em massa solicitações pendentes para liberar bloqueios',
  'pro.specialty.removal_assist.add_specialty': 'Adicionar outra especialidade',
  'pro.specialty.removal_assist.add_specialty_desc': 'Adicione Nutricionista ou Personal Trainer para permitir remoção',
  'pro.specialty.removal_blocked.title': 'Não é possível remover a especialidade',
  'pro.specialty.removal_blocked.active_students_body': 'Esta especialidade tem {count} aluno{plural} ativo. Desvincule ou conclua as atribuições ativas primeiro.',
  'pro.specialty.removal_blocked.pending_students_body': 'Esta especialidade tem {count} aluno{plural} pendente. Aceite ou negue as solicitações pendentes primeiro.',
  'pro.specialty.removal_blocked.last_specialty_body': 'Você deve ter pelo menos uma especialidade. Adicione uma nova especialidade antes de remover esta.',
  'pro.students.title': 'Meus alunos',
  'pro.students.search.placeholder': 'Buscar alunos',
  'pro.students.filter.active': 'Ativos',
  'pro.students.filter.pending': 'Pendentes',
  'pro.students.filter.all': 'Todos',
  'pro.students.empty': 'Nenhum aluno ainda.',
  'pro.students.error': 'Não foi possível carregar a lista de alunos. Tente novamente.',
  'pro.students.bulk_assign.cta': 'Atribuir plano em massa',
  'pro.students.bulk_assign.select_hint': 'Selecione alunos para atribuir um plano.',
  'pro.students.specialty.nutritionist': 'Nutricionista',
  'pro.students.specialty.fitness_coach': 'Personal Trainer',
  'pro.student_profile.title': 'Perfil do aluno',
  'pro.student_profile.specialty.nutritionist': 'Nutrição',
  'pro.student_profile.specialty.fitness_coach': 'Treino',
  'pro.student_profile.assignment.active': 'Ativo',
  'pro.student_profile.assignment.pending': 'Aguardando confirmação',
  'pro.student_profile.assignment.none': 'Sem atribuição ativa',
  'pro.student_profile.unbind.cta': 'Encerrar atribuição',
  'pro.student_profile.unbind.confirm_title': 'Encerrar esta atribuição?',
  'pro.student_profile.unbind.confirm_body': 'O aluno será desvinculado. O histórico será mantido.',
  'pro.student_profile.unbind.confirm_yes': 'Encerrar atribuição',
  'pro.student_profile.unbind.confirm_no': 'Manter atribuição',
  'pro.student_profile.unbind.error': 'Não foi possível encerrar a atribuição. Tente novamente.',
  'pro.student_profile.plan_change_requests.title': 'Solicitações de mudança de plano',
  'pro.student_profile.plan_change_requests.empty': 'Nenhuma solicitação de mudança pendente.',
  'pro.student_profile.plan_change_requests.load_error': 'Não foi possível carregar as solicitações. Tente novamente.',
  'pro.student_profile.plan_change_requests.action_error': 'Não foi possível atualizar a solicitação. Tente novamente.',
  'pro.student_profile.plan_change_requests.review': 'Marcar como revisado',
  'pro.student_profile.plan_change_requests.dismiss': 'Dispensar',
  'pro.student_profile.water_goal.title': 'Meta de água do aluno',
  'pro.student_profile.water_goal.label': 'Meta diária (ml)',
  'pro.student_profile.water_goal.placeholder': 'ex.: 2500',
  'pro.student_profile.water_goal.save': 'Definir meta',
  'pro.student_profile.water_goal.validation.required': 'A quantidade da meta é obrigatória.',
  'pro.student_profile.water_goal.validation.must_be_positive': 'A meta deve ser maior que zero.',
  'pro.student_profile.water_goal.error': 'Não foi possível definir a meta de água. Tente novamente.',
  'pro.student_profile.entitlement_lock': 'As ações de plano estão bloqueadas. Restaure sua assinatura para desbloquear.',
  'pro.student_profile.error': 'Não foi possível carregar o perfil do aluno. Tente novamente.',
  'pro.subscription.title': 'Assinatura',
  'pro.subscription.status.active': 'Ativa',
  'pro.subscription.status.inactive': 'Inativa',
  'pro.subscription.status.unknown': 'Verificando...',
  'pro.subscription.cap_usage': '{count} / {limit} alunos ativos',
  'pro.subscription.free_tier': 'Gratuito para até 10 alunos ativos.',
  'pro.subscription.warning': 'Sua assinatura está prestes a expirar. Renove para evitar interrupção do serviço.',
  'pro.subscription.locked': 'As ações de plano de aluno estão bloqueadas. Restaure ou adquira uma assinatura para continuar.',
  'pro.subscription.cta_purchase': 'Fazer upgrade',
  'pro.subscription.cta_restore': 'Restaurar compra',
  'pro.subscription.cta_refresh': 'Atualizar status',
  'pro.subscription.purchase_note': 'A assinatura é gerenciada pela loja de aplicativos do seu dispositivo.',
  'pro.subscription.error': 'Não foi possível carregar o status da assinatura. Tente novamente.',
  'offline.banner': 'Você está offline. Mostrando dados em cache. Atualizações bloqueadas até reconectar.',
  'offline.write_lock': 'Conecte à internet para salvar alterações.',
  'offline.stale_minutes': 'Última atualização há {value} min',
  'offline.stale_hours': 'Última atualização há {value}h',
  'offline.stale_days': 'Última atualização há {value}d',
  'shell.tabs.home': 'Início',
  'shell.tabs.dashboard': 'Painel',
  'shell.tabs.students': 'Alunos',
  'shell.tabs.nutrition': 'Nutrição',
  'shell.tabs.training': 'Treino',
  'shell.tabs.recipes': 'Receitas',
  'shell.tabs.account': 'Conta',
  'shell.tabs.explore': 'Explorar',
  'shell.placeholder.coming_soon': 'Em breve. Verifique após a próxima atualização.',
  'shell.modal.title': 'Modal',
  'shell.modal.body_title': 'Este é um modal',
  'shell.modal.link_home': 'Ir para a tela inicial',
  'shell.home.title': 'Boas-vindas!',
  'shell.home.step1.title': 'Passo 1: Teste',
  'shell.home.step1.part1': 'Edite',
  'shell.home.step1.part2': 'para ver as mudanças. Pressione',
  'shell.home.step1.part3': 'para abrir as ferramentas de desenvolvimento.',
  'shell.home.step2.title': 'Passo 2: Explore',
  'shell.home.step2.description':
    'Toque na aba Explorar para conhecer o que está incluído neste app base.',
  'shell.home.step3.title': 'Passo 3: Comece do zero',
  'shell.home.step3.part1': 'Quando estiver pronto, execute',
  'shell.home.step3.part2': 'para obter um novo diretório',
  'shell.home.step3.part3': 'Isso moverá o diretório atual',
  'shell.home.step3.part4': 'para',
  'shell.home.menu.action': 'Ação',
  'shell.home.menu.share': 'Compartilhar',
  'shell.home.menu.more': 'Mais',
  'shell.home.menu.delete': 'Excluir',
  'shell.home.alert.action': 'Ação pressionada',
  'shell.home.alert.share': 'Compartilhar pressionado',
  'shell.home.alert.delete': 'Excluir pressionado',
  'shell.explore.title': 'Explorar',
  'shell.explore.description': 'Este app inclui código de exemplo para ajudar você a começar.',
  'shell.explore.section.routing.title': 'Roteamento por arquivos',
  'shell.explore.section.routing.line1.part1': 'Este app tem duas telas:',
  'shell.explore.section.routing.line1.part2': 'e',
  'shell.explore.section.routing.line1.part3': '.',
  'shell.explore.section.routing.line2.part1': 'O arquivo de layout em',
  'shell.explore.section.routing.line2.part2': 'configura o navegador de abas.',
  'shell.explore.section.routing.learn_more': 'Saiba mais',
  'shell.explore.section.platform.title': 'Suporte para Android, iOS e web',
  'shell.explore.section.platform.body.part1':
    'Você pode abrir este projeto em Android, iOS e web. Para abrir a versão web, pressione',
  'shell.explore.section.platform.body.part2': 'no terminal que está rodando este projeto.',
  'shell.explore.section.images.title': 'Imagens',
  'shell.explore.section.images.body.part1': 'Para imagens estáticas, você pode usar os sufixos',
  'shell.explore.section.images.body.part2': 'e',
  'shell.explore.section.images.body.part3':
    'para fornecer arquivos para diferentes densidades de tela',
  'shell.explore.section.images.learn_more': 'Saiba mais',
  'shell.explore.section.theme.title': 'Componentes para modo claro e escuro',
  'shell.explore.section.theme.body.part1': 'Este template tem suporte a modo claro e escuro. A função',
  'shell.explore.section.theme.body.part2':
    'permite verificar o esquema de cores atual do usuário e ajustar as cores da UI.',
  'shell.explore.section.theme.learn_more': 'Saiba mais',
  'shell.explore.section.animations.title': 'Animações',
  'shell.explore.section.animations.body.part1':
    'Este template inclui um exemplo de componente animado. O componente',
  'shell.explore.section.animations.body.part2': 'usa a poderosa biblioteca',
  'shell.explore.section.animations.body.part3': 'para criar uma animação de mão acenando.',
  'shell.explore.section.animations.ios_extra.part1': 'O componente',
  'shell.explore.section.animations.ios_extra.part2':
    'fornece um efeito parallax para a imagem do cabeçalho.',
  'settings.account.title': 'Conta e Privacidade',
  'settings.account.privacy_policy.label': 'Política de Privacidade',
  'settings.account.privacy_policy.cta': 'Ver Política de Privacidade',
  'settings.account.delete.title': 'Excluir conta',
  'settings.account.delete.body': 'Excluir sua conta remove seus dados pessoais. Alguns registros anonimizados podem ser retidos conforme exigido pela política.',
  'settings.account.delete.cta': 'Solicitar exclusão de conta',
  'settings.account.delete.confirm_title': 'Excluir sua conta?',
  'settings.account.delete.confirm_body': 'Esta ação é irreversível. Suas informações pessoais serão removidas. Histórico anonimizado pode ser retido por requisitos legais, financeiros e de continuidade.',
  'settings.account.delete.confirm_yes': 'Excluir conta',
  'settings.account.delete.confirm_no': 'Cancelar',
  'settings.account.delete.success': 'Sua solicitação de exclusão de conta foi enviada.',
  'settings.account.delete.error.network': 'Não foi possível conectar. Verifique sua conexão e tente novamente.',
  'settings.account.delete.error.unknown': 'Algo deu errado. Tente novamente.',
  'settings.account.delete.error.already_requested': 'Uma solicitação de exclusão já está em andamento.',
  'meal.builder.title.create': 'Criar refeição personalizada',
  'meal.builder.title.edit': 'Editar refeição',
  'meal.builder.helper': 'Informe o peso total da refeição e os nutrientes. Usamos isso para calcular qualquer porção que você registrar.',
  'meal.builder.field.name.label': 'Nome da refeição',
  'meal.builder.field.name.placeholder': 'ex.: Bowl de frango grelhado',
  'meal.builder.field.grams.label': 'Peso total (g)',
  'meal.builder.field.grams.placeholder': 'ex.: 350',
  'meal.builder.field.calories.label': 'Calorias (kcal)',
  'meal.builder.field.calories.placeholder': 'ex.: 520',
  'meal.builder.field.carbs.label': 'Carboidratos (g)',
  'meal.builder.field.carbs.placeholder': 'ex.: 45',
  'meal.builder.field.proteins.label': 'Proteínas (g)',
  'meal.builder.field.proteins.placeholder': 'ex.: 38',
  'meal.builder.field.fats.label': 'Gorduras (g)',
  'meal.builder.field.fats.placeholder': 'ex.: 12',
  'meal.builder.field.cost.label': 'Custo dos ingredientes (opcional)',
  'meal.builder.field.cost.placeholder': 'ex.: 4,50',
  'meal.builder.cta_save': 'Salvar refeição',
  'meal.builder.cta_share': 'Compartilhar receita',
  'meal.builder.image.cta_upload': 'Enviar foto',
  'meal.builder.image.cta_change': 'Alterar foto',
  'meal.builder.image.uploading': 'Enviando... {percent}%',
  'meal.builder.image.upload_failed': 'Falha ao enviar foto. Toque para tentar novamente.',
  'meal.builder.image.cta_retry': 'Tentar novamente',
  'meal.builder.validation.name_required': 'O nome da refeição é obrigatório.',
  'meal.builder.validation.grams_required': 'O peso total é obrigatório.',
  'meal.builder.validation.grams_positive': 'O peso total deve ser maior que zero.',
  'meal.builder.validation.calories_required': 'As calorias são obrigatórias.',
  'meal.builder.validation.calories_non_negative': 'As calorias devem ser zero ou mais.',
  'meal.builder.validation.carbs_required': 'Os carboidratos são obrigatórios.',
  'meal.builder.validation.carbs_non_negative': 'Os carboidratos devem ser zero ou mais.',
  'meal.builder.validation.proteins_required': 'As proteínas são obrigatórias.',
  'meal.builder.validation.proteins_non_negative': 'As proteínas devem ser zero ou mais.',
  'meal.builder.validation.fats_required': 'As gorduras são obrigatórias.',
  'meal.builder.validation.fats_non_negative': 'As gorduras devem ser zero ou mais.',
  'meal.builder.validation.cost_non_negative': 'O custo dos ingredientes deve ser zero ou mais.',
  'meal.builder.error.save': 'Não foi possível salvar a refeição. Tente novamente.',
  'meal.builder.error.load': 'Não foi possível carregar a refeição. Tente novamente.',
  'meal.builder.share.error.needs_save': 'Salve a refeição primeiro para compartilhá-la.',
  'meal.builder.share.error.unknown': 'Não foi possível gerar o link de compartilhamento. Tente novamente.',
  'meal.library.title': 'Minhas refeições personalizadas',
  'meal.library.empty.title': 'Nenhuma refeição personalizada ainda',
  'meal.library.empty.body': 'Crie sua primeira refeição personalizada para registrar porções em segundos.',
  'meal.library.cta_create': 'Criar refeição',
  'meal.library.error': 'Não foi possível carregar as refeições personalizadas. Tente novamente.',
  'meal.library.quick_log.title': 'Registrar refeição',
  'meal.library.quick_log.helper': 'Informe os gramas consumidos. Calculamos as calorias e macros automaticamente.',
  'meal.library.quick_log.field.label': 'Gramas consumidos',
  'meal.library.quick_log.field.placeholder': 'ex.: 200',
  'meal.library.quick_log.preview.calories': '{calories} kcal',
  'meal.library.quick_log.preview.macros': '{carbs}g carboidratos · {proteins}g proteína · {fats}g gordura',
  'meal.library.quick_log.cta_log': 'Registrar refeição',
  'meal.library.quick_log.cta_cancel': 'Cancelar',
  'meal.library.quick_log.validation.required': 'A quantidade é obrigatória.',
  'meal.library.quick_log.validation.positive': 'A quantidade deve ser maior que zero.',
  'meal.library.quick_log.error': 'Não foi possível salvar o registro. Tente novamente.',
  'meal.library.quick_log.success': 'Refeição registrada.',
  'meal.library.cta_share': 'Compartilhar receita',
  'meal.library.cta_edit': 'Editar',
  'shared_recipe.title': 'Salvar receita compartilhada',
  'shared_recipe.helper': 'Salve esta receita na sua conta para usá-la no seu acompanhamento diário.',
  'shared_recipe.ownership_note': 'Após salvar, esta cópia é sua, mesmo que o criador original a exclua.',
  'shared_recipe.cta_save': 'Salvar na minha conta',
  'shared_recipe.cta_cancel': 'Cancelar',
  'shared_recipe.existing_copy': 'Você já salvou esta receita na sua conta.',
  'shared_recipe.auth_required': 'Faça login para salvar esta receita. Te trazemos de volta aqui logo após o login.',
  'shared_recipe.nutrition.calories': '{calories} kcal',
  'shared_recipe.nutrition.macros': '{carbs}g carboidratos · {proteins}g proteína · {fats}g gordura',
  'shared_recipe.nutrition.weight': '{grams}g total',
  'shared_recipe.error.invalid_token': 'Este link de receita é inválido ou expirou.',
  'shared_recipe.error.network': 'Não foi possível conectar. Verifique sua conexão e tente novamente.',
  'shared_recipe.error.unknown': 'Algo deu errado. Tente novamente.',
  'shared_recipe.error.save': 'Não foi possível salvar a receita. Tente novamente.',
  'shared_recipe.success': 'Receita salva na sua conta.',
  'a11y.loading.default': 'Carregando…',
  'a11y.loading.submitting': 'Enviando…',
  'a11y.loading.saving': 'Salvando…',
  'a11y.loading.invite_code': 'Carregando código de convite…',
  'a11y.selected_count': '{count} selecionado(s)',
  'a11y.student_row': '{name}, {specialty}, {status}',
  'a11y.stat_card': '{value} {label}',
  'meal.photo_analysis.cta': 'Analisar com IA',
  'meal.photo_analysis.analyzing': 'Analisando sua refeição…',
  'meal.photo_analysis.disclaimer': 'Estes são valores estimados pela IA. Verifique antes de salvar.',
  'meal.photo_analysis.error.unrecognizable': 'Não foi possível identificar uma refeição nesta foto. Tente novamente ou preencha manualmente.',
  'meal.photo_analysis.error.quota': 'A análise por IA está temporariamente indisponível. Por favor, preencha manualmente.',
  'meal.photo_analysis.error.network': 'Erro de rede durante a análise. Verifique sua conexão e tente novamente.',
  'meal.photo_analysis.error.generic': 'A análise falhou. Você ainda pode preencher os campos manualmente.',
  'meal.photo_analysis.attach_photo.label': 'Também anexar esta foto à refeição',
  'meal.photo_analysis.confidence.low': 'Baixa confiança — confira esses valores',
  'pro.library.nutrition.title': 'Planos de Nutrição',
  'pro.library.nutrition.empty': 'Nenhum plano de nutrição ainda. Crie seu primeiro plano.',
  'pro.library.nutrition.cta_create': 'Criar plano de nutrição',
  'pro.library.training.title': 'Planos de Treino',
  'pro.library.training.empty': 'Nenhum plano de treino ainda. Crie seu primeiro plano.',
  'pro.library.training.cta_create': 'Criar plano de treino',
  'pro.library.cta_open': 'Abrir',
  'pro.library.error': 'Não foi possível carregar os planos. Tente novamente.',
  'pro.plan.nutrition.title.create': 'Criar plano de nutrição',
  'pro.plan.nutrition.title.edit': 'Editar plano de nutrição',
  'pro.plan.training.title.create': 'Criar plano de treino',
  'pro.plan.training.title.edit': 'Editar plano de treino',
  'pro.plan.field.name.label': 'Nome do plano',
  'pro.plan.field.name.placeholder': 'ex.: Déficit Calórico A',
  'pro.plan.field.calories_target.label': 'Meta de calorias (kcal)',
  'pro.plan.field.calories_target.placeholder': 'ex.: 2000',
  'pro.plan.field.carbs_target.label': 'Meta de carboidratos (g)',
  'pro.plan.field.proteins_target.label': 'Meta de proteínas (g)',
  'pro.plan.field.fats_target.label': 'Meta de gorduras (g)',
  'pro.plan.section.meals': 'Refeições',
  'pro.plan.section.sessions': 'Sessões',
  'pro.plan.cta.add_meal': 'Adicionar alimento',
  'pro.plan.cta.add_session': 'Adicionar sessão',
  'pro.plan.cta.add_item': 'Adicionar item',
  'pro.plan.cta.save': 'Salvar plano',
  'pro.plan.cta.assign': 'Atribuir ao aluno',
  'pro.plan.cta.bulk_assign': 'Atribuição em massa',
  'pro.plan.cta.clone_template': 'Começar com modelo',
  'pro.plan.template.starter_label': 'Modelos iniciais',
  'pro.plan.template.picker_title': 'Escolha um modelo inicial',
  'pro.plan.template.cta_use': 'Usar este modelo',
  'pro.plan.food_search.placeholder': 'Buscar alimentos…',
  'pro.plan.food_search.empty': 'Nenhum alimento encontrado. Tente outro termo.',
  'pro.plan.food_search.stub_notice': 'A busca de alimentos estará disponível em uma atualização futura.',
  'pro.plan.validation.name_required': 'O nome do plano é obrigatório.',
  'pro.plan.validation.name_too_short': 'O nome do plano deve ter pelo menos 2 caracteres.',
  'pro.plan.validation.calories_non_negative': 'A meta de calorias deve ser zero ou mais.',
  'pro.plan.validation.macros_non_negative': 'As metas de macronutrientes devem ser zero ou mais.',
  'pro.plan.error.save': 'Não foi possível salvar o plano. Tente novamente.',
  'pro.plan.error.load': 'Não foi possível carregar o plano. Tente novamente.',
  'pro.plan.error.assign': 'Não foi possível atribuir o plano. Tente novamente.',
  'pro.plan.assign.title': 'Atribuir plano',
  'pro.plan.assign.student_count': '{count} aluno(s) selecionado(s)',
  'pro.plan.assign.confirm': 'Confirmar atribuição',
  'pro.plan.assign.fine_tune_notice': 'Cada aluno recebe uma cópia independente que você pode ajustar antes de confirmar.',
  'pro.plan.session.field.name.label': 'Nome da sessão',
  'pro.plan.session.field.name.placeholder': 'ex.: Dia A — Superior',
  'pro.plan.session.field.notes.label': 'Notas da sessão (opcional)',
  'pro.plan.item.field.name.label': 'Nome do exercício / item',
  'pro.plan.item.field.name.placeholder': 'ex.: Supino reto',
  'pro.plan.item.field.quantity.label': 'Quantidade (opcional)',
  'pro.plan.item.field.quantity.placeholder': 'ex.: 3 séries × 10 reps',
  'pro.plan.item.field.notes.label': 'Observações (opcional)',
  'pro.plan.predefined.label': 'Plano predefinido',
};
