/**
 * Firebase Data Connect singleton initialisation.
 * Mirrors the pattern in features/auth/firebase.ts.
 * Refs: D-114
 */

import { getApp, getApps, initializeApp } from 'firebase/app';
import { getDataConnect, type DataConnect } from 'firebase/data-connect';
import Constants from 'expo-constants';

import { connectorConfig } from '@mychampions/dataconnect-generated';

type FirebaseExtraConfig = {
  apiKey?: string;
  authDomain?: string;
  projectId?: string;
  storageBucket?: string;
  messagingSenderId?: string;
  appId?: string;
};

function resolveFirebaseConfig(): FirebaseExtraConfig {
  const extra = (Constants.expoConfig?.extra ?? {}) as { firebase?: FirebaseExtraConfig };
  return extra.firebase ?? {};
}

let dcInstance: DataConnect | null = null;

/**
 * Returns the singleton DataConnect instance, initialising it on first call.
 * Uses the connectorConfig generated by `firebase dataconnect:sdk:generate`.
 */
export function getDataConnectInstance(): DataConnect {
  if (dcInstance) return dcInstance;

  const firebaseConfig = resolveFirebaseConfig();
  const app = getApps().length > 0 ? getApp() : initializeApp(firebaseConfig);
  dcInstance = getDataConnect(app, connectorConfig);
  return dcInstance;
}
