name: Android PR Checks

on:
  workflow_dispatch:

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Write .env
        run: |
          cat <<'EOF' > .env
          ${{ secrets.ENV_FILE }}
          EOF
        working-directory: .
      - name: Set app variant
        run: echo "APP_VARIANT=dev" >> "$GITHUB_ENV"
        working-directory: .
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
      - name: Install JS deps
        run: yarn install --frozen-lockfile
        working-directory: .
      - uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9 # v4.8.0
        with:
          distribution: temurin
          java-version: 17
      - name: Set CI version code
        run: echo "CI_VERSION_CODE=${{ github.run_number }}" >> $GITHUB_ENV
      - name: Run Android lint, unit tests, and debug build
        run: |
          ./gradlew \
            lintDevDebug \
            testDevDebugUnitTest \
            assembleDevDebug \
            --no-build-cache
      - name: Upload reports
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: android-failure-reports-${{ github.run_id }}
          path: android/app/build/reports
          if-no-files-found: warn
          retention-days: 1
